apiVersion: v1
kind: Service
metadata:
  name: pbm-admin-ui
  namespace: pbm-qa
  labels:
    app: pbm-admin-ui
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pbm-admin-ui