apiVersion: v1
kind: Service
metadata:
  name: eligibility
  namespace: stg
  labels:
    app: eligibility
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: eligibility
