apiVersion: apps/v1
kind: Deployment
metadata:
  name: prescription-service-qa-deployment
  namespace: pbm-qa
  labels:
    app: prescription-service-qa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prescription-service-qa-deployment
  template:
    metadata:
      labels:
        app: prescription-service-qa-deployment
    spec:
      containers:
        - name: prescription-service-qa-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-qa/prescription-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: PBM_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: prescription-service-secrets
                key: PBM_OAUTH_CLIENT_ID
          - name: PBM_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: prescription-service-secrets
                key: PBM_OAUTH_CLIENT_SECRET
          - name: SSO_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: prescription-service-secrets
                key: SSO_CLIENT_ID
          - name: SSO_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: prescription-service-secrets
                key: SSO_CLIENT_SECRET
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
