--liquibase formatted sql

--changeset BR Service:0002


CREATE SEQUENCE "PBM_BUSINESS_RULES"."SENSITIVE_DRUG_SEQ"
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;


CREATE TABLE "PBM_BUSINESS_RULES"."SENSITIVE_DRUG_DETAILS"
(
	"SENSITIVE_DRUG_ID" NUMBER DEFAULT SENSITIVE_DRUG_SEQ.nextval NOT NULL,
    "WASEEL_DRUG_ID"  NUMBER NOT NULL,
    "REGISTRATION_NUMBER"  VARCHAR2(50) NOT NULL,
    "TRADE_NAME"  VARCHAR2(256) NOT NULL,
    "SCIENTIFIC_NAME"  VARCHAR2(256) NOT NULL,
    "SCIENTIFIC_CODE" VARCHAR2(150) NOT NULL,
    "PRICE" NUMBER NOT NULL,
	"LAST_UPDATE_DATE" DATE NOT NULL,
	"IS_DELETED" CHAR(1) DEFAULT ('0'),
	"DELETED_BY" VARCHAR2(30) DEFAULT NULL,
    CONSTRAINT PK_SensitiveDrug_SensitiveDrug PRIMARY KEY ("SENSITIVE_DRUG_ID")
);


