--liquibase formatted sql

--changeset BR Service:0004


CREATE SEQUENCE "PBM_BUSINESS_RULES"."BENEFIT_CODE_SEQ"
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;


CREATE TABLE "PBM_BUSINESS_RULES"."BENEFIT_CODES"
(
	"BENEFIT_CODE_ID" NUMBER DEFAULT BENEFIT_CODE_SEQ.nextval NOT NULL,
    "BENEFIT_CODE_NAME"  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_BENEFIT_CODES PRIMARY KEY ("BENEFIT_CODE_ID")
);


