--liquibase formatted sql

--changeset BR Service:0005

INSERT INTO PBM_BUSINESS_RULES.BENEFIT_CODES(BENEFIT_CODE_NAME) VALUES ('Pregnancy/Delivery and Miscarriage Benefit');
INSERT INTO PBM_BUSINESS_RULES.BENEFIT_CODES(BENEFIT_CODE_NAME) VALUES ('Basic Medical Benefit');
INSERT INTO PBM_BUSINESS_RULES.BENEFIT_CODES(BENEFIT_CODE_NAME) VALUES ('Dental Benefit');
INSERT INTO PBM_BUSINESS_RULES.BENEFIT_CODES(BENEFIT_CODE_NAME) VALUES ('Visual Aid Benefit (w/ Frames)');