--liquibase formatted sql

--changeset BR Service:0006


CREATE SEQUENCE "PBM_BUSINESS_RULES"."BENEFIT_PHYSC_SPEC_ASSC_SEQ"
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;


CREATE TABLE "PBM_BUSINESS_RULES"."BENEFIT_CODE_PHYSC_SPEC_ASSC"
(
	"BENEFIT_CODE_PHYSC_SPEC_ASSC_ID" NUMBER DEFAULT BENEFIT_PHYSC_SPEC_ASSC_SEQ.nextval NOT NULL,
	"PHYSICIAN_INFO_ID" NUMBER NOT NULL,
	"SPECIALITY_ID"  NUMBER NOT NULL,
    "BENEFIT_CODE_ID"  NUMBER NOT NULL,
    "IS_ENABLED" CHAR(1) DEFAULT ('1') NOT NULL,
    CONSTRAINT PK_BENEFIT_PHYSC_SPEC_ASSC PRIMARY KEY ("BENEFIT_CODE_PHYSC_SPEC_ASSC_ID"),
    CONSTRAINT "FK_PHYSICIAN_INFO_ID"
    	FOREIGN KEY ("PHYSICIAN_INFO_ID") REFERENCES PBM_BUSINESS_RULES."PhysicianInfo" ("PhysicianInfoId"),
    CONSTRAINT FK_SPECIALITY_ID
    	FOREIGN KEY (SPECIALITY_ID) REFERENCES PBM_BUSINESS_RULES.SPECIALITY (SPECIALITY_ID),
    CONSTRAINT FK_BENEFIT_CODE_ID
    	FOREIGN KEY (BENEFIT_CODE_ID) REFERENCES PBM_BUSINESS_RULES.BENEFIT_CODES (BENEFIT_CODE_ID)
);


