--liquibase formatted sql

--changeset BR Service:0009

ALTER TABLE BENEFIT_CODE_PHYSC_SPEC_ASSC DROP CONSTRAINT FK_PHYSICIAN_INFO_ID;

ALTER TABLE BENEFIT_CODE_PHYSC_SPEC_ASSC DROP COLUMN PHYSICIAN_INFO_ID;
