//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdmissionResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdmissionResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Admission" type="{http://www.waseel.com/wsdl/primary/wschema}AdmissionCT"/&gt;
 *         &lt;element name="AdmissionDecision" type="{http://www.waseel.com/wsdl/primary/wschema}AdmissionDecisionCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdmissionResponseCT", propOrder = {
    "admission",
    "admissionDecision"
})
public class AdmissionResponseCT {

    @XmlElement(name = "Admission", required = true)
    protected AdmissionCT admission;
    @XmlElement(name = "AdmissionDecision", required = true)
    protected AdmissionDecisionCT admissionDecision;

    /**
     * Gets the value of the admission property.
     * 
     * @return
     *     possible object is
     *     {@link AdmissionCT }
     *     
     */
    public AdmissionCT getAdmission() {
        return admission;
    }

    /**
     * Sets the value of the admission property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdmissionCT }
     *     
     */
    public void setAdmission(AdmissionCT value) {
        this.admission = value;
    }

    /**
     * Gets the value of the admissionDecision property.
     * 
     * @return
     *     possible object is
     *     {@link AdmissionDecisionCT }
     *     
     */
    public AdmissionDecisionCT getAdmissionDecision() {
        return admissionDecision;
    }

    /**
     * Sets the value of the admissionDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdmissionDecisionCT }
     *     
     */
    public void setAdmissionDecision(AdmissionDecisionCT value) {
        this.admissionDecision = value;
    }

}
