//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for AdmissionDecisionCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdmissionDecisionCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="roomType" type="{http://www.waseel.com/wsdl/primary/wschema}roomTypeST" minOccurs="0"/&gt;
 *         &lt;element name="approvedLengthOfStay" type="{http://www.w3.org/2001/XMLSchema}duration"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdmissionDecisionCT", propOrder = {
    "roomType",
    "approvedLengthOfStay"
})
public class AdmissionDecisionCT {

    @XmlSchemaType(name = "string")
    protected RoomTypeST roomType;
    @XmlElement(required = true)
    protected Duration approvedLengthOfStay;

    /**
     * Gets the value of the roomType property.
     * 
     * @return
     *     possible object is
     *     {@link RoomTypeST }
     *     
     */
    public RoomTypeST getRoomType() {
        return roomType;
    }

    /**
     * Sets the value of the roomType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoomTypeST }
     *     
     */
    public void setRoomType(RoomTypeST value) {
        this.roomType = value;
    }

    /**
     * Gets the value of the approvedLengthOfStay property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getApprovedLengthOfStay() {
        return approvedLengthOfStay;
    }

    /**
     * Sets the value of the approvedLengthOfStay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setApprovedLengthOfStay(Duration value) {
        this.approvedLengthOfStay = value;
    }

}
