//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApprovalInquiryResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApprovalInquiryResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="SummaryResponse" type="{http://www.waseel.com/wsdl/primary/wschema}ApprovalSummaryResponseCT"/&gt;
 *         &lt;element name="DetailResponse" type="{http://www.waseel.com/wsdl/primary/wschema}ApprovalDetailResponseCT"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApprovalInquiryResponseCT", propOrder = {
    "summaryResponse",
    "detailResponse"
})
public class ApprovalInquiryResponseCT {

    @XmlElement(name = "SummaryResponse")
    protected ApprovalSummaryResponseCT summaryResponse;
    @XmlElement(name = "DetailResponse")
    protected ApprovalDetailResponseCT detailResponse;

    /**
     * Gets the value of the summaryResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalSummaryResponseCT }
     *     
     */
    public ApprovalSummaryResponseCT getSummaryResponse() {
        return summaryResponse;
    }

    /**
     * Sets the value of the summaryResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalSummaryResponseCT }
     *     
     */
    public void setSummaryResponse(ApprovalSummaryResponseCT value) {
        this.summaryResponse = value;
    }

    /**
     * Gets the value of the detailResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalDetailResponseCT }
     *     
     */
    public ApprovalDetailResponseCT getDetailResponse() {
        return detailResponse;
    }

    /**
     * Sets the value of the detailResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalDetailResponseCT }
     *     
     */
    public void setDetailResponse(ApprovalDetailResponseCT value) {
        this.detailResponse = value;
    }

}
