//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BenefitCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BenefitCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="benefitCode" type="{http://www.waseel.com/wsdl/primary/wschema}benefitCodeST"/&gt;
 *         &lt;element name="benefitLimit" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="benefitDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="patientShare" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="maxPatientShare" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="maxConsultFee" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="approvalThreshold" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="approvalLimit" type="{http://www.waseel.com/wsdl/primary/wschema}approvalLimitST"/&gt;
 *         &lt;element name="CEC" type="{http://www.waseel.com/wsdl/primary/wschema}CECCT"/&gt;
 *         &lt;element name="Case" type="{http://www.waseel.com/wsdl/primary/wschema}CaseCT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="SubCoverage" type="{http://www.waseel.com/wsdl/primary/wschema}SubCoverageCT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BenefitCT", propOrder = {
    "benefitCode",
    "benefitLimit",
    "benefitDescription",
    "patientShare",
    "maxPatientShare",
    "maxConsultFee",
    "approvalThreshold",
    "approvalLimit",
    "cec",
    "_case",
    "subCoverage"
})
public class BenefitCT {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected BenefitCodeST benefitCode;
    protected AmountST benefitLimit;
    protected String benefitDescription;
    @XmlElement(required = true)
    protected AmountST patientShare;
    protected AmountST maxPatientShare;
    protected AmountST maxConsultFee;
    protected AmountST approvalThreshold;
    protected boolean approvalLimit;
    @XmlElement(name = "CEC", required = true)
    protected CECCT cec;
    @XmlElement(name = "Case")
    protected List<CaseCT> _case;
    @XmlElement(name = "SubCoverage")
    protected List<SubCoverageCT> subCoverage;

    /**
     * Gets the value of the benefitCode property.
     * 
     * @return
     *     possible object is
     *     {@link BenefitCodeST }
     *     
     */
    public BenefitCodeST getBenefitCode() {
        return benefitCode;
    }

    /**
     * Sets the value of the benefitCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenefitCodeST }
     *     
     */
    public void setBenefitCode(BenefitCodeST value) {
        this.benefitCode = value;
    }

    /**
     * Gets the value of the benefitLimit property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getBenefitLimit() {
        return benefitLimit;
    }

    /**
     * Sets the value of the benefitLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setBenefitLimit(AmountST value) {
        this.benefitLimit = value;
    }

    /**
     * Gets the value of the benefitDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenefitDescription() {
        return benefitDescription;
    }

    /**
     * Sets the value of the benefitDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenefitDescription(String value) {
        this.benefitDescription = value;
    }

    /**
     * Gets the value of the patientShare property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getPatientShare() {
        return patientShare;
    }

    /**
     * Sets the value of the patientShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setPatientShare(AmountST value) {
        this.patientShare = value;
    }

    /**
     * Gets the value of the maxPatientShare property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getMaxPatientShare() {
        return maxPatientShare;
    }

    /**
     * Sets the value of the maxPatientShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setMaxPatientShare(AmountST value) {
        this.maxPatientShare = value;
    }

    /**
     * Gets the value of the maxConsultFee property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getMaxConsultFee() {
        return maxConsultFee;
    }

    /**
     * Sets the value of the maxConsultFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setMaxConsultFee(AmountST value) {
        this.maxConsultFee = value;
    }

    /**
     * Gets the value of the approvalThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getApprovalThreshold() {
        return approvalThreshold;
    }

    /**
     * Sets the value of the approvalThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setApprovalThreshold(AmountST value) {
        this.approvalThreshold = value;
    }

    /**
     * Gets the value of the approvalLimit property.
     * 
     */
    public boolean isApprovalLimit() {
        return approvalLimit;
    }

    /**
     * Sets the value of the approvalLimit property.
     * 
     */
    public void setApprovalLimit(boolean value) {
        this.approvalLimit = value;
    }

    /**
     * Gets the value of the cec property.
     * 
     * @return
     *     possible object is
     *     {@link CECCT }
     *     
     */
    public CECCT getCEC() {
        return cec;
    }

    /**
     * Sets the value of the cec property.
     * 
     * @param value
     *     allowed object is
     *     {@link CECCT }
     *     
     */
    public void setCEC(CECCT value) {
        this.cec = value;
    }

    /**
     * Gets the value of the case property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the case property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCase().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CaseCT }
     * 
     * 
     */
    public List<CaseCT> getCase() {
        if (_case == null) {
            _case = new ArrayList<CaseCT>();
        }
        return this._case;
    }

    /**
     * Gets the value of the subCoverage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the subCoverage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubCoverage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubCoverageCT }
     * 
     * 
     */
    public List<SubCoverageCT> getSubCoverage() {
        if (subCoverage == null) {
            subCoverage = new ArrayList<SubCoverageCT>();
        }
        return this.subCoverage;
    }

}
