//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClaimCriteriaCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimCriteriaCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="providerBatchID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="payerBatchID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="providerClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="payerClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimCriteriaCT", propOrder = {
    "providerBatchID",
    "payerBatchID",
    "providerClaimNumber",
    "payerClaimNumber"
})
public class ClaimCriteriaCT {

    protected String providerBatchID;
    protected String payerBatchID;
    protected String providerClaimNumber;
    protected String payerClaimNumber;

    /**
     * Gets the value of the providerBatchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderBatchID() {
        return providerBatchID;
    }

    /**
     * Sets the value of the providerBatchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderBatchID(String value) {
        this.providerBatchID = value;
    }

    /**
     * Gets the value of the payerBatchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerBatchID() {
        return payerBatchID;
    }

    /**
     * Sets the value of the payerBatchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerBatchID(String value) {
        this.payerBatchID = value;
    }

    /**
     * Gets the value of the providerClaimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderClaimNumber() {
        return providerClaimNumber;
    }

    /**
     * Sets the value of the providerClaimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderClaimNumber(String value) {
        this.providerClaimNumber = value;
    }

    /**
     * Gets the value of the payerClaimNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayerClaimNumber() {
        return payerClaimNumber;
    }

    /**
     * Sets the value of the payerClaimNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayerClaimNumber(String value) {
        this.payerClaimNumber = value;
    }

}
