//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClaimInquiryRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClaimInquiryRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Criteria" type="{http://www.waseel.com/wsdl/primary/wschema}ClaimCriteriaCT"/&gt;
 *         &lt;element name="ClaimReference"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="providerClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="payerClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClaimInquiryRequestCT", propOrder = {
    "criteria",
    "claimReference"
})
public class ClaimInquiryRequestCT {

    @XmlElement(name = "Criteria")
    protected ClaimCriteriaCT criteria;
    @XmlElement(name = "ClaimReference")
    protected ClaimInquiryRequestCT.ClaimReference claimReference;

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimCriteriaCT }
     *     
     */
    public ClaimCriteriaCT getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimCriteriaCT }
     *     
     */
    public void setCriteria(ClaimCriteriaCT value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the claimReference property.
     * 
     * @return
     *     possible object is
     *     {@link ClaimInquiryRequestCT.ClaimReference }
     *     
     */
    public ClaimInquiryRequestCT.ClaimReference getClaimReference() {
        return claimReference;
    }

    /**
     * Sets the value of the claimReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClaimInquiryRequestCT.ClaimReference }
     *     
     */
    public void setClaimReference(ClaimInquiryRequestCT.ClaimReference value) {
        this.claimReference = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="providerClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="payerClaimNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "providerClaimNumber",
        "payerClaimNumber"
    })
    public static class ClaimReference {

        protected String providerClaimNumber;
        protected String payerClaimNumber;

        /**
         * Gets the value of the providerClaimNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProviderClaimNumber() {
            return providerClaimNumber;
        }

        /**
         * Sets the value of the providerClaimNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProviderClaimNumber(String value) {
            this.providerClaimNumber = value;
        }

        /**
         * Gets the value of the payerClaimNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPayerClaimNumber() {
            return payerClaimNumber;
        }

        /**
         * Sets the value of the payerClaimNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPayerClaimNumber(String value) {
            this.payerClaimNumber = value;
        }

    }

}
