//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispenseSubmissionResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispenseSubmissionResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestedData" type="{http://www.waseel.com/wsdl/primary/wschema}DispenseSubmissionRequestCT"/&gt;
 *         &lt;element name="DispenseServiceResponse" type="{http://www.waseel.com/wsdl/primary/wschema}DispenseServiceResponseCT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.waseel.com/wsdl/primary/wschema}StatusCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispenseSubmissionResponseCT", propOrder = {
    "requestedData",
    "dispenseServiceResponse",
    "status"
})
public class DispenseSubmissionResponseCT {

    @XmlElement(name = "RequestedData", required = true)
    protected DispenseSubmissionRequestCT requestedData;
    @XmlElement(name = "DispenseServiceResponse")
    protected List<DispenseServiceResponseCT> dispenseServiceResponse;
    @XmlElement(name = "Status", required = true)
    protected StatusCT status;

    /**
     * Gets the value of the requestedData property.
     * 
     * @return
     *     possible object is
     *     {@link DispenseSubmissionRequestCT }
     *     
     */
    public DispenseSubmissionRequestCT getRequestedData() {
        return requestedData;
    }

    /**
     * Sets the value of the requestedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispenseSubmissionRequestCT }
     *     
     */
    public void setRequestedData(DispenseSubmissionRequestCT value) {
        this.requestedData = value;
    }

    /**
     * Gets the value of the dispenseServiceResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispenseServiceResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispenseServiceResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DispenseServiceResponseCT }
     * 
     * 
     */
    public List<DispenseServiceResponseCT> getDispenseServiceResponse() {
        if (dispenseServiceResponse == null) {
            dispenseServiceResponse = new ArrayList<DispenseServiceResponseCT>();
        }
        return this.dispenseServiceResponse;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCT }
     *     
     */
    public StatusCT getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCT }
     *     
     */
    public void setStatus(StatusCT value) {
        this.status = value;
    }

}
