//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispenseInquiryResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispenseInquiryResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestedData"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ApprovalReference"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DispenseServiceResponse" type="{http://www.waseel.com/wsdl/primary/wschema}DispenseServiceResponseCT" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.waseel.com/wsdl/primary/wschema}StatusCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispenseInquiryResponseCT", propOrder = {
    "requestedData",
    "dispenseServiceResponse",
    "status"
})
public class DispenseInquiryResponseCT {

    @XmlElement(name = "RequestedData", required = true)
    protected DispenseInquiryResponseCT.RequestedData requestedData;
    @XmlElement(name = "DispenseServiceResponse")
    protected List<DispenseServiceResponseCT> dispenseServiceResponse;
    @XmlElement(name = "Status", required = true)
    protected StatusCT status;

    /**
     * Gets the value of the requestedData property.
     * 
     * @return
     *     possible object is
     *     {@link DispenseInquiryResponseCT.RequestedData }
     *     
     */
    public DispenseInquiryResponseCT.RequestedData getRequestedData() {
        return requestedData;
    }

    /**
     * Sets the value of the requestedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispenseInquiryResponseCT.RequestedData }
     *     
     */
    public void setRequestedData(DispenseInquiryResponseCT.RequestedData value) {
        this.requestedData = value;
    }

    /**
     * Gets the value of the dispenseServiceResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispenseServiceResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispenseServiceResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DispenseServiceResponseCT }
     * 
     * 
     */
    public List<DispenseServiceResponseCT> getDispenseServiceResponse() {
        if (dispenseServiceResponse == null) {
            dispenseServiceResponse = new ArrayList<DispenseServiceResponseCT>();
        }
        return this.dispenseServiceResponse;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCT }
     *     
     */
    public StatusCT getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCT }
     *     
     */
    public void setStatus(StatusCT value) {
        this.status = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ApprovalReference"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "approvalReference"
    })
    public static class RequestedData {

        @XmlElement(name = "ApprovalReference", required = true)
        protected DispenseInquiryResponseCT.RequestedData.ApprovalReference approvalReference;

        /**
         * Gets the value of the approvalReference property.
         * 
         * @return
         *     possible object is
         *     {@link DispenseInquiryResponseCT.RequestedData.ApprovalReference }
         *     
         */
        public DispenseInquiryResponseCT.RequestedData.ApprovalReference getApprovalReference() {
            return approvalReference;
        }

        /**
         * Sets the value of the approvalReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link DispenseInquiryResponseCT.RequestedData.ApprovalReference }
         *     
         */
        public void setApprovalReference(DispenseInquiryResponseCT.RequestedData.ApprovalReference value) {
            this.approvalReference = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "approvalNumber"
        })
        public static class ApprovalReference {

            @XmlElement(required = true)
            protected String approvalNumber;

            /**
             * Gets the value of the approvalNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApprovalNumber() {
                return approvalNumber;
            }

            /**
             * Sets the value of the approvalNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApprovalNumber(String value) {
                this.approvalNumber = value;
            }

        }

    }

}
