//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for DrugUseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DrugUseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dosage"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;decimal"&gt;
 *                 &lt;attribute name="unit" default="TAB"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="GM"/&gt;
 *                       &lt;enumeration value="MG"/&gt;
 *                       &lt;enumeration value="MCG"/&gt;
 *                       &lt;enumeration value="CC"/&gt;
 *                       &lt;enumeration value="ML"/&gt;
 *                       &lt;enumeration value="TSP"/&gt;
 *                       &lt;enumeration value="TBSP"/&gt;
 *                       &lt;enumeration value="GTT"/&gt;
 *                       &lt;enumeration value="TAB"/&gt;
 *                       &lt;enumeration value="CAP"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="doseTimes"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;integer"&gt;
 *                 &lt;attribute name="qualifier" default="QD"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="QD"/&gt;
 *                       &lt;enumeration value="QH"/&gt;
 *                       &lt;enumeration value="PC"/&gt;
 *                       &lt;enumeration value="AC"/&gt;
 *                       &lt;enumeration value="PRN"/&gt;
 *                       &lt;enumeration value="QOD"/&gt;
 *                       &lt;enumeration value="STAT"/&gt;
 *                       &lt;enumeration value="QHS"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="durationOfTreatment" type="{http://www.w3.org/2001/XMLSchema}duration"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DrugUseCT", propOrder = {
    "dosage",
    "doseTimes",
    "durationOfTreatment"
})
public class DrugUseCT {

    @XmlElement(required = true)
    protected DrugUseCT.Dosage dosage;
    @XmlElement(required = true)
    protected DrugUseCT.DoseTimes doseTimes;
    @XmlElement(required = true)
    protected Duration durationOfTreatment;

    /**
     * Gets the value of the dosage property.
     * 
     * @return
     *     possible object is
     *     {@link DrugUseCT.Dosage }
     *     
     */
    public DrugUseCT.Dosage getDosage() {
        return dosage;
    }

    /**
     * Sets the value of the dosage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugUseCT.Dosage }
     *     
     */
    public void setDosage(DrugUseCT.Dosage value) {
        this.dosage = value;
    }

    /**
     * Gets the value of the doseTimes property.
     * 
     * @return
     *     possible object is
     *     {@link DrugUseCT.DoseTimes }
     *     
     */
    public DrugUseCT.DoseTimes getDoseTimes() {
        return doseTimes;
    }

    /**
     * Sets the value of the doseTimes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DrugUseCT.DoseTimes }
     *     
     */
    public void setDoseTimes(DrugUseCT.DoseTimes value) {
        this.doseTimes = value;
    }

    /**
     * Gets the value of the durationOfTreatment property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDurationOfTreatment() {
        return durationOfTreatment;
    }

    /**
     * Sets the value of the durationOfTreatment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDurationOfTreatment(Duration value) {
        this.durationOfTreatment = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;decimal"&gt;
     *       &lt;attribute name="unit" default="TAB"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="GM"/&gt;
     *             &lt;enumeration value="MG"/&gt;
     *             &lt;enumeration value="MCG"/&gt;
     *             &lt;enumeration value="CC"/&gt;
     *             &lt;enumeration value="ML"/&gt;
     *             &lt;enumeration value="TSP"/&gt;
     *             &lt;enumeration value="TBSP"/&gt;
     *             &lt;enumeration value="GTT"/&gt;
     *             &lt;enumeration value="TAB"/&gt;
     *             &lt;enumeration value="CAP"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Dosage {

        @XmlValue
        protected BigDecimal value;
        @XmlAttribute(name = "unit")
        protected String unit;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValue(BigDecimal value) {
            this.value = value;
        }

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnit() {
            if (unit == null) {
                return "TAB";
            } else {
                return unit;
            }
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnit(String value) {
            this.unit = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;integer"&gt;
     *       &lt;attribute name="qualifier" default="QD"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="QD"/&gt;
     *             &lt;enumeration value="QH"/&gt;
     *             &lt;enumeration value="PC"/&gt;
     *             &lt;enumeration value="AC"/&gt;
     *             &lt;enumeration value="PRN"/&gt;
     *             &lt;enumeration value="QOD"/&gt;
     *             &lt;enumeration value="STAT"/&gt;
     *             &lt;enumeration value="QHS"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DoseTimes {

        @XmlValue
        protected BigInteger value;
        @XmlAttribute(name = "qualifier")
        protected String qualifier;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setValue(BigInteger value) {
            this.value = value;
        }

        /**
         * Gets the value of the qualifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQualifier() {
            if (qualifier == null) {
                return "QD";
            } else {
                return qualifier;
            }
        }

        /**
         * Sets the value of the qualifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQualifier(String value) {
            this.qualifier = value;
        }

    }

}
