//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EditingCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EditingCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="canFollowUp" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="canCancel" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditingCT", propOrder = {
    "canFollowUp",
    "canCancel"
})
public class EditingCT {

    protected boolean canFollowUp;
    protected boolean canCancel;

    /**
     * Gets the value of the canFollowUp property.
     * 
     */
    public boolean isCanFollowUp() {
        return canFollowUp;
    }

    /**
     * Sets the value of the canFollowUp property.
     * 
     */
    public void setCanFollowUp(boolean value) {
        this.canFollowUp = value;
    }

    /**
     * Gets the value of the canCancel property.
     * 
     */
    public boolean isCanCancel() {
        return canCancel;
    }

    /**
     * Sets the value of the canCancel property.
     * 
     */
    public void setCanCancel(boolean value) {
        this.canCancel = value;
    }

}
