//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GDPNCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GDPNCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="net" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="netVATrate" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="netVATamount" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="patientShare" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="patientShareVATrate" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="patientShareVATamount" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="discount" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="gross" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="priceCorrection" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="rejection" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GDPNCT", propOrder = {
    "net",
    "netVATrate",
    "netVATamount",
    "patientShare",
    "patientShareVATrate",
    "patientShareVATamount",
    "discount",
    "gross",
    "priceCorrection",
    "rejection"
})
public class GDPNCT {

    @XmlElement(required = true)
    protected AmountST net;
    @XmlElement(required = true)
    protected AmountST netVATrate;
    @XmlElement(required = true)
    protected AmountST netVATamount;
    @XmlElement(required = true)
    protected AmountST patientShare;
    @XmlElement(required = true)
    protected AmountST patientShareVATrate;
    @XmlElement(required = true)
    protected AmountST patientShareVATamount;
    @XmlElement(required = true)
    protected AmountST discount;
    @XmlElement(required = true)
    protected AmountST gross;
    protected AmountST priceCorrection;
    protected AmountST rejection;

    /**
     * Gets the value of the net property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getNet() {
        return net;
    }

    /**
     * Sets the value of the net property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setNet(AmountST value) {
        this.net = value;
    }

    /**
     * Gets the value of the netVATrate property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getNetVATrate() {
        return netVATrate;
    }

    /**
     * Sets the value of the netVATrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setNetVATrate(AmountST value) {
        this.netVATrate = value;
    }

    /**
     * Gets the value of the netVATamount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getNetVATamount() {
        return netVATamount;
    }

    /**
     * Sets the value of the netVATamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setNetVATamount(AmountST value) {
        this.netVATamount = value;
    }

    /**
     * Gets the value of the patientShare property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getPatientShare() {
        return patientShare;
    }

    /**
     * Sets the value of the patientShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setPatientShare(AmountST value) {
        this.patientShare = value;
    }

    /**
     * Gets the value of the patientShareVATrate property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getPatientShareVATrate() {
        return patientShareVATrate;
    }

    /**
     * Sets the value of the patientShareVATrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setPatientShareVATrate(AmountST value) {
        this.patientShareVATrate = value;
    }

    /**
     * Gets the value of the patientShareVATamount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getPatientShareVATamount() {
        return patientShareVATamount;
    }

    /**
     * Sets the value of the patientShareVATamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setPatientShareVATamount(AmountST value) {
        this.patientShareVATamount = value;
    }

    /**
     * Gets the value of the discount property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getDiscount() {
        return discount;
    }

    /**
     * Sets the value of the discount property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setDiscount(AmountST value) {
        this.discount = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setGross(AmountST value) {
        this.gross = value;
    }

    /**
     * Gets the value of the priceCorrection property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getPriceCorrection() {
        return priceCorrection;
    }

    /**
     * Sets the value of the priceCorrection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setPriceCorrection(AmountST value) {
        this.priceCorrection = value;
    }

    /**
     * Gets the value of the rejection property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getRejection() {
        return rejection;
    }

    /**
     * Sets the value of the rejection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setRejection(AmountST value) {
        this.rejection = value;
    }

}
