//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for IntimationResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntimationResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="IntimationType" type="{http://www.waseel.com/wsdl/primary/wschema}intimationTypeST"/&gt;
 *         &lt;element name="PolicyNumber" type="{http://www.waseel.com/wsdl/primary/wschema}policyNumberST" minOccurs="0"/&gt;
 *         &lt;element name="planNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="lossMonth" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="CaseType" type="{http://www.waseel.com/wsdl/primary/wschema}caseTypeST" minOccurs="0"/&gt;
 *         &lt;element name="gross" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="net" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Status" type="{http://www.waseel.com/wsdl/primary/wschema}StatusCT"/&gt;
 *         &lt;element name="additionalInfo" type="{http://www.waseel.com/wsdl/primary/wschema}additionalInfoST"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntimationResponseCT", propOrder = {
    "intimationType",
    "policyNumber",
    "planNumber",
    "lossMonth",
    "caseType",
    "gross",
    "net",
    "batchReference",
    "status",
    "additionalInfo"
})
public class IntimationResponseCT {

    @XmlElement(name = "IntimationType", required = true)
    @XmlSchemaType(name = "string")
    protected IntimationTypeST intimationType;
    @XmlElement(name = "PolicyNumber")
    protected String policyNumber;
    protected String planNumber;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lossMonth;
    @XmlElement(name = "CaseType")
    @XmlSchemaType(name = "string")
    protected CaseTypeST caseType;
    @XmlElement(required = true)
    protected AmountST gross;
    @XmlElement(required = true)
    protected AmountST net;
    protected String batchReference;
    @XmlElement(name = "Status", required = true)
    protected StatusCT status;
    @XmlElement(required = true)
    protected String additionalInfo;

    /**
     * Gets the value of the intimationType property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationTypeST }
     *     
     */
    public IntimationTypeST getIntimationType() {
        return intimationType;
    }

    /**
     * Sets the value of the intimationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationTypeST }
     *     
     */
    public void setIntimationType(IntimationTypeST value) {
        this.intimationType = value;
    }

    /**
     * Gets the value of the policyNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPolicyNumber() {
        return policyNumber;
    }

    /**
     * Sets the value of the policyNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPolicyNumber(String value) {
        this.policyNumber = value;
    }

    /**
     * Gets the value of the planNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanNumber() {
        return planNumber;
    }

    /**
     * Sets the value of the planNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanNumber(String value) {
        this.planNumber = value;
    }

    /**
     * Gets the value of the lossMonth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLossMonth() {
        return lossMonth;
    }

    /**
     * Sets the value of the lossMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLossMonth(XMLGregorianCalendar value) {
        this.lossMonth = value;
    }

    /**
     * Gets the value of the caseType property.
     * 
     * @return
     *     possible object is
     *     {@link CaseTypeST }
     *     
     */
    public CaseTypeST getCaseType() {
        return caseType;
    }

    /**
     * Sets the value of the caseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseTypeST }
     *     
     */
    public void setCaseType(CaseTypeST value) {
        this.caseType = value;
    }

    /**
     * Gets the value of the gross property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getGross() {
        return gross;
    }

    /**
     * Sets the value of the gross property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setGross(AmountST value) {
        this.gross = value;
    }

    /**
     * Gets the value of the net property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getNet() {
        return net;
    }

    /**
     * Sets the value of the net property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setNet(AmountST value) {
        this.net = value;
    }

    /**
     * Gets the value of the batchReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchReference() {
        return batchReference;
    }

    /**
     * Sets the value of the batchReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchReference(String value) {
        this.batchReference = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCT }
     *     
     */
    public StatusCT getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCT }
     *     
     */
    public void setStatus(StatusCT value) {
        this.status = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

}
