//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for intimationTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="intimationTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="POLICY"/&gt;
 *     &lt;enumeration value="PLAN"/&gt;
 *     &lt;enumeration value="REFERRAL"/&gt;
 *     &lt;enumeration value="GROUP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "intimationTypeST")
@XmlEnum
public enum IntimationTypeST {

    POLICY,
    PLAN,
    REFERRAL,
    GROUP;

    public String value() {
        return name();
    }

    public static IntimationTypeST fromValue(String v) {
        return valueOf(v);
    }

}
