//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="InvoiceDecision" type="{http://www.waseel.com/wsdl/primary/wschema}InvoiceDecisionCT"/&gt;
 *         &lt;element name="ServiceResponse" type="{http://www.waseel.com/wsdl/primary/wschema}ServiceResponseCT" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceResponseCT", propOrder = {
    "invoiceDecision",
    "serviceResponse"
})
public class InvoiceResponseCT {

    @XmlElement(name = "InvoiceDecision", required = true)
    protected InvoiceDecisionCT invoiceDecision;
    @XmlElement(name = "ServiceResponse", required = true)
    protected List<ServiceResponseCT> serviceResponse;

    /**
     * Gets the value of the invoiceDecision property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceDecisionCT }
     *     
     */
    public InvoiceDecisionCT getInvoiceDecision() {
        return invoiceDecision;
    }

    /**
     * Sets the value of the invoiceDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceDecisionCT }
     *     
     */
    public void setInvoiceDecision(InvoiceDecisionCT value) {
        this.invoiceDecision = value;
    }

    /**
     * Gets the value of the serviceResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceResponseCT }
     * 
     * 
     */
    public List<ServiceResponseCT> getServiceResponse() {
        if (serviceResponse == null) {
            serviceResponse = new ArrayList<ServiceResponseCT>();
        }
        return this.serviceResponse;
    }

}
