//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InvoiceDecisionCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InvoiceDecisionCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="invoiceNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="InvoiceGDPN" type="{http://www.waseel.com/wsdl/primary/wschema}GDPNCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InvoiceDecisionCT", propOrder = {
    "invoiceNumber",
    "invoiceGDPN"
})
public class InvoiceDecisionCT {

    @XmlElement(required = true)
    protected String invoiceNumber;
    @XmlElement(name = "InvoiceGDPN", required = true)
    protected GDPNCT invoiceGDPN;

    /**
     * Gets the value of the invoiceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInvoiceNumber(String value) {
        this.invoiceNumber = value;
    }

    /**
     * Gets the value of the invoiceGDPN property.
     * 
     * @return
     *     possible object is
     *     {@link GDPNCT }
     *     
     */
    public GDPNCT getInvoiceGDPN() {
        return invoiceGDPN;
    }

    /**
     * Sets the value of the invoiceGDPN property.
     * 
     * @param value
     *     allowed object is
     *     {@link GDPNCT }
     *     
     */
    public void setInvoiceGDPN(GDPNCT value) {
        this.invoiceGDPN = value;
    }

}
