//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.math.BigDecimal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for opticalReadingST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="opticalReadingST"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;decimal"&gt;
 *       &lt;attribute name="geometry" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.waseel.com/wsdl/primary/wschema}geometryST"&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="side" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.waseel.com/wsdl/primary/wschema}sideST"&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="focus" use="required"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.waseel.com/wsdl/primary/wschema}focusST"&gt;
 *             &lt;enumeration value="NEAR"/&gt;
 *             &lt;enumeration value="DISTANCE"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "opticalReadingST", propOrder = {
    "value"
})
@XmlSeeAlso({
    CaseInfoCT.CaseDescription.Optics.Reading.class
})
public class OpticalReadingST {

    @XmlValue
    protected BigDecimal value;
    @XmlAttribute(name = "geometry", required = true)
    protected GeometryST geometry;
    @XmlAttribute(name = "side", required = true)
    protected SideST side;
    @XmlAttribute(name = "focus", required = true)
    protected FocusST focus;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * Gets the value of the geometry property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryST }
     *     
     */
    public GeometryST getGeometry() {
        return geometry;
    }

    /**
     * Sets the value of the geometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryST }
     *     
     */
    public void setGeometry(GeometryST value) {
        this.geometry = value;
    }

    /**
     * Gets the value of the side property.
     * 
     * @return
     *     possible object is
     *     {@link SideST }
     *     
     */
    public SideST getSide() {
        return side;
    }

    /**
     * Sets the value of the side property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideST }
     *     
     */
    public void setSide(SideST value) {
        this.side = value;
    }

    /**
     * Gets the value of the focus property.
     * 
     * @return
     *     possible object is
     *     {@link FocusST }
     *     
     */
    public FocusST getFocus() {
        return focus;
    }

    /**
     * Sets the value of the focus property.
     * 
     * @param value
     *     allowed object is
     *     {@link FocusST }
     *     
     */
    public void setFocus(FocusST value) {
        this.focus = value;
    }

}
