//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhysicianCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PhysicianCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="physicianName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="physicianID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="physicianCategory" type="{http://www.waseel.com/wsdl/primary/wschema}physicianCategoryST"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PhysicianCT", propOrder = {
    "physicianName",
    "physicianID",
    "physicianCategory"
})
public class PhysicianCT {

    @XmlElement(required = true)
    protected String physicianName;
    @XmlElement(required = true)
    protected String physicianID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PhysicianCategoryST physicianCategory;

    /**
     * Gets the value of the physicianName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianName() {
        return physicianName;
    }

    /**
     * Sets the value of the physicianName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianName(String value) {
        this.physicianName = value;
    }

    /**
     * Gets the value of the physicianID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhysicianID() {
        return physicianID;
    }

    /**
     * Sets the value of the physicianID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhysicianID(String value) {
        this.physicianID = value;
    }

    /**
     * Gets the value of the physicianCategory property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicianCategoryST }
     *     
     */
    public PhysicianCategoryST getPhysicianCategory() {
        return physicianCategory;
    }

    /**
     * Sets the value of the physicianCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicianCategoryST }
     *     
     */
    public void setPhysicianCategory(PhysicianCategoryST value) {
        this.physicianCategory = value;
    }

}
