//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PolicyInquiryRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PolicyInquiryRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Criteria" type="{http://www.waseel.com/wsdl/primary/wschema}PolicyInquiryCriteriaCT"/&gt;
 *         &lt;element name="PolicyReference" type="{http://www.waseel.com/wsdl/primary/wschema}PolicyReferenceCT"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PolicyInquiryRequestCT", propOrder = {
    "criteria",
    "policyReference"
})
public class PolicyInquiryRequestCT {

    @XmlElement(name = "Criteria")
    protected PolicyInquiryCriteriaCT criteria;
    @XmlElement(name = "PolicyReference")
    protected PolicyReferenceCT policyReference;

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyInquiryCriteriaCT }
     *     
     */
    public PolicyInquiryCriteriaCT getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyInquiryCriteriaCT }
     *     
     */
    public void setCriteria(PolicyInquiryCriteriaCT value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the policyReference property.
     * 
     * @return
     *     possible object is
     *     {@link PolicyReferenceCT }
     *     
     */
    public PolicyReferenceCT getPolicyReference() {
        return policyReference;
    }

    /**
     * Sets the value of the policyReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolicyReferenceCT }
     *     
     */
    public void setPolicyReference(PolicyReferenceCT value) {
        this.policyReference = value;
    }

}
