//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for roomTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="roomTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SHARED ROOM"/&gt;
 *     &lt;enumeration value="PRIVATE"/&gt;
 *     &lt;enumeration value="SUITE"/&gt;
 *     &lt;enumeration value="Royal Suite Room"/&gt;
 *     &lt;enumeration value="Delux Suite"/&gt;
 *     &lt;enumeration value="Normal Suite"/&gt;
 *     &lt;enumeration value="Semi-Suite Room"/&gt;
 *     &lt;enumeration value="Private Room"/&gt;
 *     &lt;enumeration value="Delux Room"/&gt;
 *     &lt;enumeration value="First Class Room"/&gt;
 *     &lt;enumeration value="Special Room"/&gt;
 *     &lt;enumeration value="Semi-Private Room"/&gt;
 *     &lt;enumeration value="Shared Room"/&gt;
 *     &lt;enumeration value="Second Class Room"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "roomTypeST")
@XmlEnum
public enum RoomTypeST {

    @XmlEnumValue("SHARED ROOM")
    VALUE_1("SHARED ROOM"),
    @XmlEnumValue("PRIVATE")
    VALUE_2("PRIVATE"),
    @XmlEnumValue("SUITE")
    VALUE_3("SUITE"),
    @XmlEnumValue("Royal Suite Room")
    VALUE_4("Royal Suite Room"),
    @XmlEnumValue("Delux Suite")
    VALUE_5("Delux Suite"),
    @XmlEnumValue("Normal Suite")
    VALUE_6("Normal Suite"),
    @XmlEnumValue("Semi-Suite Room")
    VALUE_7("Semi-Suite Room"),
    @XmlEnumValue("Private Room")
    VALUE_8("Private Room"),
    @XmlEnumValue("Delux Room")
    VALUE_9("Delux Room"),
    @XmlEnumValue("First Class Room")
    VALUE_10("First Class Room"),
    @XmlEnumValue("Special Room")
    VALUE_11("Special Room"),
    @XmlEnumValue("Semi-Private Room")
    VALUE_12("Semi-Private Room"),
    @XmlEnumValue("Shared Room")
    VALUE_13("Shared Room"),
    @XmlEnumValue("Second Class Room")
    VALUE_14("Second Class Room");
    private final String value;

    RoomTypeST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RoomTypeST fromValue(String v) {
        for (RoomTypeST c: RoomTypeST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
