//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="serviceTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="N/A"/&gt;
 *     &lt;enumeration value="LABORATORY"/&gt;
 *     &lt;enumeration value="MEDICATION"/&gt;
 *     &lt;enumeration value="RADIOLOGY"/&gt;
 *     &lt;enumeration value="CONSULTATION"/&gt;
 *     &lt;enumeration value="PROCEDURE"/&gt;
 *     &lt;enumeration value="HOSPITLIZATION"/&gt;
 *     &lt;enumeration value="DENTAL"/&gt;
 *     &lt;enumeration value="SUPPLY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "serviceTypeST")
@XmlEnum
public enum ServiceTypeST {

    @XmlEnumValue("N/A")
    N_A("N/A"),
    LABORATORY("LABORATORY"),
    MEDICATION("MEDICATION"),
    RADIOLOGY("RADIOLOGY"),
    CONSULTATION("CONSULTATION"),
    PROCEDURE("PROCEDURE"),
    HOSPITLIZATION("HOSPITLIZATION"),
    DENTAL("DENTAL"),
    SUPPLY("SUPPLY");
    private final String value;

    ServiceTypeST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ServiceTypeST fromValue(String v) {
        for (ServiceTypeST c: ServiceTypeST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
