//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ServiceResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ServiceResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Service" type="{http://www.waseel.com/wsdl/primary/wschema}ServiceCT"/&gt;
 *         &lt;element name="ServiceDecision" type="{http://www.waseel.com/wsdl/primary/wschema}ServiceDecisionCT" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ServiceResponseCT", propOrder = {
    "service",
    "serviceDecision"
})
public class ServiceResponseCT {

    @XmlElement(name = "Service", required = true)
    protected ServiceCT service;
    @XmlElement(name = "ServiceDecision")
    protected ServiceDecisionCT serviceDecision;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCT }
     *     
     */
    public ServiceCT getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCT }
     *     
     */
    public void setService(ServiceCT value) {
        this.service = value;
    }

    /**
     * Gets the value of the serviceDecision property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceDecisionCT }
     *     
     */
    public ServiceDecisionCT getServiceDecision() {
        return serviceDecision;
    }

    /**
     * Sets the value of the serviceDecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceDecisionCT }
     *     
     */
    public void setServiceDecision(ServiceDecisionCT value) {
        this.serviceDecision = value;
    }

}
