//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for toothNumberST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="toothNumberST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="0"/&gt;
 *     &lt;enumeration value="1"/&gt;
 *     &lt;enumeration value="2"/&gt;
 *     &lt;enumeration value="3"/&gt;
 *     &lt;enumeration value="4"/&gt;
 *     &lt;enumeration value="5"/&gt;
 *     &lt;enumeration value="6"/&gt;
 *     &lt;enumeration value="7"/&gt;
 *     &lt;enumeration value="8"/&gt;
 *     &lt;enumeration value="9"/&gt;
 *     &lt;enumeration value="10"/&gt;
 *     &lt;enumeration value="11"/&gt;
 *     &lt;enumeration value="12"/&gt;
 *     &lt;enumeration value="13"/&gt;
 *     &lt;enumeration value="14"/&gt;
 *     &lt;enumeration value="15"/&gt;
 *     &lt;enumeration value="16"/&gt;
 *     &lt;enumeration value="17"/&gt;
 *     &lt;enumeration value="18"/&gt;
 *     &lt;enumeration value="19"/&gt;
 *     &lt;enumeration value="20"/&gt;
 *     &lt;enumeration value="21"/&gt;
 *     &lt;enumeration value="22"/&gt;
 *     &lt;enumeration value="23"/&gt;
 *     &lt;enumeration value="24"/&gt;
 *     &lt;enumeration value="25"/&gt;
 *     &lt;enumeration value="26"/&gt;
 *     &lt;enumeration value="27"/&gt;
 *     &lt;enumeration value="28"/&gt;
 *     &lt;enumeration value="29"/&gt;
 *     &lt;enumeration value="30"/&gt;
 *     &lt;enumeration value="31"/&gt;
 *     &lt;enumeration value="32"/&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="B"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="G"/&gt;
 *     &lt;enumeration value="H"/&gt;
 *     &lt;enumeration value="I"/&gt;
 *     &lt;enumeration value="J"/&gt;
 *     &lt;enumeration value="K"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="M"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="O"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="Q"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="S"/&gt;
 *     &lt;enumeration value="T"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "toothNumberST")
@XmlEnum
public enum ToothNumberST {

	@XmlEnumValue("0")
	VALUE_1("0"), @XmlEnumValue("1")
	VALUE_2("1"), @XmlEnumValue("2")
	VALUE_3("2"), @XmlEnumValue("3")
	VALUE_4("3"), @XmlEnumValue("4")
	VALUE_5("4"), @XmlEnumValue("5")
	VALUE_6("5"), @XmlEnumValue("6")
	VALUE_7("6"), @XmlEnumValue("7")
	VALUE_8("7"), @XmlEnumValue("8")
	VALUE_9("8"), @XmlEnumValue("9")
	VALUE_10("9"), @XmlEnumValue("10")
	VALUE_11("10"), @XmlEnumValue("11")
	VALUE_12("11"), @XmlEnumValue("12")
	VALUE_13("12"), @XmlEnumValue("13")
	VALUE_14("13"), @XmlEnumValue("14")
	VALUE_15("14"), @XmlEnumValue("15")
	VALUE_16("15"), @XmlEnumValue("16")
	VALUE_17("16"), @XmlEnumValue("17")
	VALUE_18("17"), @XmlEnumValue("18")
	VALUE_19("18"), @XmlEnumValue("19")
	VALUE_20("19"), @XmlEnumValue("20")
	VALUE_21("20"), @XmlEnumValue("21")
	VALUE_22("21"), @XmlEnumValue("22")
	VALUE_23("22"), @XmlEnumValue("23")
	VALUE_24("23"), @XmlEnumValue("24")
	VALUE_25("24"), @XmlEnumValue("25")
	VALUE_26("25"), @XmlEnumValue("26")
	VALUE_27("26"), @XmlEnumValue("27")
	VALUE_28("27"), @XmlEnumValue("28")
	VALUE_29("28"), @XmlEnumValue("29")
	VALUE_30("29"), @XmlEnumValue("30")
	VALUE_31("30"), @XmlEnumValue("31")
	VALUE_32("31"), @XmlEnumValue("32")
	VALUE_33("32"), @XmlEnumValue("33")
	VALUE_34("33"), @XmlEnumValue("34")
	VALUE_35("34"), @XmlEnumValue("35")
	VALUE_36("35"), @XmlEnumValue("36")
	VALUE_37("36"), @XmlEnumValue("37")
	VALUE_38("37"), @XmlEnumValue("38")
	VALUE_39("38"), @XmlEnumValue("39")
	VALUE_40("39"), @XmlEnumValue("40")
	VALUE_41("40"), @XmlEnumValue("41")
	VALUE_42("41"), @XmlEnumValue("42")
	VALUE_43("42"), @XmlEnumValue("43")
	VALUE_44("43"), @XmlEnumValue("44")
	VALUE_45("44"), @XmlEnumValue("45")
	VALUE_46("45"), @XmlEnumValue("46")
	VALUE_47("46"), @XmlEnumValue("47")
	VALUE_48("47"), @XmlEnumValue("48")
	VALUE_49("48"), @XmlEnumValue("49")
	VALUE_50("49"), @XmlEnumValue("50")
	VALUE_51("50"), @XmlEnumValue("51")
	VALUE_52("51"), @XmlEnumValue("52")
	VALUE_53("52"), @XmlEnumValue("53")
	VALUE_54("53"), @XmlEnumValue("54")
	VALUE_55("54"), @XmlEnumValue("55")
	VALUE_56("55"), @XmlEnumValue("56")
	VALUE_57("56"), @XmlEnumValue("57")
	VALUE_58("57"), @XmlEnumValue("58")
	VALUE_59("58"), @XmlEnumValue("59")
	VALUE_60("59"), @XmlEnumValue("60")
	VALUE_61("60"), @XmlEnumValue("61")
	VALUE_62("61"), @XmlEnumValue("62")
	VALUE_63("62"), @XmlEnumValue("63")
	VALUE_64("63"), @XmlEnumValue("64")
	VALUE_65("64"), @XmlEnumValue("65")
	VALUE_66("65"), @XmlEnumValue("66")
	VALUE_67("66"), @XmlEnumValue("67")
	VALUE_68("67"), @XmlEnumValue("68")
	VALUE_69("68"), @XmlEnumValue("69")
	VALUE_70("69"), @XmlEnumValue("70")
	VALUE_71("70"), @XmlEnumValue("71")
	VALUE_72("71"), @XmlEnumValue("72")
	VALUE_73("72"), @XmlEnumValue("73")
	VALUE_74("73"), @XmlEnumValue("74")
	VALUE_75("74"), @XmlEnumValue("75")
	VALUE_76("75"), @XmlEnumValue("76")
	VALUE_77("76"), @XmlEnumValue("77")
	VALUE_78("77"), @XmlEnumValue("78")
	VALUE_79("78"), @XmlEnumValue("79")
	VALUE_80("79"), @XmlEnumValue("80")
	VALUE_81("80"), @XmlEnumValue("81")
	VALUE_82("81"), @XmlEnumValue("82")
	VALUE_83("82"), @XmlEnumValue("83")
	VALUE_84("83"), @XmlEnumValue("84")
	VALUE_85("84"), @XmlEnumValue("85")
	VALUE_86("85"), @XmlEnumValue("A")
	VALUE_87("A"), @XmlEnumValue("B")
	VALUE_88("B"), @XmlEnumValue("C")
	VALUE_89("C"), @XmlEnumValue("D")
	VALUE_90("D"), @XmlEnumValue("E")
	VALUE_91("E"), @XmlEnumValue("F")
	VALUE_92("F"), @XmlEnumValue("G")
	VALUE_93("G"), @XmlEnumValue("H")
	VALUE_94("H"), @XmlEnumValue("I")
	VALUE_95("I"), @XmlEnumValue("J")
	VALUE_96("J"), @XmlEnumValue("K")
	VALUE_97("K"), @XmlEnumValue("L")
	VALUE_98("L"), @XmlEnumValue("M")
	VALUE_99("M"), @XmlEnumValue("N")
	VALUE_100("N"), @XmlEnumValue("O")
	VALUE_101("O"), @XmlEnumValue("P")
	VALUE_102("P"), @XmlEnumValue("Q")
	VALUE_103("Q"), @XmlEnumValue("R")
	VALUE_104("R"), @XmlEnumValue("S")
	VALUE_105("S"), @XmlEnumValue("T")
	VALUE_106("T");
	private final String value;

    ToothNumberST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ToothNumberST fromValue(String v) {
    	if(v == null) {
    		return null;
    	}
        for (ToothNumberST c: ToothNumberST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
