//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transactionSubTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="transactionSubTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NEW"/&gt;
 *     &lt;enumeration value="FOLLOWUP"/&gt;
 *     &lt;enumeration value="CANCELLATION"/&gt;
 *     &lt;enumeration value="SUMMARY"/&gt;
 *     &lt;enumeration value="DETAIL"/&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "transactionSubTypeST")
@XmlEnum
public enum TransactionSubTypeST {

    NEW,
    FOLLOWUP,
    CANCELLATION,
    SUMMARY,
    DETAIL,
    NONE;

    public String value() {
        return name();
    }

    public static TransactionSubTypeST fromValue(String v) {
        return valueOf(v);
    }

}
