//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transactionTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="transactionTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="1.1"/&gt;
 *     &lt;enumeration value="2.1"/&gt;
 *     &lt;enumeration value="2.2"/&gt;
 *     &lt;enumeration value="2.3"/&gt;
 *     &lt;enumeration value="3.1"/&gt;
 *     &lt;enumeration value="3.2"/&gt;
 *     &lt;enumeration value="3.3"/&gt;
 *     &lt;enumeration value="3.4"/&gt;
 *     &lt;enumeration value="3.5"/&gt;
 *     &lt;enumeration value="4.2"/&gt;
 *     &lt;enumeration value="4.3"/&gt;
 *     &lt;enumeration value="5.1"/&gt;
 *     &lt;enumeration value="5.2"/&gt;
 *     &lt;enumeration value="6.1"/&gt;
 *     &lt;enumeration value="6.2"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "transactionTypeST")
@XmlEnum
public enum TransactionTypeST {

    @XmlEnumValue("1.1")
    VALUE_1("1.1"),
    @XmlEnumValue("2.1")
    VALUE_2("2.1"),
    @XmlEnumValue("2.2")
    VALUE_3("2.2"),
    @XmlEnumValue("2.3")
    VALUE_4("2.3"),
    @XmlEnumValue("3.1")
    VALUE_5("3.1"),
    @XmlEnumValue("3.2")
    VALUE_6("3.2"),
    @XmlEnumValue("3.3")
    VALUE_7("3.3"),
    @XmlEnumValue("3.4")
    VALUE_8("3.4"),
    @XmlEnumValue("3.5")
    VALUE_9("3.5"),
    @XmlEnumValue("4.2")
    VALUE_10("4.2"),
    @XmlEnumValue("4.3")
    VALUE_11("4.3"),
    @XmlEnumValue("5.1")
    VALUE_12("5.1"),
    @XmlEnumValue("5.2")
    VALUE_13("5.2"),
    @XmlEnumValue("6.1")
    VALUE_14("6.1"),
    @XmlEnumValue("6.2")
    VALUE_15("6.2");
    private final String value;

    TransactionTypeST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransactionTypeST fromValue(String v) {
        for (TransactionTypeST c: TransactionTypeST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
