--liquibase formatted sql

--changeset Payer-Customization-Service:005

CREATE TABLE "MDSS"."PayerCustomizationModules"
(
   "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
   "RuleId" VARCHAR2 (20),
   "Description" VARCHAR2 (100),
   CONSTRAINT PK_Id PRIMARY KEY ("Id")
);