--liquibase formatted sql

--changeset Payer-Customization-Service:032

CREATE TABLE "MDSS"."CustomizationBatch"
(
    "Id" NUMBER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,
    "BatchReference" VARCHAR2(150),
	"CreatedDate" DATE,
	"Uploader" VARCHAR2(150),
	CONSTRAINT PK_BatchId PRIMARY KEY ("Id")
);