--liquibase formatted sql

--changeset Payer-Customization-Service:047

CREATE TABLE MDSS.CUSTOMIZATION_REQUESTS
(
    CUSTOMIZATION_REQUESTS_ID  NUMBER NOT NULL,
    REQUEST_ID VARCHAR2(100) NOT NULL,
	PAYER_ID VARCHAR2(20) NOT NULL,
	STATUS VARCHAR2(10) DEFAULT('Pending') NOT NULL,
	MODULE_NAME VARCHAR2(200) NOT NULL,
	DRUG_CODE VARCHAR2(250) NOT NULL,
	ICD_CODE  VARCHAR2(20),
	REJECTION_CATEGORY  VARCHAR2(100),
	LAST_UPDATED_DATE DATE NOT NULL,
	IS_DELETED CHAR(1) DEFAULT('0') NOT NULL,
	INTERACTED_DRUG_CODE VARCHAR2(250),
	GENDER  VARCHAR2(20),
	FROM_AGE_IN_DAYS NUMBER,
	TO_AGE_IN_DAYS NUMBER,
	DRUG_TYPE VARCHAR2(20),
	MAX_VALUE_PER_DAY NUMBER, 
	UNIT_TYPE VARCHAR2(10),
	PRODUCT_PACKAGE_SIZE NUMBER,
	REJECTION_REASON  VARCHAR2(4000),
	CONSTRAINT PK_CUSTOMIZATION_REQUESTS_ID PRIMARY KEY (CUSTOMIZATION_REQUESTS_ID)
);

CREATE SEQUENCE MDSS.PC_CUSTOMIZATION_REQUESTS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;