--liquibase formatted sql

--changeset Payer-Customization-Service:050

CREATE TABLE MDSS.CUSTOMIZATION_REQUEST_METADATA
(
    CUSTOMIZATION_REQUESTS_ID  NUMBER NOT NULL,
	PAYER_ID VARCHAR2(20) NOT NULL,
	STATUS VARCHAR2(10) DEFAULT('Pending') NOT NULL,
	MODULE_NAME VARCHAR2(200) NOT NULL,
	DRUG_CODE VARCHAR2(250) NOT NULL,
	DRUG_NAME VARCHAR2(250) NOT NULL,
	LAST_UPDATED_DATE DATE NOT NULL,
	IS_DELETED CHAR(1) DEFAULT('0') NOT NULL,
	REJECTION_REASON  VARCHAR2(4000),
	CONSTRAINT PK_CUSTOMIZATION_REQUESTS_ID PRIMARY KEY (CUSTOMIZATION_REQUESTS_ID)
);

CREATE SEQUENCE MDSS.PC_REQUESTS_METADATA_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;