--liquibase formatted sql

--changeset Payer-Customization-Service:051

CREATE TABLE MDSS.CUSTOMIZATION_REQUEST_DETAILS
(
    CUSTOMIZATION_DETAILS_ID  NUMBER NOT NULL,
	CUSTOMIZATION_REQUESTS_ID  NUMBER NOT NULL,
	CUSTOMIZATION_KEY VARCHAR2(200) NOT NULL,
	CUSTOMIZATION_VALUE VARCHAR2(200) NOT NULL,
	CONSTRAINT PK_CUS_REQ_DETAILS_ID PRIMARY KEY (CUSTOMIZATION_REQUESTS_ID),
	CONSTRAINT FK_CUS_DETAILS FOREIGN KEY(CUSTOMIZATION_REQUESTS_ID) REFERENCES "MDSS"."CUSTOMIZATION_REQUEST_METADATA" ("CUSTOMIZATION_REQUESTS_ID")

);

CREATE SEQUENCE MDSS.PC_REQUESTS_DETAILS_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;