--liquibase formatted sql

--changeset Payer-Customization-Service:052

DROP TABLE MDSS.CUSTOMIZATION_REQUEST_DETAILS;

CREATE TABLE MDSS.CUSTOMIZATION_REQUEST_DETAILS
(
    CUSTOMIZATION_DETAILS_ID  NUMBER NOT NULL,
	CUSTOMIZATION_REQUEST_ID  NUMBER NOT NULL,
	CUSTOMIZATION_KEY VARCHAR2(200) NOT NULL,
	CUSTOMIZATION_VALUE VARCHAR2(200) NOT NULL,
	CUSTOMIZATION_LABEL VARCHAR2(200) NOT NULL,
	CONSTRAINT PK_CUS_REQ_DETAILS_ID PRIMARY KEY (CUSTOMIZATION_DETAILS_ID),
	CONSTRAINT FK_CUS_DETAILS FOREIGN KEY(CUSTOMIZATION_REQUEST_ID) REFERENCES "MDSS"."CUSTOMIZATION_REQUEST_METADATA" ("CUSTOMIZATION_REQUESTS_ID")
);