--liquibase formatted sql

--changeset Payer-Customization-Service:053

ALTER TABLE MDSS.CUSTOMIZATION_REQUEST_METADATA ADD (IS_CUSTOMIZABLE CHAR(1));
ALTER TABLE MDSS.CUSTOMIZATION_REQUEST_METADATA MODIFY (IS_CUSTOMIZABLE CHAR(1) DEFAULT ('0') NOT NULL ENABLE NOVALIDATE);

