--liquibase formatted sql

--changeset Payer-Customization-Service:054

CREATE TABLE MDSS.CUSTOMIZATION_REQUESTS_AUDIT
(
	CUSTOMIZATION_REQUEST_AUDIT_ID NUMBER NOT NULL,
    USER_ID  VARCHAR2(200) NOT NULL,
	ENTITY_ID  NUMBER NOT NULL,
	ENTITY_NAME VARCHAR2(200),
	ACTION VARCHAR2(200) NOT NULL,
	LAST_UPDATED_DATE DATE NOT NULL,
	CHANGE CLOB NULL,
	ACCOUNT_ID VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_CUSTOMIZATION_REQUEST_AUDIT_ID PRIMARY KEY (CUSTOMIZATION_REQUEST_AUDIT_ID)
);

CREATE SEQUENCE MDSS.CUSTOMIZATION_REQUESTS_AUDIT_ID_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;