--liquibase formatted sql

--changeset Payer-Customization-Service:059

ALTER TABLE "MDSS"."CUSTOMIZATION_REQUEST_METADATA"
DROP COLUMN IS_CUSTOMIZABLE;

ALTER TABLE "MDSS"."CUSTOMIZATION_REQUEST_DETAILS"
ADD (IS_CUSTOMIZABLE CHAR(1) DEFAULT ('0') NOT NULL ENABLE NOVALIDATE);