apiVersion: v1
kind: Service
metadata:
  name: br-service
  namespace: pbm-prod
  labels:
    app: br-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: br-service
