apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility
  namespace: qa
  labels:
    app: eligibility
spec:
  selector:
    matchLabels:
      app: eligibility
  template:
    metadata:
      labels:
        app: eligibility
    spec:
      containers:
        - name: eligibility
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/qa/eligibility:latest
          resources:
           requests:
             memory: 500Mi
             cpu: 0.1
           limits:
             memory: 3Gi
             cpu: 2
          volumeMounts:
            - mountPath: /wallet
              name: wallet-config
              readOnly: true
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: claim-db-creds
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: claim-db-creds
                key: password
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: ocir-login-credentials
      volumes:
        - name: wallet-config
          configMap:
            name: wallet-adb-files-qa
