apiVersion: v1
kind: Service
metadata:
  name: pbm-authentication-server
  namespace: pbm-qa
  labels:
    app: pbm-authentication-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: pbm-authentication-server
