#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379


#spring.rabbitmq.host = devone.waseel.com
#spring.rabbitmq.port = 5672
#spring.rabbitmq.username = guest
#spring.rabbitmq.password = guest

spring.datasource.url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.username = hira
spring.datasource.password = ADBPortal_HI2021
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=180000
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.properties.hibernate.default_schema=HIRA

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

server.port=8086

#/////////////////Configure Spring Security//////////////////////////////
jwt.secret=UrSoBeautifulgrace@#!0569821638

security.frontendOrigin: http://localhost:4200


clients.sso.url=http://localhost:9999


allowed-clients.clients[0].id=prescription-service
allowed-clients.clients[0].secret=prescription-service-secret

logging.level.feign=DEBUG
logging.level.com.waseel.pbm.authentication.clients=DEBUG
logging.level.org.springframework.security=DEBUG
