spring.datasource.url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/wallet
spring.datasource.username = ${ORACLE_ADB_USERNAME}
spring.datasource.password = ${ORACLE_ADB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=180000
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.properties.hibernate.default_schema=HIRA


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#/////////////////Configure Spring Security//////////////////////////////
jwt.secret=${jwtSecret}

security.frontendOrigin: https://stg-pbm.waseel.com/


clients.sso.url=https://qa-sso.waseel.com/api

logging.level.feign=DEBUG
logging.level.com.waseel.pbm.authentication.clients=DEBUG
logging.level.org.hibernate.SQL=DEBUG

springdoc.default-produces-media-type=application/json

swagger.url:https://stg-pbm-admin.waseel.com/api/oauth
swagger.authorization.url:https://stg-pbm-admin.waseel.com/api/oauth/signIn
swagger.refresh.url:https://stg-pbm-admin.waseel.com/api/oauth/refresh