spring.profiles.active=@activatedSpringProperties@

spring.messages.basename=internationalization/messages

logging.level.org.hibernate.SQL=DEBUG
logging.level.feign=DEBUG
logging.level.com.waseel.pbm.authentication.clients.signup.TawuniyaClient=DEBUG
logging.level.com.waseel.pbm.authentication.clients.ContractServiceClient=DEBUG
spring.main.allow-bean-definition-overriding=true