#Logging Configuration
#-----------------------------------
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.hibernate.SQL=DEBUG
#---------------------------------
#DataBase Configuration
#-----------------------------------
spring.datasource.url=jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=/wallet/
spring.datasource.username =MDSS
spring.datasource.password =Dev#$#MSpro$#3234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=300000
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#------------------------------
#Liquibase configuration
#------------------------------
spring.liquibase.enabled= true
logging.level.liquibase = INFO
spring.liquibase.change-log = classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=MDSS

pbmPayerApisServiceClient.url:http://pbm-payer-apis-service.pbm-qa:8080/pbm-payer-apis-service