
spring.jpa.properties.hibernate.search.backend.hosts=@elasticsearchHosts@
spring.jpa.properties.hibernate.search.backend.index_schema_management_strategy=create-or-validate
spring.jpa.properties.hibernate.search.backend.schema_management.minimal_required_status=yellow
spring.jpa.properties.hibernate.search.backend.schema_management.minimal_required_status_wait_timeout=120000
spring.jpa.properties.hibernate.search.backend.discovery.enabled=false
spring.jpa.properties.hibernate.search.enabled=true

spring.jpa.properties.hibernate.search.backend.analysis.configurer=class:com.waseel.dssadminservice.configuration.CustomElasticsearchAnalysisConfigurer

spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=3
# spring.jpa.properties.hibernate.search.backend.protocol=
# spring.jpa.properties.hibernate.search.backend.username=
# spring.jpa.properties.hibernate.search.backend.password=


# logging.level.org.hibernate.search=TRACE