package com.waseel.pbm.payercustomizationservice.enums;

public enum CustomizationRequestDetailKeys {

	ICD_CODE, ICD_DESCRIPTION, INTERACTED_DRUG_CODE, INTERACTED_DRUG_NAME, GENDER, REJECTION_CATEGORY, FROM_AGE_IN_DAYS,
	TO_AGE_IN_DAYS, DRUG_TYPE, MAX_VALUE_PER_DAY, UNIT_TYPE, PRODUCT_PACKAGE_SIZE, CUSTOMIZABLE;
}
