//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ApprovalLineCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApprovalLineCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.waseel.com/wsdl/primary/wschema}caseTypeST"/&gt;
 *         &lt;element name="statusCode" type="{http://www.waseel.com/wsdl/primary/wschema}statusCodeST" minOccurs="0"/&gt;
 *         &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="patientFileNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="submissionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="approvalVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApprovalLineCT", propOrder = {
    "type",
    "statusCode",
    "approvalNumber",
    "patientFileNumber",
    "submissionDate",
    "approvalVersion"
})
public class ApprovalLineCT {

    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected CaseTypeST type;
    @XmlSchemaType(name = "string")
    protected StatusCodeST statusCode;
    @XmlElement(required = true)
    protected String approvalNumber;
    protected String patientFileNumber;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar submissionDate;
    protected String approvalVersion;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CaseTypeST }
     *     
     */
    public CaseTypeST getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseTypeST }
     *     
     */
    public void setType(CaseTypeST value) {
        this.type = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCodeST }
     *     
     */
    public StatusCodeST getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCodeST }
     *     
     */
    public void setStatusCode(StatusCodeST value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the approvalNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalNumber() {
        return approvalNumber;
    }

    /**
     * Sets the value of the approvalNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalNumber(String value) {
        this.approvalNumber = value;
    }

    /**
     * Gets the value of the patientFileNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatientFileNumber() {
        return patientFileNumber;
    }

    /**
     * Sets the value of the patientFileNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatientFileNumber(String value) {
        this.patientFileNumber = value;
    }

    /**
     * Gets the value of the submissionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSubmissionDate() {
        return submissionDate;
    }

    /**
     * Sets the value of the submissionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSubmissionDate(XMLGregorianCalendar value) {
        this.submissionDate = value;
    }

    /**
     * Gets the value of the approvalVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovalVersion() {
        return approvalVersion;
    }

    /**
     * Sets the value of the approvalVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovalVersion(String value) {
        this.approvalVersion = value;
    }

}
