//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApprovalSubmissionResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApprovalSubmissionResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestedData" type="{http://www.waseel.com/wsdl/primary/wschema}ApprovalSubmissionRequestCT"/&gt;
 *         &lt;element name="ApprovalResponse" type="{http://www.waseel.com/wsdl/primary/wschema}ApprovalResponseCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApprovalSubmissionResponseCT", propOrder = {
    "requestedData",
    "approvalResponse"
})
public class ApprovalSubmissionResponseCT {

    @XmlElement(name = "RequestedData", required = true)
    protected ApprovalSubmissionRequestCT requestedData;
    @XmlElement(name = "ApprovalResponse", required = true)
    protected ApprovalResponseCT approvalResponse;

    /**
     * Gets the value of the requestedData property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalSubmissionRequestCT }
     *     
     */
    public ApprovalSubmissionRequestCT getRequestedData() {
        return requestedData;
    }

    /**
     * Sets the value of the requestedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalSubmissionRequestCT }
     *     
     */
    public void setRequestedData(ApprovalSubmissionRequestCT value) {
        this.requestedData = value;
    }

    /**
     * Gets the value of the approvalResponse property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalResponseCT }
     *     
     */
    public ApprovalResponseCT getApprovalResponse() {
        return approvalResponse;
    }

    /**
     * Sets the value of the approvalResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalResponseCT }
     *     
     */
    public void setApprovalResponse(ApprovalResponseCT value) {
        this.approvalResponse = value;
    }

}
