//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApprovalInquiryRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApprovalInquiryRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Criteria" type="{http://www.waseel.com/wsdl/primary/wschema}ApprovalCriteriaCT"/&gt;
 *         &lt;element name="ApprovalReference"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="approvalVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApprovalInquiryRequestCT", propOrder = {
    "criteria",
    "approvalReference"
})
public class ApprovalInquiryRequestCT {

    @XmlElement(name = "Criteria")
    protected ApprovalCriteriaCT criteria;
    @XmlElement(name = "ApprovalReference")
    protected ApprovalInquiryRequestCT.ApprovalReference approvalReference;

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalCriteriaCT }
     *     
     */
    public ApprovalCriteriaCT getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalCriteriaCT }
     *     
     */
    public void setCriteria(ApprovalCriteriaCT value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the approvalReference property.
     * 
     * @return
     *     possible object is
     *     {@link ApprovalInquiryRequestCT.ApprovalReference }
     *     
     */
    public ApprovalInquiryRequestCT.ApprovalReference getApprovalReference() {
        return approvalReference;
    }

    /**
     * Sets the value of the approvalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApprovalInquiryRequestCT.ApprovalReference }
     *     
     */
    public void setApprovalReference(ApprovalInquiryRequestCT.ApprovalReference value) {
        this.approvalReference = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="approvalVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "approvalNumber",
        "approvalVersion"
    })
    public static class ApprovalReference {

        @XmlElement(required = true)
        protected String approvalNumber;
        protected String approvalVersion;

        /**
         * Gets the value of the approvalNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalNumber() {
            return approvalNumber;
        }

        /**
         * Sets the value of the approvalNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalNumber(String value) {
            this.approvalNumber = value;
        }

        /**
         * Gets the value of the approvalVersion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalVersion() {
            return approvalVersion;
        }

        /**
         * Sets the value of the approvalVersion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalVersion(String value) {
            this.approvalVersion = value;
        }

    }

}
