//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for benefitCodeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="benefitCodeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GENERAL"/&gt;
 *     &lt;enumeration value="DENTAL"/&gt;
 *     &lt;enumeration value="MATERNITY"/&gt;
 *     &lt;enumeration value="OUTPATIENT"/&gt;
 *     &lt;enumeration value="ALLERGIES"/&gt;
 *     &lt;enumeration value="INPATIENT"/&gt;
 *     &lt;enumeration value="OPTICAL"/&gt;
 *     &lt;enumeration value="PREEXISTING"/&gt;
 *     &lt;enumeration value="CHRONIC"/&gt;
 *     &lt;enumeration value="REPATRIATION"/&gt;
 *     &lt;enumeration value="OUTPATIENT"/&gt;
 *     &lt;enumeration value="PSYCHIATRY"/&gt;
 *     &lt;enumeration value="CIRCUMCISION"/&gt;
 *     &lt;enumeration value="TERRORISM"/&gt;
 *     &lt;enumeration value="PREVENTIVE"/&gt;
 *     &lt;enumeration value="AMBULANCE"/&gt;
 *     &lt;enumeration value="DIALYSIS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "benefitCodeST")
@XmlEnum
public enum BenefitCodeST {

    GENERAL,
    DENTAL,
    MATERNITY,
    OUTPATIENT,
    ALLERGIES,
    INPATIENT,
    OPTICAL,
    PREEXISTING,
    CHRONIC,
    REPATRIATION,
    PSYCHIATRY,
    CIRCUMCISION,
    TERRORISM,
    PREVENTIVE,
    AMBULANCE,
    DIALYSIS;

    public String value() {
        return name();
    }

    public static BenefitCodeST fromValue(String v) {
        return valueOf(v);
    }

}
