//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for caseTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="caseTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="INPATIENT"/&gt;
 *     &lt;enumeration value="OUTPATIENT"/&gt;
 *     &lt;enumeration value="DENTAL"/&gt;
 *     &lt;enumeration value="DELIVERY"/&gt;
 *     &lt;enumeration value="OPTICAL"/&gt;
 *     &lt;enumeration value="PHARMACY"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "caseTypeST")
@XmlEnum
public enum CaseTypeST {

    INPATIENT,
    OUTPATIENT,
    DENTAL,
    DELIVERY,
    OPTICAL,
    PHARMACY;

    public String value() {
        return name();
    }

    public static CaseTypeST fromValue(String v) {
        return valueOf(v);
    }

}
