//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CaseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CaseQualifier" type="{http://www.waseel.com/wsdl/primary/wschema}caseQualifierST"/&gt;
 *         &lt;element name="patientShare" type="{http://www.waseel.com/wsdl/primary/wschema}amountST"/&gt;
 *         &lt;element name="maxPatientShare" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="maxConsultFee" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *         &lt;element name="approvalThreshold" type="{http://www.waseel.com/wsdl/primary/wschema}amountST" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CaseCT", propOrder = {
    "caseQualifier",
    "patientShare",
    "maxPatientShare",
    "maxConsultFee",
    "approvalThreshold"
})
public class CaseCT {

    @XmlElement(name = "CaseQualifier", required = true)
    @XmlSchemaType(name = "string")
    protected CaseQualifierST caseQualifier;
    @XmlElement(required = true)
    protected AmountST patientShare;
    protected AmountST maxPatientShare;
    protected AmountST maxConsultFee;
    protected AmountST approvalThreshold;

    /**
     * Gets the value of the caseQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link CaseQualifierST }
     *     
     */
    public CaseQualifierST getCaseQualifier() {
        return caseQualifier;
    }

    /**
     * Sets the value of the caseQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseQualifierST }
     *     
     */
    public void setCaseQualifier(CaseQualifierST value) {
        this.caseQualifier = value;
    }

    /**
     * Gets the value of the patientShare property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getPatientShare() {
        return patientShare;
    }

    /**
     * Sets the value of the patientShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setPatientShare(AmountST value) {
        this.patientShare = value;
    }

    /**
     * Gets the value of the maxPatientShare property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getMaxPatientShare() {
        return maxPatientShare;
    }

    /**
     * Sets the value of the maxPatientShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setMaxPatientShare(AmountST value) {
        this.maxPatientShare = value;
    }

    /**
     * Gets the value of the maxConsultFee property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getMaxConsultFee() {
        return maxConsultFee;
    }

    /**
     * Sets the value of the maxConsultFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setMaxConsultFee(AmountST value) {
        this.maxConsultFee = value;
    }

    /**
     * Gets the value of the approvalThreshold property.
     * 
     * @return
     *     possible object is
     *     {@link AmountST }
     *     
     */
    public AmountST getApprovalThreshold() {
        return approvalThreshold;
    }

    /**
     * Sets the value of the approvalThreshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmountST }
     *     
     */
    public void setApprovalThreshold(AmountST value) {
        this.approvalThreshold = value;
    }

}
