//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for diagnosisTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="diagnosisTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PRINCIPAL"/&gt;
 *     &lt;enumeration value="SCONDARY"/&gt;
 *     &lt;enumeration value="ADMITTING"/&gt;
 *     &lt;enumeration value="DISCHARGE"/&gt;
 *     &lt;enumeration value="CAUSEOFDEATH"/&gt;
 *     &lt;enumeration value="PROVISIONAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "diagnosisTypeST")
@XmlEnum
public enum DiagnosisTypeST {

    PRINCIPAL,
    SCONDARY,
    ADMITTING,
    DISCHARGE,
    CAUSEOFDEATH,
    PROVISIONAL;

    public String value() {
        return name();
    }

    public static DiagnosisTypeST fromValue(String v) {
        return valueOf(v);
    }

}
