//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispenseSubmissionRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispenseSubmissionRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ApprovalReference"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="DispenseServiceRequest" type="{http://www.waseel.com/wsdl/primary/wschema}DispenseServiceRequestCT" maxOccurs="unbounded"/&gt;
 *         &lt;element name="pharmacyCode" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispenseSubmissionRequestCT", propOrder = {
    "approvalReference",
    "dispenseServiceRequest",
    "pharmacyCode"
})
public class DispenseSubmissionRequestCT {

    @XmlElement(name = "ApprovalReference", required = true)
    protected DispenseSubmissionRequestCT.ApprovalReference approvalReference;
    @XmlElement(name = "DispenseServiceRequest", required = true)
    protected List<DispenseServiceRequestCT> dispenseServiceRequest;
    @XmlElement(required = true)
    protected String pharmacyCode;

    /**
     * Gets the value of the approvalReference property.
     * 
     * @return
     *     possible object is
     *     {@link DispenseSubmissionRequestCT.ApprovalReference }
     *     
     */
    public DispenseSubmissionRequestCT.ApprovalReference getApprovalReference() {
        return approvalReference;
    }

    /**
     * Sets the value of the approvalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispenseSubmissionRequestCT.ApprovalReference }
     *     
     */
    public void setApprovalReference(DispenseSubmissionRequestCT.ApprovalReference value) {
        this.approvalReference = value;
    }

    /**
     * Gets the value of the dispenseServiceRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dispenseServiceRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDispenseServiceRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DispenseServiceRequestCT }
     * 
     * 
     */
    public List<DispenseServiceRequestCT> getDispenseServiceRequest() {
        if (dispenseServiceRequest == null) {
            dispenseServiceRequest = new ArrayList<DispenseServiceRequestCT>();
        }
        return this.dispenseServiceRequest;
    }

    /**
     * Gets the value of the pharmacyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPharmacyCode() {
        return pharmacyCode;
    }

    /**
     * Sets the value of the pharmacyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPharmacyCode(String value) {
        this.pharmacyCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "approvalNumber"
    })
    public static class ApprovalReference {

        @XmlElement(required = true)
        protected String approvalNumber;

        /**
         * Gets the value of the approvalNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalNumber() {
            return approvalNumber;
        }

        /**
         * Sets the value of the approvalNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalNumber(String value) {
            this.approvalNumber = value;
        }

    }

}
