//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispenseInquiryRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispenseInquiryRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ApprovalReference"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispenseInquiryRequestCT", propOrder = {
    "approvalReference"
})
public class DispenseInquiryRequestCT {

    @XmlElement(name = "ApprovalReference", required = true)
    protected DispenseInquiryRequestCT.ApprovalReference approvalReference;

    /**
     * Gets the value of the approvalReference property.
     * 
     * @return
     *     possible object is
     *     {@link DispenseInquiryRequestCT.ApprovalReference }
     *     
     */
    public DispenseInquiryRequestCT.ApprovalReference getApprovalReference() {
        return approvalReference;
    }

    /**
     * Sets the value of the approvalReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispenseInquiryRequestCT.ApprovalReference }
     *     
     */
    public void setApprovalReference(DispenseInquiryRequestCT.ApprovalReference value) {
        this.approvalReference = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="approvalNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "approvalNumber"
    })
    public static class ApprovalReference {

        @XmlElement(required = true)
        protected String approvalNumber;

        /**
         * Gets the value of the approvalNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getApprovalNumber() {
            return approvalNumber;
        }

        /**
         * Sets the value of the approvalNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setApprovalNumber(String value) {
            this.approvalNumber = value;
        }

    }

}
