//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EligibilitySubmissionReponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EligibilitySubmissionReponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestedData" type="{http://www.waseel.com/wsdl/primary/wschema}EligibilitySubmissionRequestCT"/&gt;
 *         &lt;element name="Status" type="{http://www.waseel.com/wsdl/primary/wschema}StatusCT"/&gt;
 *         &lt;element name="MemberInfo" type="{http://www.waseel.com/wsdl/primary/wschema}MemberInfoCT" minOccurs="0"/&gt;
 *         &lt;element name="CoverageInfo" type="{http://www.waseel.com/wsdl/primary/wschema}CoverageInfoCT" minOccurs="0"/&gt;
 *         &lt;element name="additionalInfo" type="{http://www.waseel.com/wsdl/primary/wschema}additionalInfoST" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EligibilitySubmissionReponseCT", propOrder = {
    "requestedData",
    "status",
    "memberInfo",
    "coverageInfo",
    "additionalInfo"
})
public class EligibilitySubmissionReponseCT {

    @XmlElement(name = "RequestedData", required = true)
    protected EligibilitySubmissionRequestCT requestedData;
    @XmlElement(name = "Status", required = true)
    protected StatusCT status;
    @XmlElement(name = "MemberInfo")
    protected MemberInfoCT memberInfo;
    @XmlElement(name = "CoverageInfo")
    protected CoverageInfoCT coverageInfo;
    protected String additionalInfo;

    /**
     * Gets the value of the requestedData property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilitySubmissionRequestCT }
     *     
     */
    public EligibilitySubmissionRequestCT getRequestedData() {
        return requestedData;
    }

    /**
     * Sets the value of the requestedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilitySubmissionRequestCT }
     *     
     */
    public void setRequestedData(EligibilitySubmissionRequestCT value) {
        this.requestedData = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link StatusCT }
     *     
     */
    public StatusCT getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusCT }
     *     
     */
    public void setStatus(StatusCT value) {
        this.status = value;
    }

    /**
     * Gets the value of the memberInfo property.
     * 
     * @return
     *     possible object is
     *     {@link MemberInfoCT }
     *     
     */
    public MemberInfoCT getMemberInfo() {
        return memberInfo;
    }

    /**
     * Sets the value of the memberInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberInfoCT }
     *     
     */
    public void setMemberInfo(MemberInfoCT value) {
        this.memberInfo = value;
    }

    /**
     * Gets the value of the coverageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CoverageInfoCT }
     *     
     */
    public CoverageInfoCT getCoverageInfo() {
        return coverageInfo;
    }

    /**
     * Sets the value of the coverageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverageInfoCT }
     *     
     */
    public void setCoverageInfo(CoverageInfoCT value) {
        this.coverageInfo = value;
    }

    /**
     * Gets the value of the additionalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Sets the value of the additionalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalInfo(String value) {
        this.additionalInfo = value;
    }

}
