//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FileTypeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FileTypeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Medical Report"/&gt;
 *     &lt;enumeration value="X-Ray result"/&gt;
 *     &lt;enumeration value="Lab Result"/&gt;
 *     &lt;enumeration value="Iqama/ID copy"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FileTypeST")
@XmlEnum
public enum FileTypeST {

    @XmlEnumValue("Medical Report")
    MEDICAL_REPORT("Medical Report"),
    @XmlEnumValue("X-Ray result")
    X_RAY_RESULT("X-Ray result"),
    @XmlEnumValue("Lab Result")
    LAB_RESULT("Lab Result"),
    @XmlEnumValue("Iqama/ID copy")
    IQAMA_ID_COPY("Iqama/ID copy");
    private final String value;

    FileTypeST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FileTypeST fromValue(String v) {
        for (FileTypeST c: FileTypeST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
