//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeneralInfoCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeneralInfoCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Member" type="{http://www.waseel.com/wsdl/primary/wschema}MemberCT"/&gt;
 *         &lt;element name="VisitInformation" type="{http://www.waseel.com/wsdl/primary/wschema}visitInfoCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeneralInfoCT", propOrder = {
    "member",
    "visitInformation"
})
public class GeneralInfoCT {

    @XmlElement(name = "Member", required = true)
    protected MemberCT member;
    @XmlElement(name = "VisitInformation", required = true)
    protected VisitInfoCT visitInformation;

    /**
     * Gets the value of the member property.
     * 
     * @return
     *     possible object is
     *     {@link MemberCT }
     *     
     */
    public MemberCT getMember() {
        return member;
    }

    /**
     * Sets the value of the member property.
     * 
     * @param value
     *     allowed object is
     *     {@link MemberCT }
     *     
     */
    public void setMember(MemberCT value) {
        this.member = value;
    }

    /**
     * Gets the value of the visitInformation property.
     * 
     * @return
     *     possible object is
     *     {@link VisitInfoCT }
     *     
     */
    public VisitInfoCT getVisitInformation() {
        return visitInformation;
    }

    /**
     * Sets the value of the visitInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisitInfoCT }
     *     
     */
    public void setVisitInformation(VisitInfoCT value) {
        this.visitInformation = value;
    }

}
