//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for illnessCodeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="illnessCodeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AMBULANCE"/&gt;
 *     &lt;enumeration value="DIALYSIS"/&gt;
 *     &lt;enumeration value="CHECKUP"/&gt;
 *     &lt;enumeration value="CHRONIC"/&gt;
 *     &lt;enumeration value="CIRCUMCISION"/&gt;
 *     &lt;enumeration value="CLEANING"/&gt;
 *     &lt;enumeration value="CONGENITAL"/&gt;
 *     &lt;enumeration value="INFERTILITY"/&gt;
 *     &lt;enumeration value="MATERNITY COMPLICATIONS"/&gt;
 *     &lt;enumeration value="PREEXISTING"/&gt;
 *     &lt;enumeration value="NA"/&gt;
 *     &lt;enumeration value="ORTHODONTICS"/&gt;
 *     &lt;enumeration value="PREGNANCY"/&gt;
 *     &lt;enumeration value="PSYCHIATRY"/&gt;
 *     &lt;enumeration value="RTA"/&gt;
 *     &lt;enumeration value="SPORTS"/&gt;
 *     &lt;enumeration value="VACCINATION"/&gt;
 *     &lt;enumeration value="WRA"/&gt;
 *     &lt;enumeration value="REGULAR DENTAL TREATMENT"/&gt;
 *     &lt;enumeration value="EMERGENCY RESUSCITATION"/&gt;
 *     &lt;enumeration value="EMERGENCY"/&gt;
 *     &lt;enumeration value="EMERGENCY URGENT"/&gt;
 *     &lt;enumeration value="EMERGENCY LESS URGENT"/&gt;
 *     &lt;enumeration value="EMERGENCY NOT URGENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "illnessCodeST")
@XmlEnum
public enum IllnessCodeST {

    AMBULANCE("AMBULANCE"),
    DIALYSIS("DIALYSIS"),
    CHECKUP("CHECKUP"),
    CHRONIC("CHRONIC"),
    CIRCUMCISION("CIRCUMCISION"),
    CLEANING("CLEANING"),
    CONGENITAL("CONGENITAL"),
    INFERTILITY("INFERTILITY"),
    @XmlEnumValue("MATERNITY COMPLICATIONS")
    MATERNITY_COMPLICATIONS("MATERNITY COMPLICATIONS"),
    PREEXISTING("PREEXISTING"),
    NA("NA"),
    ORTHODONTICS("ORTHODONTICS"),
    PREGNANCY("PREGNANCY"),
    PSYCHIATRY("PSYCHIATRY"),
    RTA("RTA"),
    SPORTS("SPORTS"),
    VACCINATION("VACCINATION"),
    WRA("WRA"),
    @XmlEnumValue("REGULAR DENTAL TREATMENT")
    REGULAR_DENTAL_TREATMENT("REGULAR DENTAL TREATMENT"),
    @XmlEnumValue("EMERGENCY RESUSCITATION")
    EMERGENCY_RESUSCITATION("EMERGENCY RESUSCITATION"),
    EMERGENCY("EMERGENCY"),
    @XmlEnumValue("EMERGENCY URGENT")
    EMERGENCY_URGENT("EMERGENCY URGENT"),
    @XmlEnumValue("EMERGENCY LESS URGENT")
    EMERGENCY_LESS_URGENT("EMERGENCY LESS URGENT"),
    @XmlEnumValue("EMERGENCY NOT URGENT")
    EMERGENCY_NOT_URGENT("EMERGENCY NOT URGENT");
    private final String value;

    IllnessCodeST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IllnessCodeST fromValue(String v) {
        for (IllnessCodeST c: IllnessCodeST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
