//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntimationInquiryRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntimationInquiryRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="Criteria" type="{http://www.waseel.com/wsdl/primary/wschema}IntimationCriteriaCT"/&gt;
 *         &lt;element name="IntimationReference"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntimationInquiryRequestCT", propOrder = {
    "criteria",
    "intimationReference"
})
public class IntimationInquiryRequestCT {

    @XmlElement(name = "Criteria")
    protected IntimationCriteriaCT criteria;
    @XmlElement(name = "IntimationReference")
    protected IntimationInquiryRequestCT.IntimationReference intimationReference;

    /**
     * Gets the value of the criteria property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationCriteriaCT }
     *     
     */
    public IntimationCriteriaCT getCriteria() {
        return criteria;
    }

    /**
     * Sets the value of the criteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationCriteriaCT }
     *     
     */
    public void setCriteria(IntimationCriteriaCT value) {
        this.criteria = value;
    }

    /**
     * Gets the value of the intimationReference property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationInquiryRequestCT.IntimationReference }
     *     
     */
    public IntimationInquiryRequestCT.IntimationReference getIntimationReference() {
        return intimationReference;
    }

    /**
     * Sets the value of the intimationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationInquiryRequestCT.IntimationReference }
     *     
     */
    public void setIntimationReference(IntimationInquiryRequestCT.IntimationReference value) {
        this.intimationReference = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "batchReference"
    })
    public static class IntimationReference {

        @XmlElement(required = true)
        protected String batchReference;

        /**
         * Gets the value of the batchReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBatchReference() {
            return batchReference;
        }

        /**
         * Sets the value of the batchReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBatchReference(String value) {
            this.batchReference = value;
        }

    }

}
