//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntimationSubmissionResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntimationSubmissionResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestedData" type="{http://www.waseel.com/wsdl/primary/wschema}IntimationSubmissionRequestCT"/&gt;
 *         &lt;element name="IntimationResponse" type="{http://www.waseel.com/wsdl/primary/wschema}IntimationResponseCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntimationSubmissionResponseCT", propOrder = {
    "requestedData",
    "intimationResponse"
})
public class IntimationSubmissionResponseCT {

    @XmlElement(name = "RequestedData", required = true)
    protected IntimationSubmissionRequestCT requestedData;
    @XmlElement(name = "IntimationResponse", required = true)
    protected IntimationResponseCT intimationResponse;

    /**
     * Gets the value of the requestedData property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationSubmissionRequestCT }
     *     
     */
    public IntimationSubmissionRequestCT getRequestedData() {
        return requestedData;
    }

    /**
     * Sets the value of the requestedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationSubmissionRequestCT }
     *     
     */
    public void setRequestedData(IntimationSubmissionRequestCT value) {
        this.requestedData = value;
    }

    /**
     * Gets the value of the intimationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationResponseCT }
     *     
     */
    public IntimationResponseCT getIntimationResponse() {
        return intimationResponse;
    }

    /**
     * Sets the value of the intimationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationResponseCT }
     *     
     */
    public void setIntimationResponse(IntimationResponseCT value) {
        this.intimationResponse = value;
    }

}
