//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IntimationDetailResponseCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntimationDetailResponseCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestedData"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="IntimationReference"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="IntimationResponse" type="{http://www.waseel.com/wsdl/primary/wschema}IntimationResponseCT"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntimationDetailResponseCT", propOrder = {
    "requestedData",
    "intimationResponse"
})
public class IntimationDetailResponseCT {

    @XmlElement(name = "RequestedData", required = true)
    protected IntimationDetailResponseCT.RequestedData requestedData;
    @XmlElement(name = "IntimationResponse", required = true)
    protected IntimationResponseCT intimationResponse;

    /**
     * Gets the value of the requestedData property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationDetailResponseCT.RequestedData }
     *     
     */
    public IntimationDetailResponseCT.RequestedData getRequestedData() {
        return requestedData;
    }

    /**
     * Sets the value of the requestedData property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationDetailResponseCT.RequestedData }
     *     
     */
    public void setRequestedData(IntimationDetailResponseCT.RequestedData value) {
        this.requestedData = value;
    }

    /**
     * Gets the value of the intimationResponse property.
     * 
     * @return
     *     possible object is
     *     {@link IntimationResponseCT }
     *     
     */
    public IntimationResponseCT getIntimationResponse() {
        return intimationResponse;
    }

    /**
     * Sets the value of the intimationResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntimationResponseCT }
     *     
     */
    public void setIntimationResponse(IntimationResponseCT value) {
        this.intimationResponse = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="IntimationReference"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "intimationReference"
    })
    public static class RequestedData {

        @XmlElement(name = "IntimationReference", required = true)
        protected IntimationDetailResponseCT.RequestedData.IntimationReference intimationReference;

        /**
         * Gets the value of the intimationReference property.
         * 
         * @return
         *     possible object is
         *     {@link IntimationDetailResponseCT.RequestedData.IntimationReference }
         *     
         */
        public IntimationDetailResponseCT.RequestedData.IntimationReference getIntimationReference() {
            return intimationReference;
        }

        /**
         * Sets the value of the intimationReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link IntimationDetailResponseCT.RequestedData.IntimationReference }
         *     
         */
        public void setIntimationReference(IntimationDetailResponseCT.RequestedData.IntimationReference value) {
            this.intimationReference = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "batchReference"
        })
        public static class IntimationReference {

            @XmlElement(required = true)
            protected String batchReference;

            /**
             * Gets the value of the batchReference property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBatchReference() {
                return batchReference;
            }

            /**
             * Sets the value of the batchReference property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBatchReference(String value) {
                this.batchReference = value;
            }

        }

    }

}
