//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MEOBRequestCT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MEOBRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="batchID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SubmittedClaimsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MEOBRequestCT", propOrder = {
    "batchID",
    "submittedClaimsCount"
})
public class MEOBRequestCT {

    @XmlElement(required = true)
    protected String batchID;
    @XmlElement(name = "SubmittedClaimsCount", required = true)
    protected BigInteger submittedClaimsCount;
    
    
    public MEOBRequestCT() {
    
    }	
    
    public MEOBRequestCT(String batchID, long submittedClaimsCount) {
		super();
		this.batchID = batchID;
		this.submittedClaimsCount = BigInteger.valueOf(submittedClaimsCount);
    }	

    /**
     * Gets the value of the batchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatchID() {
        return batchID;
    }

    /**
     * Sets the value of the batchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatchID(String value) {
        this.batchID = value;
    }

    /**
     * Gets the value of the submittedClaimsCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSubmittedClaimsCount() {
        return submittedClaimsCount;
    }

    /**
     * Sets the value of the submittedClaimsCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSubmittedClaimsCount(BigInteger value) {
        this.submittedClaimsCount = value;
    }

}
