//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//

package com.waseel.eligibility.client.portal.model;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Calendar;
import java.util.GregorianCalendar;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for MSOBRequestCT complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MSOBRequestCT"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="batchID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="totalClaimCount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="totalClaimedAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="batchReference" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="sendDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *         &lt;element name="NotAcceptedClaimsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="NotAcceptedClaimsList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NotAcceptedClaimsAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="AcceptedClaimsCount" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="AcceptedClaimsAmount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *         &lt;element name="TotalVATamount" type="{http://www.w3.org/2001/XMLSchema}decimal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MSOBRequestCT", propOrder = { "batchID", "totalClaimCount", "totalClaimedAmount", "batchReference",
		"sendDate", "notAcceptedClaimsCount", "notAcceptedClaimsList", "notAcceptedClaimsAmount", "acceptedClaimsCount",
		"acceptedClaimsAmount", "totalVATamount", "billingPeriodFrom", "billingPeriodTo" })
public class MSOBRequestCT {

	@XmlElement(required = true)
	protected String batchID;
	@XmlElement(required = true)
	protected BigInteger totalClaimCount;
	@XmlElement(required = true)
	protected BigDecimal totalClaimedAmount;
	@XmlElement(required = true)
	protected String batchReference;
	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar sendDate;
	@XmlElement(name = "NotAcceptedClaimsCount", required = true)
	protected BigInteger notAcceptedClaimsCount;
	@XmlElement(name = "NotAcceptedClaimsList")
	protected String notAcceptedClaimsList;
	@XmlElement(name = "NotAcceptedClaimsAmount", required = true)
	protected BigDecimal notAcceptedClaimsAmount;
	@XmlElement(name = "AcceptedClaimsCount", required = true)
	protected BigInteger acceptedClaimsCount;
	@XmlElement(name = "AcceptedClaimsAmount", required = true)
	protected BigDecimal acceptedClaimsAmount;
	@XmlElement(name = "TotalVATamount", required = true)
	protected BigDecimal totalVATamount;
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar billingPeriodFrom;
	@XmlElement(required = true)
	@XmlSchemaType(name = "dateTime")
	protected XMLGregorianCalendar billingPeriodTo;

	public MSOBRequestCT() {

	}

	public MSOBRequestCT(String batchID, Long totalClaimCount, BigDecimal totalClaimedAmount, BigDecimal totalVATamount) {
		super();
		this.batchID = batchID;
		this.totalClaimCount = BigInteger.valueOf(totalClaimCount);
		this.totalClaimedAmount = totalClaimedAmount;
		this.totalVATamount = totalVATamount;

		this.batchReference = this.batchID;
		try {
			this.sendDate = DatatypeFactory.newInstance()
					.newXMLGregorianCalendar((GregorianCalendar) Calendar.getInstance());
			this.billingPeriodFrom = DatatypeFactory.newInstance()
					.newXMLGregorianCalendar((GregorianCalendar) Calendar.getInstance());
			this.billingPeriodTo = DatatypeFactory.newInstance()
					.newXMLGregorianCalendar((GregorianCalendar) Calendar.getInstance());
		} catch (DatatypeConfigurationException e) {
		}
		this.acceptedClaimsAmount = totalClaimedAmount;
		this.acceptedClaimsCount = this.totalClaimCount;
		this.notAcceptedClaimsAmount = BigDecimal.ZERO;
		this.notAcceptedClaimsCount = BigInteger.ZERO;
	}

	/**
	 * Gets the value of the batchID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBatchID() {
		return batchID;
	}

	/**
	 * Sets the value of the batchID property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBatchID(String value) {
		this.batchID = value;
	}

	/**
	 * Gets the value of the totalClaimCount property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getTotalClaimCount() {
		return totalClaimCount;
	}

	/**
	 * Sets the value of the totalClaimCount property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setTotalClaimCount(BigInteger value) {
		this.totalClaimCount = value;
	}

	/**
	 * Gets the value of the totalClaimedAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getTotalClaimedAmount() {
		return totalClaimedAmount;
	}

	/**
	 * Sets the value of the totalClaimedAmount property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setTotalClaimedAmount(BigDecimal value) {
		this.totalClaimedAmount = value;
	}

	/**
	 * Gets the value of the batchReference property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getBatchReference() {
		return batchReference;
	}

	/**
	 * Sets the value of the batchReference property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setBatchReference(String value) {
		this.batchReference = value;
	}

	/**
	 * Gets the value of the sendDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getSendDate() {
		return sendDate;
	}

	/**
	 * Sets the value of the sendDate property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setSendDate(XMLGregorianCalendar value) {
		this.sendDate = value;
	}

	/**
	 * Gets the value of the notAcceptedClaimsCount property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getNotAcceptedClaimsCount() {
		return notAcceptedClaimsCount;
	}

	/**
	 * Sets the value of the notAcceptedClaimsCount property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setNotAcceptedClaimsCount(BigInteger value) {
		this.notAcceptedClaimsCount = value;
	}

	/**
	 * Gets the value of the notAcceptedClaimsList property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getNotAcceptedClaimsList() {
		return notAcceptedClaimsList;
	}

	/**
	 * Sets the value of the notAcceptedClaimsList property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setNotAcceptedClaimsList(String value) {
		this.notAcceptedClaimsList = value;
	}

	/**
	 * Gets the value of the notAcceptedClaimsAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getNotAcceptedClaimsAmount() {
		return notAcceptedClaimsAmount;
	}

	/**
	 * Sets the value of the notAcceptedClaimsAmount property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setNotAcceptedClaimsAmount(BigDecimal value) {
		this.notAcceptedClaimsAmount = value;
	}

	/**
	 * Gets the value of the acceptedClaimsCount property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getAcceptedClaimsCount() {
		return acceptedClaimsCount;
	}

	/**
	 * Sets the value of the acceptedClaimsCount property.
	 * 
	 * @param value allowed object is {@link BigInteger }
	 * 
	 */
	public void setAcceptedClaimsCount(BigInteger value) {
		this.acceptedClaimsCount = value;
	}

	/**
	 * Gets the value of the acceptedClaimsAmount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getAcceptedClaimsAmount() {
		return acceptedClaimsAmount;
	}

	/**
	 * Sets the value of the acceptedClaimsAmount property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setAcceptedClaimsAmount(BigDecimal value) {
		this.acceptedClaimsAmount = value;
	}

	/**
	 * Gets the value of the totalVATamount property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getTotalVATamount() {
		return totalVATamount;
	}

	/**
	 * Sets the value of the totalVATamount property.
	 * 
	 * @param value allowed object is {@link BigDecimal }
	 * 
	 */
	public void setTotalVATamount(BigDecimal value) {
		this.totalVATamount = value;
	}
	
	/**
	 * Gets the value of the billingPeriodFrom property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getBillingPeriodFrom() {
		return billingPeriodFrom;
	}

	/**
	 * Sets the value of the billingPeriodFrom property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setBillingPeriodFrom(XMLGregorianCalendar value) {
		this.billingPeriodFrom = value;
	}
	
	/**
	 * Gets the value of the billingPeriodTo property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getBillingPeriodTo() {
		return billingPeriodTo;
	}

	/**
	 * Sets the value of the billingPeriodTo property.
	 * 
	 * @param value allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setBillingPeriodTo(XMLGregorianCalendar value) {
		this.billingPeriodTo = value;
	}

}
