//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.waseel.com/wsdl/primary/wschema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.waseel.eligibility.client.portal.model;
