//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for physicianCategoryST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="physicianCategoryST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GENERAL PRACTICE"/&gt;
 *     &lt;enumeration value="SPECIALIST"/&gt;
 *     &lt;enumeration value="CONSULTANT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "physicianCategoryST")
@XmlEnum
public enum PhysicianCategoryST {

    @XmlEnumValue("GENERAL PRACTICE")
    GENERAL_PRACTICE("GENERAL PRACTICE"),
    SPECIALIST("SPECIALIST"),
    CONSULTANT("CONSULTANT");
    private final String value;

    PhysicianCategoryST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PhysicianCategoryST fromValue(String v) {
        for (PhysicianCategoryST c: PhysicianCategoryST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
