//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.17 at 03:12:46 PM AST 
//


package com.waseel.eligibility.client.portal.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statusCodeST.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="statusCodeST"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="VALID"/&gt;
 *     &lt;enumeration value="INVALID"/&gt;
 *     &lt;enumeration value="ELIGIBLE"/&gt;
 *     &lt;enumeration value="INELIGIBLE"/&gt;
 *     &lt;enumeration value="APPROVED"/&gt;
 *     &lt;enumeration value="REJECTED"/&gt;
 *     &lt;enumeration value="PARTIALLY APPROVED"/&gt;
 *     &lt;enumeration value="LIMIT APPROVED"/&gt;
 *     &lt;enumeration value="CONDITIONALLY APPROVED"/&gt;
 *     &lt;enumeration value="PENDING"/&gt;
 *     &lt;enumeration value="CANCELLED"/&gt;
 *     &lt;enumeration value="REFERRED"/&gt;
 *     &lt;enumeration value="FURTHER DETAILS REQUIRED"/&gt;
 *     &lt;enumeration value="UNDER PROCESS"/&gt;
 *     &lt;enumeration value="SETTLED"/&gt;
 *     &lt;enumeration value="PAID"/&gt;
 *     &lt;enumeration value="PARTIALLY PAID"/&gt;
 *     &lt;enumeration value="OUTSTANDING"/&gt;
 *     &lt;enumeration value="RETURNED"/&gt;
 *     &lt;enumeration value="DUPLICATE"/&gt;
 *     &lt;enumeration value="DISPENSED"/&gt;
 *     &lt;enumeration value="PARTIALLY DISPENSED"/&gt;
 *     &lt;enumeration value="NOT DISPENSED"/&gt;
 *     &lt;enumeration value="No Approval Required"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "statusCodeST")
@XmlEnum
public enum StatusCodeST {

    VALID("VALID"),
    INVALID("INVALID"),
    ELIGIBLE("ELIGIBLE"),
    INELIGIBLE("INELIGIBLE"),
    APPROVED("APPROVED"),
    REJECTED("REJECTED"),
    @XmlEnumValue("PARTIALLY APPROVED")
    PARTIALLY_APPROVED("PARTIALLY APPROVED"),
    @XmlEnumValue("LIMIT APPROVED")
    LIMIT_APPROVED("LIMIT APPROVED"),
    @XmlEnumValue("CONDITIONALLY APPROVED")
    CONDITIONALLY_APPROVED("CONDITIONALLY APPROVED"),
    PENDING("PENDING"),
    CANCELLED("CANCELLED"),
    REFERRED("REFERRED"),
    @XmlEnumValue("FURTHER DETAILS REQUIRED")
    FURTHER_DETAILS_REQUIRED("FURTHER DETAILS REQUIRED"),
    @XmlEnumValue("UNDER PROCESS")
    UNDER_PROCESS("UNDER PROCESS"),
    SETTLED("SETTLED"),
    PAID("PAID"),
    @XmlEnumValue("PARTIALLY PAID")
    PARTIALLY_PAID("PARTIALLY PAID"),
    OUTSTANDING("OUTSTANDING"),
    RETURNED("RETURNED"),
    DUPLICATE("DUPLICATE"),
    DISPENSED("DISPENSED"),
    @XmlEnumValue("PARTIALLY DISPENSED")
    PARTIALLY_DISPENSED("PARTIALLY DISPENSED"),
    @XmlEnumValue("NOT DISPENSED")
    NOT_DISPENSED("NOT DISPENSED"),
    @XmlEnumValue("No Approval Required")
    NO_APPROVAL_REQUIRED("No Approval Required");
    private final String value;

    StatusCodeST(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StatusCodeST fromValue(String v) {
        for (StatusCodeST c: StatusCodeST.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
