apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdb-validation-service-stg-deployment
  namespace: pbm-stg
  labels:
    app: fdb-validation-service-stg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdb-validation-service-stg-deployment
  template:
    metadata:
      labels:
        app: fdb-validation-service-stg-deployment
    spec:
      containers:
        - name: fdb-validation-service-stg-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-stg/fdb-validation-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: MDSS_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MDSS_USERNAME
          - name: MDSS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MDSS_PASSWORD
          - name: MEDK_FRAMWORK_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MEDK_FRAMWORK_USERNAME
          - name: MEDK_FRAMWORK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MEDK_FRAMWORK_PASSWORD
          - name: MEDK_FDB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MEDK_FDB_USERNAME
          - name: MEDK_FDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MEDK_FDB_PASSWORD
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
          resources: {}
      imagePullSecrets:
        - name: waseel-docker-registry-cred
