#---------------------------------
#DataBase Configuration
#-----------------------------------
spring.datasource.mdss.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/wallet/
spring.datasource.mdss.username=${MDSS_USERNAME}
spring.datasource.mdss.password=${MDSS_PASSWORD}
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=1
spring.datasource.mdss.maximumPoolSize=1

spring.datasource.businessrules.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/wallet/
spring.datasource.businessrules.username=${PBM_BUSINESS_RULES_USERNAME}
spring.datasource.businessrules.password=${PBM_BUSINESS_RULES_PASSWORD}
spring.datasource.businessrules.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.businessrules.connectionTimeout=3600000
spring.datasource.businessrules.idleTimeout=600000
spring.datasource.businessrules.minimumIdle=1
spring.datasource.businessrules.maximumPoolSize=1

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#---------------------------------
#Liquibase configuration
#-----------------------------------
spring.liquibase.enabled=true
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=PBM_business_rules

#--------------------------
#MongoDB
#--------------------------
spring.data.mongodb.database=PBM_STG
spring.data.mongodb.uri=mongodb://PBM_test:ENt4356PestM@tst-mongo-upgrade-tbd-1.devdbsn.wslvcn.oraclevcn.com:27017,test-mongo-upgrade-tbd.devdbsn.wslvcn.oraclevcn.com:27017/test?authSource=PBM&replicaSet=tst-mongo-01&maxPoolSize=400&maxIdleTimeMS=60000&readPreference=primary&appname=MongoDB%20Compass&ssl=false

pbmPayerApisServiceClient.url=http://pbm-payer-apis-service:8080/pbm-payer-apis-service