apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbm-authentication-service-prod-deployment
  namespace: pbm-prod
  labels:
    app: pbm-authentication-service-prod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pbm-authentication-service-prod-deployment
  template:
    metadata:
      labels:
        app: pbm-authentication-service-prod-deployment
    spec:
      nodeSelector:
        environment: pbm-prod
      containers:
        - name: pbm-authentication-service-prod-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-prod/pbm-authentication-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
