apiVersion: v1
kind: Service
metadata:
  name: pbm-authentication-service-prod-service
  namespace: pbm-prod
  labels:
    app: pbm-authentication-service-prod-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: pbm-authentication-service-prod-deployment
