#Logging Configuration
#-----------------------------------
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

client.tawuniya.url:https://webapisdev.tawuniya.com.sa:5556/gateway/tawnEprescription
clients.tawuniya.apiKey:441708b0-6dc4-420e-a07f-b512af5b1a9c
clients.tawuniya.senderCode:101
clients.tawuniya.receiverCode:102
clients.tawuniya.direction:REQUEST

client.mock.url:https://mock.waseel.com/rest/Tawuniya+Apis/1.2