apiVersion: apps/v1
kind: Deployment
metadata:
  name: payer-customization-service-stg-deployment
  namespace: pbm-stg
  labels:
    app: payer-customization-service-stg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payer-customization-service-stg-deployment
  template:
    metadata:
      labels:
        app: payer-customization-service-stg-deployment
    spec:
      containers:
        - name: payer-customization-service-stg-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-stg/payer-customization-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: MDSS_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MDSS_USERNAME
          - name: MDSS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MDSS_PASSWORD
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /payer-customization-service/actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
      imagePullSecrets:
        - name: waseel-docker-registry-cred
