--liquibase formatted sql

--changeset DssService:32


CREATE TABLE MDSS.CHRONIC_DZ_INFORMATION
(
  CHRONIC_DISEASES_ID    NUMBER Generated as Identity ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP) NOT NULL,
  CHRONIC_DISEASES_NAME  VARCHAR2(250 BYTE)     NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX MDSS.CHRONIC_DZ_INFORMATION_PK ON MDSS.CHRONIC_DZ_INFORMATION
(CHRONIC_DISEASES_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   20
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX MDSS.CHRONIC_DZ_INFORMATION_UK ON MDSS.CHRONIC_DZ_INFORMATION
(CHRONIC_DISEASES_ID, CHRONIC_DISEASES_NAME)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   20
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MDSS.CHRONIC_DZ_INFORMATION ADD (
  CONSTRAINT CHRONIC_DZ_INFORMATION_PK
  PRIMARY KEY
  (CHRONIC_DISEASES_ID)
  USING INDEX MDSS.CHRONIC_DZ_INFORMATION_PK
  ENABLE VALIDATE,
  CONSTRAINT CHRONIC_DZ_INFORMATION_UK
  UNIQUE (CHRONIC_DISEASES_ID, CHRONIC_DISEASES_NAME)
  USING INDEX MDSS.CHRONIC_DZ_INFORMATION_UK
  ENABLE VALIDATE);
