--liquibase formatted sql

--changeset DssService:34

CREATE TABLE MDSS.CHRONIC_DZ_DRUG_ASSOC
(
  CHRONIC_DZ_DRUG_ASSOC_ID   NUMBER Generated as Identity ( START WITH 21 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP) NOT NULL,
  CHRONIC_DISEASES_ID        NUMBER             NOT NULL,
  SERVICE_CODE               VARCHAR2(250 BYTE) NOT NULL,
  IS_ENABLED                 VARCHAR2(1 BYTE)   DEFAULT 1                     NOT NULL,
  LAST_UPDATE_DATE_AND_TIME  DATE               DEFAULT sysdate               NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX MDSS.CHRONIC_DZ_DRUG_ASSOC_PK ON MDSS.CHRONIC_DZ_DRUG_ASSOC
(CHRONIC_DZ_DRUG_ASSOC_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   20
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX MDSS.CHRONIC_DZ_DRUG_ASSOC_UK ON MDSS.CHRONIC_DZ_DRUG_ASSOC
(CHRONIC_DISEASES_ID, SERVICE_CODE)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   20
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MDSS.CHRONIC_DZ_DRUG_ASSOC ADD (
  CONSTRAINT CHRONIC_DZ_DRUG_ASSOC_PK
  PRIMARY KEY
  (CHRONIC_DZ_DRUG_ASSOC_ID)
  USING INDEX MDSS.CHRONIC_DZ_DRUG_ASSOC_PK
  ENABLE VALIDATE,
  CONSTRAINT CHRONIC_DZ_DRUG_ASSOC_UK
  UNIQUE (CHRONIC_DISEASES_ID, SERVICE_CODE)
  USING INDEX MDSS.CHRONIC_DZ_DRUG_ASSOC_UK
  ENABLE VALIDATE);

ALTER TABLE MDSS.CHRONIC_DZ_DRUG_ASSOC ADD (
  CONSTRAINT CHRONIC_DZ_DRUG_ASSOC_FK 
  FOREIGN KEY (CHRONIC_DISEASES_ID) 
  REFERENCES MDSS.CHRONIC_DZ_INFORMATION (CHRONIC_DISEASES_ID)
  ENABLE VALIDATE);
