--liquibase formatted sql

--changeset DssService:37


CREATE TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC
(
  MEMBER_CRO_DIAGNOSIS_ASSOC_ID  NUMBER Generated as Identity ( START WITH 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CYCLE CACHE 20 ORDER KEEP) NOT NULL,
  MEMBER_CHRONIC_DZ_ASSOC_ID     NUMBER         NOT NULL,
  DIAGNOSIS_CODE                 VARCHAR2(10 BYTE) NOT NULL,
  IS_ENABLED                     VARCHAR2(1 BYTE) DEFAULT 1 NOT NULL,
  LAST_UPDATE_DATE_AND_TIME      DATE           DEFAULT sysdate               NOT NULL
)
TABLESPACE DATA
PCTUSED    0
PCTFREE    10
INITRANS   10
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX MDSS.MEMBER_CHRONIC_DIAGNOSIS_AS_PK ON MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC
(MEMBER_CRO_DIAGNOSIS_ASSOC_ID)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   20
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX MDSS.MEMBER_CHRONIC_DIAGNOSIS_AS_UK ON MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC
(MEMBER_CHRONIC_DZ_ASSOC_ID, DIAGNOSIS_CODE)
LOGGING
TABLESPACE DATA
PCTFREE    10
INITRANS   20
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC ADD (
  CONSTRAINT MEMBER_CHRONIC_DIAGNOSIS_AS_PK
  PRIMARY KEY
  (MEMBER_CRO_DIAGNOSIS_ASSOC_ID)
  USING INDEX MDSS.MEMBER_CHRONIC_DIAGNOSIS_AS_PK
  ENABLE VALIDATE,
  CONSTRAINT MEMBER_CHRONIC_DIAGNOSIS_AS_UK
  UNIQUE (MEMBER_CHRONIC_DZ_ASSOC_ID, DIAGNOSIS_CODE)
  USING INDEX MDSS.MEMBER_CHRONIC_DIAGNOSIS_AS_UK
  ENABLE VALIDATE);

ALTER TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC ADD (
  CONSTRAINT MEMBER_CHRONIC_DIAGNOSIS_AS_FK 
  FOREIGN KEY (MEMBER_CHRONIC_DZ_ASSOC_ID) 
  REFERENCES MDSS.MEMBER_CHRONIC_DZ_ASSOC (MEMBER_CHRONIC_DZ_ASSOC_ID)
  ENABLE VALIDATE);
