--liquibase formatted sql

--changeset DSS:42

CREATE INDEX MDSS.CHRONIC_DZ_DIAGNOSIS_ASSOC_FU ON MDSS.CHRONIC_DZ_DIAGNOSIS_ASSOC
(DIAGNOSIS_CODE, IS_ENABLED);

CREATE INDEX MDSS.MEMBER_CHRONIC_DZ_ASSOC_FU ON MDSS.MEMBER_CHRONIC_DZ_ASSOC
(MEMBER_ID, IS_ENABLED);

