--liquibase formatted sql

--changeset DssService:49

CREATE TABLE MDSS.PAYER_FEATURES_CONFIGURATION
(
  PAYER_ID                    VARCHAR2(20)      NOT NULL,
  FEATURE_NAME                VARCHAR2(100)     NOT NULL,
  IS_ENABLED                  VARCHAR2(1)       NOT NULL,
  LAST_UPDATED_DATE_AND_TIME  DATE              NOT NULL
);

ALTER TABLE MDSS.PAYER_FEATURES_CONFIGURATION ADD (
  CONSTRAINT PAYER_FEATURE_CONFIG_PK
  PRIMARY KEY
  (PAYER_ID, FEATURE_NAME)
  ENABLE VALIDATE);