--liquibase formatted sql

--changeset DssService:50

Drop TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC;

CREATE TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC 
(
  MEMBER_CHRONIC_DZ_ASSOC_ID     NUMBER         NOT NULL,
  DIAGNOSIS_CODE                 VARCHAR2(10 BYTE) NOT NULL,
  IS_ENABLED                     VARCHAR2(1 BYTE) DEFAULT 1 NOT NULL,
  LAST_UPDATE_DATE_AND_TIME      DATE           DEFAULT sysdate               NOT NULL
);


ALTER TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC ADD (
  CONSTRAINT MEMBER_CHRONIC_DIAGNOSIS_AS_PK
  PRIMARY KEY
  (MEMBER_CHRONIC_DZ_ASSOC_ID, DIAGNOSIS_CODE)
  );

ALTER TABLE MDSS.MEMBER_CHRONIC_DIAGNOSIS_ASSOC ADD (
  CONSTRAINT MEMBER_CHRONIC_DIAGNOSIS_AS_FK 
  FOREIGN KEY (MEMBER_CHRONIC_DZ_ASSOC_ID) 
  REFERENCES MDSS.MEMBER_CHRONIC_DZ_ASSOC (MEMBER_CHRONIC_DZ_ASSOC_ID)
  ENABLE VALIDATE);