package com.waseel.pbmnotificationservice.service.email;

import org.springframework.stereotype.Service;

@Service
public class EmailMessageBodyService {

	public String getHtmlContentOfEmail(String memberName,String providerName,
			String ePrescriptionReferenceNumber,String patientUrl) {
		String patientUrlForView = patientUrl.getBytes().length > 48 ? patientUrl.substring(0, 47) + "..."
				: patientUrl;
		return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"font-family:arial, 'helvetica neue', helvetica, sans-serif\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"UTF-8\">\r\n"
				+ "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "  <meta content=\"telephone=no\" name=\"format-detection\">\r\n"
				+ "  <title>PBM Email</title><!--[if (mso 16)]>\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "    a {text-decoration: none;}\r\n"
				+ "    </style>\r\n"
				+ "    <![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "    <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG></o:AllowPNG>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "    </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]--><!--[if !mso]><!-- -->\r\n"
				+ "  <link href=\"https://fonts.googleapis.com/css?family=Poppins:400,500,700\" rel=\"stylesheet\"><!--<![endif]-->\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "    #outlook a {\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .es-button {\r\n"
				+ "      mso-style-priority: 100 !important;\r\n"
				+ "      text-decoration: none !important;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    a[x-apple-data-detectors] {\r\n"
				+ "      color: inherit !important;\r\n"
				+ "      text-decoration: none !important;\r\n"
				+ "      font-size: inherit !important;\r\n"
				+ "      font-family: inherit !important;\r\n"
				+ "      font-weight: inherit !important;\r\n"
				+ "      line-height: inherit !important;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .es-desk-hidden {\r\n"
				+ "      display: none;\r\n"
				+ "      float: left;\r\n"
				+ "      overflow: hidden;\r\n"
				+ "      width: 0;\r\n"
				+ "      max-height: 0;\r\n"
				+ "      line-height: 0;\r\n"
				+ "      mso-hide: all;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media only screen and (max-width:600px) {\r\n"
				+ "      .p-0 {\r\n"
				+ "        padding: 0 !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .header-block {\r\n"
				+ "        padding-top: 24px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .responsive-padding {\r\n"
				+ "        padding-left: 16px !important;\r\n"
				+ "        padding-right: 16px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      p,\r\n"
				+ "      ul li,\r\n"
				+ "      ol li,\r\n"
				+ "      a {\r\n"
				+ "        line-height: 150% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h1,\r\n"
				+ "      h2,\r\n"
				+ "      h3,\r\n"
				+ "      h1 a,\r\n"
				+ "      h2 a,\r\n"
				+ "      h3 a {\r\n"
				+ "        line-height: 120%\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h1 {\r\n"
				+ "        font-size: 28px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h2 {\r\n"
				+ "        font-size: 20px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h3 {\r\n"
				+ "        font-size: 18px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body h1 a,\r\n"
				+ "      .es-content-body h1 a,\r\n"
				+ "      .es-footer-body h1 a {\r\n"
				+ "        font-size: 28px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body h2 a,\r\n"
				+ "      .es-content-body h2 a,\r\n"
				+ "      .es-footer-body h2 a {\r\n"
				+ "        font-size: 20px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body h3 a,\r\n"
				+ "      .es-content-body h3 a,\r\n"
				+ "      .es-footer-body h3 a {\r\n"
				+ "        font-size: 18px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-menu td a {\r\n"
				+ "        font-size: 14px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body p,\r\n"
				+ "      .es-header-body ul li,\r\n"
				+ "      .es-header-body ol li,\r\n"
				+ "      .es-header-body a {\r\n"
				+ "        font-size: 24px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-content-body p,\r\n"
				+ "      .es-content-body ul li,\r\n"
				+ "      .es-content-body ol li,\r\n"
				+ "      .es-content-body a {\r\n"
				+ "        font-size: 14px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-footer-body p,\r\n"
				+ "      .es-footer-body ul li,\r\n"
				+ "      .es-footer-body ol li,\r\n"
				+ "      .es-footer-body a {\r\n"
				+ "        font-size: 14px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-infoblock p,\r\n"
				+ "      .es-infoblock ul li,\r\n"
				+ "      .es-infoblock ol li,\r\n"
				+ "      .es-infoblock a {\r\n"
				+ "        font-size: 12px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      *[class=\"gmail-fix\"] {\r\n"
				+ "        display: none !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-c,\r\n"
				+ "      .es-m-txt-c h1,\r\n"
				+ "      .es-m-txt-c h2,\r\n"
				+ "      .es-m-txt-c h3 {\r\n"
				+ "        text-align: center !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-r,\r\n"
				+ "      .es-m-txt-r h1,\r\n"
				+ "      .es-m-txt-r h2,\r\n"
				+ "      .es-m-txt-r h3 {\r\n"
				+ "        text-align: right !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-l,\r\n"
				+ "      .es-m-txt-l h1,\r\n"
				+ "      .es-m-txt-l h2,\r\n"
				+ "      .es-m-txt-l h3 {\r\n"
				+ "        text-align: left !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-r img,\r\n"
				+ "      .es-m-txt-c img,\r\n"
				+ "      .es-m-txt-l img {\r\n"
				+ "        display: inline !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-button-border {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      a.es-button,\r\n"
				+ "      button.es-button {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-adaptive table,\r\n"
				+ "      .es-left,\r\n"
				+ "      .es-right {\r\n"
				+ "        width: 100% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-content table,\r\n"
				+ "      .es-header table,\r\n"
				+ "      .es-footer table,\r\n"
				+ "      .es-content,\r\n"
				+ "      .es-footer,\r\n"
				+ "      .es-header {\r\n"
				+ "        width: 100% !important;\r\n"
				+ "        max-width: 600px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-adapt-td {\r\n"
				+ "        display: block !important;\r\n"
				+ "        width: 100% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .adapt-img {\r\n"
				+ "        width: 100% !important;\r\n"
				+ "        height: auto !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0 {\r\n"
				+ "        padding: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0r {\r\n"
				+ "        padding-right: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0l {\r\n"
				+ "        padding-left: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0t {\r\n"
				+ "        padding-top: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0b {\r\n"
				+ "        padding-bottom: 0 !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p20b {\r\n"
				+ "        padding-bottom: 20px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-mobile-hidden,\r\n"
				+ "      .es-hidden {\r\n"
				+ "        display: none !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      tr.es-desk-hidden,\r\n"
				+ "      td.es-desk-hidden,\r\n"
				+ "      table.es-desk-hidden {\r\n"
				+ "        width: auto !important;\r\n"
				+ "        overflow: visible !important;\r\n"
				+ "        float: none !important;\r\n"
				+ "        max-height: inherit !important;\r\n"
				+ "        line-height: inherit !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      tr.es-desk-hidden {\r\n"
				+ "        display: table-row !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-desk-hidden {\r\n"
				+ "        display: table !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      td.es-desk-menu-hidden {\r\n"
				+ "        display: table-cell !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-menu td {\r\n"
				+ "        width: 1% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-table-not-adapt,\r\n"
				+ "      .esd-block-html table {\r\n"
				+ "        width: auto !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-social {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-social td {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-desk-hidden {\r\n"
				+ "        display: table-row !important;\r\n"
				+ "        width: auto !important;\r\n"
				+ "        overflow: visible !important;\r\n"
				+ "        max-height: inherit !important\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\r\n"
				+ "  <div class=\"es-wrapper-color\" style=\"background-color:#F6F6F6\"><!--[if gte mso 9]>\r\n"
				+ "			<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
				+ "				<v:fill type=\"tile\" color=\"#f6f6f6\"></v:fill>\r\n"
				+ "			</v:background>\r\n"
				+ "		<![endif]-->\r\n"
				+ "    <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\r\n"
				+ "      style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td valign=\"top\" class=\"p-0\" style=\"padding:0;Margin:0;padding-top: 40px;padding-bottom: 40px;\">\r\n"
				+ "          <table class=\" es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\r\n"
				+ "            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\r\n"
				+ "            <tr>\r\n"
				+ "              <td align=\"center\" bgcolor=\"#f6f6f6\" style=\"padding: 0;Margin:0;background-color:#f6f6f6;\">\r\n"
				+ "                <table class=\" es-content-body\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\"\r\n"
				+ "                  style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px\">\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td align=\"left\" style=\"padding:0;Margin:0;padding-left:32px;padding-right:32px;padding-top:40px\" class=\"responsive-padding header-block\">\r\n"
				+ "                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:540px\">\r\n"
				+ "                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\"\r\n"
				+ "                              style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0;font-size:0px\"><a target=\"_blank\" href=\"https://pbm-admin.waseel.com\"\r\n"
				+ "                                    style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#0373FF;font-size:16px\"><img\r\n"
				+ "                                      src=\"https://i.ibb.co/bgT0rYF/pbm-logo.png\" alt style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\" height=\"48\"></a>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0;padding-bottom:24px;padding-top: 48px;\">\r\n"
				+ "                                  <p\r\n"
				+ "                                    style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#222222;font-size:16px\">\r\n"
				+ "                                    Hi "
				+ memberName
				+ ",<br><br>We have received your prescription(Ref. No. "
				+ ePrescriptionReferenceNumber
				+ ")"
				+ " created/updated by "
				+ providerName
				+ ". You can check it’s status and details\r\n"
				+ "                                    by clicking on below given button.</p>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td align=\"left\" style=\"padding:0;Margin:0;padding-left:32px;padding-right:32px;padding-bottom:32px\" class=\"responsive-padding\">\r\n"
				+ "                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:540px\">\r\n"
				+ "                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\"\r\n"
				+ "                              style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0\"><!--[if mso]>"
				+ "<a href=\""+patientUrl + "\"" 
				+ " target=\"_blank\" hidden>\r\n"
				+ "	<v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\""
				+ " esdevVmlButton href=\"" +patientUrl + "\"\r\n"
				+ "                style=\"height:36px; v-text-anchor:middle; width:93px\" arcsize=\"22%\" stroke=\"f\"  fillcolor=\"#0373FF\">\r\n"
				+ "		<w:anchorlock></w:anchorlock>\r\n"
				+ "		<center style='color:#ffffff; font-family:Poppins, \"helvetica neue\", helvetica, arial, sans-serif; font-size:12px; font-weight:400; line-height:12px;  mso-text-raise:1px'>View Prescription</center>\r\n"
				+ "	</v:roundrect></a>\r\n"
				+ "<![endif]--><!--[if !mso]><!-- --><span class=\"msohide es-button-border\"\r\n"
				+ "                                    style=\"border-style:solid;border-color:#2CB543;background:#0373FF;border-width:0px;display:inline-block;border-radius:8px;width:auto;mso-hide:all\"><a\r\n"
				+ "                                      href=\""
				+ patientUrl + "\"" 
				+ " class=\"es-button\" target=\"_blank\"\r\n"
				+ "                                      style=\"mso-style-priority:100 !important;text-decoration:none;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;color:#FFFFFF;font-size:14px;display:inline-block;background:#0373FF;border-radius:8px;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;font-weight:normal;font-style:normal;line-height:17px;width:auto;text-align:center;padding:10px 24px 10px 24px;border-color:#0373FF\">View\r\n"
				+ "                                      Prescription</a></span><!--<![endif]--></td>\r\n"
				+ "                              </tr>\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0;padding-top:24px\">\r\n"
				+ "                                  <p\r\n"
				+ "                                    style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#222222;font-size:16px\">\r\n"
				+ "                                    If you’re having trouble with the button above, then you may click on the below URL.<br><br><a target=\"_blank\"\r\n"
				+ "                                      href=\""
				+ patientUrl+"\"\r\n"
				+ "                                      style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#0373FF;font-size:16px;word-break:break-all\">"
				+ patientUrlForView
				+ "</a><br><br>Thanks,<br>Team\r\n"
				+ "                                    Waseel PBM<br><br><span style=\"color: #757575;\">Note: This is an auto generated email, please do not\r\n"
				+ "                                      reply.</span></p>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </table>\r\n"
				+ "              </td>\r\n"
				+ "            </tr>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"es-footer\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\r\n"
				+ "            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\r\n"
				+ "            <tr>\r\n"
				+ "              <td align=\"center\" bgcolor=\"#f6f6f6\" style=\"padding:0;Margin:0;background-color:#f6f6f6\">\r\n"
				+ "                <table class=\"es-footer-body\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\"\r\n"
				+ "                  style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#0373FF;width:600px\">\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td align=\"left\" style=\"Margin:0;padding-top:16px;padding-bottom:16px;padding-left:32px;padding-right:32px\" class=\"responsive-padding\">\r\n"
				+ "                      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td align=\"left\" style=\"padding:0;Margin:0;width:540px\">\r\n"
				+ "                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\"\r\n"
				+ "                              style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"center\" style=\"padding:0;Margin:0\">\r\n"
				+ "                                  <p\r\n"
				+ "                                    style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#FFFFFF;font-size:16px\">\r\n"
				+ "                                    ©Copyright 2023. All rights reserved.<br>Waseel PBM</p>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </table>\r\n"
				+ "              </td>\r\n"
				+ "            </tr>\r\n"
				+ "          </table>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}

	public String getHtmlContentOfEmailForCancellation(String memberName,String providerName,
			String ePrescriptionReferenceNumber) {
		return "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
				+ "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" style=\"font-family:arial, 'helvetica neue', helvetica, sans-serif\">\r\n"
				+ "\r\n"
				+ "<head>\r\n"
				+ "  <meta charset=\"UTF-8\">\r\n"
				+ "  <meta content=\"width=device-width, initial-scale=1\" name=\"viewport\">\r\n"
				+ "  <meta name=\"x-apple-disable-message-reformatting\">\r\n"
				+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "  <meta content=\"telephone=no\" name=\"format-detection\">\r\n"
				+ "  <title>PBM Email</title><!--[if (mso 16)]>\r\n"
				+ "    <style type=\"text/css\">\r\n"
				+ "    a {text-decoration: none;}\r\n"
				+ "    </style>\r\n"
				+ "    <![endif]--><!--[if gte mso 9]><style>sup { font-size: 100% !important; }</style><![endif]--><!--[if gte mso 9]>\r\n"
				+ "<xml>\r\n"
				+ "    <o:OfficeDocumentSettings>\r\n"
				+ "    <o:AllowPNG></o:AllowPNG>\r\n"
				+ "    <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
				+ "    </o:OfficeDocumentSettings>\r\n"
				+ "</xml>\r\n"
				+ "<![endif]--><!--[if !mso]><!-- -->\r\n"
				+ "  <link href=\"https://fonts.googleapis.com/css?family=Poppins:400,500,700\" rel=\"stylesheet\"><!--<![endif]-->\r\n"
				+ "  <style type=\"text/css\">\r\n"
				+ "    #outlook a {\r\n"
				+ "      padding: 0;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .es-button {\r\n"
				+ "      mso-style-priority: 100 !important;\r\n"
				+ "      text-decoration: none !important;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    a[x-apple-data-detectors] {\r\n"
				+ "      color: inherit !important;\r\n"
				+ "      text-decoration: none !important;\r\n"
				+ "      font-size: inherit !important;\r\n"
				+ "      font-family: inherit !important;\r\n"
				+ "      font-weight: inherit !important;\r\n"
				+ "      line-height: inherit !important;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    .es-desk-hidden {\r\n"
				+ "      display: none;\r\n"
				+ "      float: left;\r\n"
				+ "      overflow: hidden;\r\n"
				+ "      width: 0;\r\n"
				+ "      max-height: 0;\r\n"
				+ "      line-height: 0;\r\n"
				+ "      mso-hide: all;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "    @media only screen and (max-width:600px) {\r\n"
				+ "      .p-0 {\r\n"
				+ "        padding: 0 !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .header-block {\r\n"
				+ "        padding-top: 24px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .responsive-padding {\r\n"
				+ "        padding-left: 16px !important;\r\n"
				+ "        padding-right: 16px !important;\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      p,\r\n"
				+ "      ul li,\r\n"
				+ "      ol li,\r\n"
				+ "      a {\r\n"
				+ "        line-height: 150% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h1,\r\n"
				+ "      h2,\r\n"
				+ "      h3,\r\n"
				+ "      h1 a,\r\n"
				+ "      h2 a,\r\n"
				+ "      h3 a {\r\n"
				+ "        line-height: 120%\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h1 {\r\n"
				+ "        font-size: 28px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h2 {\r\n"
				+ "        font-size: 20px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      h3 {\r\n"
				+ "        font-size: 18px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body h1 a,\r\n"
				+ "      .es-content-body h1 a,\r\n"
				+ "      .es-footer-body h1 a {\r\n"
				+ "        font-size: 28px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body h2 a,\r\n"
				+ "      .es-content-body h2 a,\r\n"
				+ "      .es-footer-body h2 a {\r\n"
				+ "        font-size: 20px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body h3 a,\r\n"
				+ "      .es-content-body h3 a,\r\n"
				+ "      .es-footer-body h3 a {\r\n"
				+ "        font-size: 18px !important;\r\n"
				+ "        text-align: left\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-menu td a {\r\n"
				+ "        font-size: 14px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-header-body p,\r\n"
				+ "      .es-header-body ul li,\r\n"
				+ "      .es-header-body ol li,\r\n"
				+ "      .es-header-body a {\r\n"
				+ "        font-size: 24px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-content-body p,\r\n"
				+ "      .es-content-body ul li,\r\n"
				+ "      .es-content-body ol li,\r\n"
				+ "      .es-content-body a {\r\n"
				+ "        font-size: 14px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-footer-body p,\r\n"
				+ "      .es-footer-body ul li,\r\n"
				+ "      .es-footer-body ol li,\r\n"
				+ "      .es-footer-body a {\r\n"
				+ "        font-size: 14px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-infoblock p,\r\n"
				+ "      .es-infoblock ul li,\r\n"
				+ "      .es-infoblock ol li,\r\n"
				+ "      .es-infoblock a {\r\n"
				+ "        font-size: 12px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      *[class=\"gmail-fix\"] {\r\n"
				+ "        display: none !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-c,\r\n"
				+ "      .es-m-txt-c h1,\r\n"
				+ "      .es-m-txt-c h2,\r\n"
				+ "      .es-m-txt-c h3 {\r\n"
				+ "        text-align: center !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-r,\r\n"
				+ "      .es-m-txt-r h1,\r\n"
				+ "      .es-m-txt-r h2,\r\n"
				+ "      .es-m-txt-r h3 {\r\n"
				+ "        text-align: right !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-l,\r\n"
				+ "      .es-m-txt-l h1,\r\n"
				+ "      .es-m-txt-l h2,\r\n"
				+ "      .es-m-txt-l h3 {\r\n"
				+ "        text-align: left !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-txt-r img,\r\n"
				+ "      .es-m-txt-c img,\r\n"
				+ "      .es-m-txt-l img {\r\n"
				+ "        display: inline !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-button-border {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      a.es-button,\r\n"
				+ "      button.es-button {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-adaptive table,\r\n"
				+ "      .es-left,\r\n"
				+ "      .es-right {\r\n"
				+ "        width: 100% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-content table,\r\n"
				+ "      .es-header table,\r\n"
				+ "      .es-footer table,\r\n"
				+ "      .es-content,\r\n"
				+ "      .es-footer,\r\n"
				+ "      .es-header {\r\n"
				+ "        width: 100% !important;\r\n"
				+ "        max-width: 600px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-adapt-td {\r\n"
				+ "        display: block !important;\r\n"
				+ "        width: 100% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .adapt-img {\r\n"
				+ "        width: 100% !important;\r\n"
				+ "        height: auto !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0 {\r\n"
				+ "        padding: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0r {\r\n"
				+ "        padding-right: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0l {\r\n"
				+ "        padding-left: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0t {\r\n"
				+ "        padding-top: 0px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p0b {\r\n"
				+ "        padding-bottom: 0 !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-m-p20b {\r\n"
				+ "        padding-bottom: 20px !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-mobile-hidden,\r\n"
				+ "      .es-hidden {\r\n"
				+ "        display: none !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      tr.es-desk-hidden,\r\n"
				+ "      td.es-desk-hidden,\r\n"
				+ "      table.es-desk-hidden {\r\n"
				+ "        width: auto !important;\r\n"
				+ "        overflow: visible !important;\r\n"
				+ "        float: none !important;\r\n"
				+ "        max-height: inherit !important;\r\n"
				+ "        line-height: inherit !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      tr.es-desk-hidden {\r\n"
				+ "        display: table-row !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-desk-hidden {\r\n"
				+ "        display: table !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      td.es-desk-menu-hidden {\r\n"
				+ "        display: table-cell !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-menu td {\r\n"
				+ "        width: 1% !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-table-not-adapt,\r\n"
				+ "      .esd-block-html table {\r\n"
				+ "        width: auto !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-social {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      table.es-social td {\r\n"
				+ "        display: inline-block !important\r\n"
				+ "      }\r\n"
				+ "\r\n"
				+ "      .es-desk-hidden {\r\n"
				+ "        display: table-row !important;\r\n"
				+ "        width: auto !important;\r\n"
				+ "        overflow: visible !important;\r\n"
				+ "        max-height: inherit !important\r\n"
				+ "      }\r\n"
				+ "    }\r\n"
				+ "  </style>\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body style=\"width:100%;font-family:arial, 'helvetica neue', helvetica, sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;padding:0;Margin:0\">\r\n"
				+ "  <div class=\"es-wrapper-color\" style=\"background-color:#F6F6F6\"><!--[if gte mso 9]>\r\n"
				+ "			<v:background xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"t\">\r\n"
				+ "				<v:fill type=\"tile\" color=\"#f6f6f6\"></v:fill>\r\n"
				+ "			</v:background>\r\n"
				+ "		<![endif]-->\r\n"
				+ "    <table class=\"es-wrapper\" width=\"100%\" cellspacing=\"0\" cellpadding=\"0\"\r\n"
				+ "      style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;padding:0;Margin:0;width:100%;height:100%;background-repeat:repeat;background-position:center top;background-color:#F6F6F6\">\r\n"
				+ "      <tr>\r\n"
				+ "        <td valign=\"top\" class=\"p-0\" style=\"padding:0;Margin:0;padding-top: 40px;padding-bottom: 40px;\">\r\n"
				+ "          <table class=\" es-content\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\r\n"
				+ "            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%\">\r\n"
				+ "            <tr>\r\n"
				+ "              <td align=\"center\" bgcolor=\"#f6f6f6\" style=\"padding: 0;Margin:0;background-color:#f6f6f6;\">\r\n"
				+ "                <table class=\" es-content-body\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\"\r\n"
				+ "                  style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#FFFFFF;width:600px\">\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td align=\"left\" style=\"padding:0;Margin:0;padding-left:32px;padding-right:32px;padding-top:40px\" class=\"responsive-padding header-block\">\r\n"
				+ "                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:540px\">\r\n"
				+ "                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\"\r\n"
				+ "                              style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0;font-size:0px\"><a target=\"_blank\" href=\"https://pbm-admin.waseel.com\"\r\n"
				+ "                                    style=\"-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;text-decoration:underline;color:#0373FF;font-size:16px\"><img\r\n"
				+ "                                      src=\"https://i.ibb.co/bgT0rYF/pbm-logo.png\" alt style=\"display:block;border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic\" height=\"48\"></a>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0;padding-bottom:0;padding-top: 48px;\">\r\n"
				+ "                                  <p\r\n"
				+ "                                    style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#222222;font-size:16px\">\r\n"
				+ "                                    Hi "
				+ memberName
				+ ",<br><br>We have received your prescription(Ref. No."
				+ ePrescriptionReferenceNumber
				+ " ) created/updated by "
				+ providerName
				+ ". But this is just to inform you that\r\n"
				+ "                                    now they have cancelled it.</p>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td align=\"left\" style=\"padding:0;Margin:0;padding-left:32px;padding-right:32px;padding-bottom:32px\" class=\"responsive-padding\">\r\n"
				+ "                      <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td valign=\"top\" align=\"center\" style=\"padding:0;Margin:0;width:540px\">\r\n"
				+ "                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\"\r\n"
				+ "                              style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"left\" style=\"padding:0;Margin:0;padding-top:24px\">\r\n"
				+ "                                  <p\r\n"
				+ "                                    style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#222222;font-size:16px\">\r\n"
				+ "                                    Thanks,<br>Team\r\n"
				+ "                                    Waseel PBM<br><br><span style=\"color: #757575;\">Note: This is an auto generated email, please do not\r\n"
				+ "                                      reply.</span>\r\n"
				+ "                                  </p>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </table>\r\n"
				+ "              </td>\r\n"
				+ "            </tr>\r\n"
				+ "          </table>\r\n"
				+ "          <table class=\"es-footer\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\"\r\n"
				+ "            style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;table-layout:fixed !important;width:100%;background-color:transparent;background-repeat:repeat;background-position:center top\">\r\n"
				+ "            <tr>\r\n"
				+ "              <td align=\"center\" bgcolor=\"#f6f6f6\" style=\"padding:0;Margin:0;background-color:#f6f6f6\">\r\n"
				+ "                <table class=\"es-footer-body\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\" align=\"center\"\r\n"
				+ "                  style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px;background-color:#0373FF;width:600px\">\r\n"
				+ "                  <tr>\r\n"
				+ "                    <td align=\"left\" style=\"Margin:0;padding-top:16px;padding-bottom:16px;padding-left:32px;padding-right:32px\" class=\"responsive-padding\">\r\n"
				+ "                      <table cellspacing=\"0\" cellpadding=\"0\" width=\"100%\" style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                        <tr>\r\n"
				+ "                          <td align=\"left\" style=\"padding:0;Margin:0;width:540px\">\r\n"
				+ "                            <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" role=\"presentation\"\r\n"
				+ "                              style=\"mso-table-lspace:0pt;mso-table-rspace:0pt;border-collapse:collapse;border-spacing:0px\">\r\n"
				+ "                              <tr>\r\n"
				+ "                                <td align=\"center\" style=\"padding:0;Margin:0\">\r\n"
				+ "                                  <p\r\n"
				+ "                                    style=\"Margin:0;-webkit-text-size-adjust:none;-ms-text-size-adjust:none;mso-line-height-rule:exactly;font-family:Poppins, 'helvetica neue', helvetica, arial, sans-serif;line-height:24px;color:#FFFFFF;font-size:16px\">\r\n"
				+ "                                    ©Copyright 2023. All rights reserved.<br>Waseel PBM</p>\r\n"
				+ "                                </td>\r\n"
				+ "                              </tr>\r\n"
				+ "                            </table>\r\n"
				+ "                          </td>\r\n"
				+ "                        </tr>\r\n"
				+ "                      </table>\r\n"
				+ "                    </td>\r\n"
				+ "                  </tr>\r\n"
				+ "                </table>\r\n"
				+ "              </td>\r\n"
				+ "            </tr>\r\n"
				+ "          </table>\r\n"
				+ "        </td>\r\n"
				+ "      </tr>\r\n"
				+ "    </table>\r\n"
				+ "  </div>\r\n"
				+ "</body>\r\n"
				+ "\r\n"
				+ "</html>";
	}
}
