apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbm-payer-apis-service
  namespace: pbm-prod
  labels:
    app: pbm-payer-apis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbm-payer-apis-service
  template:
    metadata:
      labels:
        app: pbm-payer-apis-service
    spec:
      containers:
        - name: pbm-payer-apis-service-prod-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm/prod/pbm-payer-apis-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: TAWUNIYA_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-keys
                key: TAWUNIYA_API_KEY
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
