apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdb-validation-service-qa-deployment
  namespace: pbm-qa
  labels:
    app: fdb-validation-service-qa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdb-validation-service-qa-deployment
  template:
    metadata:
      labels:
        app: fdb-validation-service-qa-deployment
    spec:
      containers:
        - name: fdb-validation-service-qa-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-qa/fdb-validation-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
