apiVersion: v1
kind: Service
metadata:
  name: fdb-validation-service-qa-service
  namespace: pbm-qa
  labels:
    app: fdb-validation-service-qa-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: fdb-validation-service-qa-deployment
