
spring.jpa.properties.hibernate.search.backend.hosts=@elasticsearchHosts@
spring.jpa.properties.hibernate.search.backend.index_schema_management_strategy=none
spring.jpa.properties.hibernate.search.backend.schema_management.minimal_required_status=yellow
spring.jpa.properties.hibernate.search.backend.schema_management.minimal_required_status_wait_timeout=120000
spring.jpa.properties.hibernate.search.backend.discovery.enabled=false
spring.jpa.properties.hibernate.search.enabled=true


# logging.level.org.hibernate.search=TRACE