#Logging Configuration
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

#-------------------------------------------------

#MongoDB
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM_test:ENt4356PestM@tst-mongo-upgrade-tbd-1.devdbsn.wslvcn.oraclevcn.com:27017,test-mongo-upgrade-tbd.devdbsn.wslvcn.oraclevcn.com:27017/test?authSource=PBM&replicaSet=tst-mongo-01&maxPoolSize=400&maxIdleTimeMS=60000&readPreference=primary&appname=MongoDB%20Compass&ssl=false


#---------------------------------
#Liquibase configuration
#-----------------------------------
spring.priscriptionservice.liquibase.enabled=false
logging.level.liquibase = INFO
spring.priscriptionservice.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.priscriptionservice.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.priscriptionservice.liquibase.database-change-log-table=DATABASECHANGELOG
spring.priscriptionservice.default-schema=prescription_service


spring.businessrules.liquibase.enabled=false
spring.businessrules.liquibase.change-log=classpath:/database/db.changelog-businessrules.yaml
spring.businessrules.default-schema=PBM_business_rules
spring.businessrules.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.businessrules.liquibase.database-change-log-table=DATABASECHANGELOG

#---------------------------------
#DataBase Configuration
#-----------------------------------

spring.datasource.mdss.jdbc-url=jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.mdss.username=MDSS
spring.datasource.mdss.password=Dev#$#MSpro$#3234
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=1
spring.datasource.mdss.maximumPoolSize=1

spring.datasource.prescriptionservice.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.prescriptionservice.username=prescription_service
spring.datasource.prescriptionservice.password=Dev#S92p$v3
spring.datasource.prescriptionservice.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.prescriptionservice.connectionTimeout=3600000
spring.datasource.prescriptionservice.idleTimeout=600000
spring.datasource.prescriptionservice.minimumIdle=1
spring.datasource.prescriptionservice.maximumPoolSize=1

spring.datasource.hira.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.hira.username=hira
spring.datasource.hira.password=ADBPortal_HI2021
spring.datasource.hira.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hira.connectionTimeout=3600000
spring.datasource.hira.idleTimeout=600000
spring.datasource.hira.minimumIdle=1
spring.datasource.hira.maximumPoolSize=1

spring.datasource.businessrules.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.businessrules.username=PBM_business_rules
spring.datasource.businessrules.password=fs#8o2dsJ3Q$kZ
spring.datasource.businessrules.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.businessrules.connectionTimeout=3600000
spring.datasource.businessrules.idleTimeout=600000
spring.datasource.businessrules.minimumIdle=1
spring.datasource.businessrules.maximumPoolSize=1


spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true

server.port:8090

dssservice.url:http://localhost:8081/dss-service
eligibilityservice.url:http://localhost:8091/eligibility-service
drugformularyservice.url:http://localhost:8092/drug-formulary-service
policyConsumptionService.url:http://localhost:8093/policy-consumption-service
drugexclusionservice.url:http://localhost:8094/drug-exclusion-validation-service
pbmPayerApisServiceClient.url:http://localhost:8095/pbm-payer-apis-service
pbmNotificationServiceClient.url:http://localhost:8096/pbm-notification
authenticationServiceClient.url:http://localhost:8086

#--------------------------------------------
#Patient access token authentication details
#---------------------------------------------
authentication.username=prescription-service
authentication.password=prescription-service-secret

#--------------------------
#Patient portal url details
#--------------------------
patientPortal.url=https://qa-pbm-admin.waseel.com

sso.url=https://qa-iam.waseel.com/realms/waseel-qa/protocol/openid-connect/token
sso.client_id=pbm-prescription-service
sso.client_secret=6PUTHBY9qHaVLtXjM0NTDNTGmmi9Y5z5
url-shortening-service.url=https://qa-url.waseel.com
brservice.url:http://localhost:8097/br-service

spring.datasource.hikari.max-lifetime=300000
feature.toggle:true
dss.feature.toggle:true