spring.h2.console.enabled = true
spring.h2.console.path = /h2
spring.datasource.url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS PRESCRIPTION
spring.datasource.username=sa
spring.datasource.password=sa

#mdss schema
spring.datasource.mdss.jdbc-url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS MDSS
spring.datasource.mdss.username=sa
spring.datasource.mdss.password=sa
#spring.jpa.properties.hibernate.globally_quoted_identifiers=true

#spring.datasource.test.driver-class-name=org.h2.Driver
spring.priscriptionservice.liquibase.enabled=false
spring.priscriptionservice.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.businessrules.liquibase.change-log=classpath:/database/db.changelog-businessrules.yaml
spring.businessrules.liquibase.enabled=false

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

dssservice.url:http://localhost:8081/dss-service
eligibilityservice.url:http://localhost:8091/eligibility-service
drugformularyservice.url:http://localhost:8092/drug-formulary-service
policyConsumptionService.url:http://localhost:8093/policy-consumption-service
drugexclusionservice.url:http://localhost:8094/drug-exclusion-validation-service
pbmPayerApisServiceClient.url:http://localhost:8095/pbm-payer-apis-service
pbmNotificationServiceClient.url:http://localhost:8096/pbm-notification
authenticationServiceClient.url:http://localhost:8086
brservice.url:http://br-service.pbm-qa:8080/br-service

#--------------------------------------------
#Patient access token authentication details
#---------------------------------------------
authentication.username=prescription-service
authentication.password=prescription-service-secret

#--------------------------
#Patient portal url details
#--------------------------
patientPortal.url=https://qa-pbm-admin.waseel.com

sso.url=https://domain/realms/waseel-qa/protocol/openid-connect/token
sso.client_id=client_id
sso.client_secret=client_secret
url-shortening-service.url=http://link.link
feature.toggle:false
