logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

spring.datasource.prescriptionservice.jdbc-url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet/
spring.datasource.prescriptionservice.username=${PRESCRIPTION_SERVICE_USERNAME}
spring.datasource.prescriptionservice.password=${PRESCRIPTION_SERVICE_PASSWORD}
spring.datasource.prescriptionservice.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.prescriptionservice.connectionTimeout=3600000
spring.datasource.prescriptionservice.idleTimeout=600000
spring.datasource.prescriptionservice.minimumIdle=1
spring.datasource.prescriptionservice.maximumPoolSize=3

spring.datasource.mdss.jdbc-url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet/
spring.datasource.mdss.username=${MDSS_USERNAME}
spring.datasource.mdss.password=${MDSS_PASSWORD}
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=1
spring.datasource.mdss.maximumPoolSize=1

spring.datasource.hira.jdbc-url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet/
spring.datasource.hira.username=${HIRA_USERNAME}
spring.datasource.hira.password=${HIRA_PASSWORD}
spring.datasource.hira.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hira.connectionTimeout=3600000
spring.datasource.hira.idleTimeout=600000
spring.datasource.hira.minimumIdle=1
spring.datasource.hira.maximumPoolSize=1

spring.datasource.businessrules.jdbc-url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet/
spring.datasource.businessrules.username=${PBM_BUSINESS_RULES_USERNAME}
spring.datasource.businessrules.password=${PBM_BUSINESS_RULES_PASSWORD}
spring.datasource.businessrules.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.businessrules.connectionTimeout=3600000
spring.datasource.businessrules.idleTimeout=600000
spring.datasource.businessrules.minimumIdle=1
spring.datasource.businessrules.maximumPoolSize=1

#-----------------
# MongoDB
#-----------------
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM:Toyxe3dsDcHy025@mongo-db.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-02.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-03.prddbsn.wslvcn.oraclevcn.com:27017/PBM?authSource=PBM&replicaSet=prd-monog-replica&ssl=false&readPreference=primary&maxIdleTimeMS=60000&maxPoolSize=400


spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true

#Liquibase configuration
#-----------------------------------
spring.priscriptionservice.liquibase.enabled=true
logging.level.liquibase = INFO
spring.priscriptionservice.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.priscriptionservice.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.priscriptionservice.liquibase.database-change-log-table=DATABASECHANGELOG
spring.priscriptionservice.default-schema=prescription_service


spring.businessrules.liquibase.enabled=true
spring.businessrules.liquibase.change-log=classpath:/database/db.changelog-businessrules.yaml
spring.businessrules.default-schema=PBM_business_rules
spring.businessrules.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.businessrules.liquibase.database-change-log-table=DATABASECHANGELOG

#-----------------------------------
dssservice.url:http://dss-service-prod-service.pbm-prod:8080/dss-service
eligibilityservice.url:http://eligibility-service-prod-service.pbm-prod:8080/eligibility-service
drugformularyservice.url:http://drug-formulary-service.pbm-prod:8080/drug-formulary-service
policyConsumptionService.url:http://policy-consumption-service.pbm-prod:8080/policy-consumption-service
drugexclusionservice.url:http://drug-exclusion-validation-service.pbm-prod:8080/drug-exclusion-validation-service
pbmPayerApisServiceClient.url:http://pbm-payer-apis-service.pbm-prod:8080/pbm-payer-apis-service
pbmNotificationServiceClient.url:http://pbm-notification-service.pbm-prod:8080/pbm-notification
authenticationServiceClient.url:http://pbm-authentication-server.pbm-prod:8080
brservice.url:http://br-service.pbm-prod:8080/br-service

springdoc.default-produces-media-type=application/json

#--------------------------------------------
#Patient access token authentication details
#---------------------------------------------
authentication.username=${PBM_OAUTH_CLIENT_ID}
authentication.password=${PBM_OAUTH_CLIENT_SECRET}

#--------------------------
#Patient portal url details
#--------------------------
patientPortal.url=https://rx.waseel.com 

sso.url=https://iam.waseel.com/realms/waseel-prod/protocol/openid-connect/token
sso.client_id=${SSO_CLIENT_ID}
sso.client_secret=${SSO_CLIENT_SECRET}
url-shortening-service.url=http://waseel-url-shortener:8080

logging.level.org.hibernate.SQL=DEBUG

swagger.url:https://rx.waseel.com/api
swagger.authorization.url:https://rx.waseel.com/api/oauth/signIn
swagger.refresh.url:https://rx.waseel.com/api/oauth/refresh

spring.datasource.hikari.max-lifetime=300000
feature.toggle:true
