#-----------------
# MongoDB
#-----------------
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM:Toyxe3dsDcHy025@mongo-db.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-02.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-03.prddbsn.wslvcn.oraclevcn.com:27017/PBM?authSource=PBM&replicaSet=prd-monog-replica&ssl=false&readPreference=primary&maxIdleTimeMS=60000&maxPoolSize=400

#Handling Exception
server.error.include-stacktrace=ALWAYS
server.error.include-message: ALWAYS

#---------------------------------
#Liquibase configuration
#-----------------------------------
spring.liquibase.enabled=true
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=PBM_business_rules


#---------------------------------
#DataBase Configuration
#-----------------------------------

spring.datasource.hira.jdbc-url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet/
spring.datasource.hira.username=${HIRA_USERNAME}
spring.datasource.hira.password=${HIRA_PASSWORD}
spring.datasource.hira.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hira.connectionTimeout=3600000
spring.datasource.hira.idleTimeout=600000
spring.datasource.hira.minimumIdle=1
spring.datasource.hira.maximumPoolSize=1

spring.datasource.businessrules.jdbc-url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet/
spring.datasource.businessrules.username=${PBM_BUSINESS_RULES_USERNAME}
spring.datasource.businessrules.password=${PBM_BUSINESS_RULES_PASSWORD}
spring.datasource.businessrules.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.businessrules.connectionTimeout=3600000
spring.datasource.businessrules.idleTimeout=600000
spring.datasource.businessrules.minimumIdle=1
spring.datasource.businessrules.maximumPoolSize=1

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers=false

#---------------------------------
#Client urls
#-----------------------------------

clients.pbmPayerApisService.url:http://pbm-payer-apis-service.pbm-prod:8080/pbm-payer-apis-service