service_name=policy-consumption-service
service_version= 1.0
application_packages=com.waseel.policy
server_urls=http://apm.elastic:8200
secret_token=apm-t0ken@123
enable_log_correlation=true
transaction_sample_rate=0.1
environment=@elasticEnvironment@