apiVersion: v1
kind: Service
metadata:
  name: drug-exclusion-validation-service
  namespace: pbm-qa
  labels:
    app: drug-exclusion-validation-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: drug-exclusion-validation-service
