name: Build drug-exclusion-validation-service-qa

on:
  workflow_dispatch:
  push:
    branches:
    - qa
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Add default settings.xml with github server in it.
      uses: s4u/maven-settings-action@v2.3.0
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: make wallet dir
      run: |
          mkdir wallet
      shell: bash
    - name: bring wallet
      uses: timheuer/base64-to-file@v1.1
      with:
    # Name of the file when written to temp location
        fileName: wallet.zip
    # If it is set, change the output location to specific one from temp location.
        fileDir: wallet
    # The base64 encoded string
        encodedString: ${{ secrets.WALLET_QA }}
    - name: make wallet dir
      run: |
           unzip wallet/wallet.zip -d wallet
      shell: bash    
     
    - name: Build with Maven
      run: mvn package -P qa -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true -e -B    

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login me-jeddah-1.ocir.io -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Build
      run: docker build --build-arg env_name=qa . -t  me-jeddah-1.ocir.io/ax7dvcawpc84/pbm/qa/drug-exclusion-validation-service:latest -t  me-jeddah-1.ocir.io/ax7dvcawpc84/pbm/qa/drug-exclusion-validation-service:${{ github.sha }}

    - name: Docker Push
      run: docker push --all-tags me-jeddah-1.ocir.io/ax7dvcawpc84/pbm/qa/drug-exclusion-validation-service
      
    - name: Deploy to K8S
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.PORTAL_KUBE_CONFIG_QA }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: set image --record deployment/drug-exclusion-validation-service drug-exclusion-validation-service-qa-container=me-jeddah-1.ocir.io/ax7dvcawpc84/pbm/qa/drug-exclusion-validation-service:${{ github.sha }} -n pbm-qa

    - name: Verify Deployment
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.PORTAL_KUBE_CONFIG_QA }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: '"rollout status deployment/drug-exclusion-validation-service -n pbm-qa"'
