--liquibase formatted sql

--changeset Prescription:0006

ALTER TABLE "PBM_BUSINESS_RULES"."PhysicianInfo"
ADD ("PhysicianInfoId" NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL);

ALTER TABLE "PBM_BUSINESS_RULES"."PhysicianInfo"
ADD CONSTRAINT UK_PId_RNumber_PInfo UNIQUE ("ProviderId","RegistrationNumber");

ALTER TABLE "PBM_BUSINESS_RULES"."PhysicianInfo"
ADD CONSTRAINT PK_PInfoId_PInfo PRIMARY KEY ("PhysicianInfoId");
