--liquibase formatted sql

--changeset Prescription:0008

CREATE TABLE PBM_BUSINESS_RULES.AUDIT_LOG
(
	AUDIT_LOG_ID NUMBER NOT NULL,
    UPDATE_BY VARCHAR2(250) NOT NULL,
    UPDATE_DATE DATE NOT NULL,
    ENTITY_ID  NUMBER NOT NULL,
    ENTITY_NAME VARCHAR2(250) NOT NULL,
    UPDATE_TYPE VARCHAR2(10) NOT NULL,
    ENTITY_DATA  CLOB,
    CONSTRAINT PK_AUDIT_LOG PRIMARY KEY (AUDIT_LOG_ID)
);

CREATE SEQUENCE PBM_BUSINESS_RULES.AUDIT_LOG_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;