--liquibase formatted sql

--changeset Drug Formulary Service:0015

ALTER TABLE PBM_BUSINESS_RULES.BENEFIT_SUBCOVERAGE
RENAME COLUMN SUBCOVERAGE_APP_THRESHOLD_VALUE TO SUBCOV_APP_THRESHOLD_VALUE;

ALTER TABLE PBM_BUSINESS_RULES.BENEFIT_SUBCOVERAGE
RENAME COLUMN SUBCOVERAGE_APPROVAL_THRESHOLD_CURRENCY TO SUBCOV_APP_THRESHOLD_CURRENCY;