--liquibase formatted sql

--changeset Drug Formulary Service:0016

ALTER TABLE PBM_BUSINESS_RULES.MEMBER_BENEFIT_ASSOICATION
RENAME COLUMN BENEFIT_REMAINING_LIMIT_CURRENCY TO BENEFIT_REMAINING_LIMIT_CURR;
