--liquibase formatted sql

--changeset Drug Formulary Service:0018

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
RENAME CONSTRAINT UK_DRUG_FORMULARY_POLICY_ASSOCIATION TO UK_DF_POLICY_ASSOCIATION;