--liquibase formatted sql

--changeset Drug Formulary Service:0019

ALTER TABLE PBM_BUSINESS_RULES.MEMBER_CHRONIC_DISEASES_ASSOCIATION
RENAME CONSTRAINT PK_MEMBER_CHRONIC_DISEASES_ASSOCIATION TO PK_MC_DISEASES_ASSOCIATION;