--liquibase formatted sql

--changeset Drug Formulary Service:0020

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
RENAME CONSTRAINT PK_DRUG_FORMULARY_POLICY_ASSOCIATION TO PK_DF_POLICY_ASSOCIATION;