--liquibase formatted sql

--changeset Drug Formulary Service:0021

ALTER TABLE PBM_BUSINESS_RULES.MEMBER_POLICY_ASSOCIATION
DROP CONSTRAINT UK_MEMBER_POLICY_ASSOCIATION;

ALTER TABLE PBM_BUSINESS_RULES.MEMBER_POLICY_ASSOCIATION
ADD CONSTRAINT UK_MEMBER_POLICY_ASSOCIATION UNIQUE (MEMBER_PROFILE_ID,POLICY_INFORMATION_ID);