--liquibase formatted sql

--changeset Drug Formulary Service:0023

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
DROP CONSTRAINT FK_DFD_FORMULARY_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
DROP CONSTRAINT UK_DRUG_FORMULARY_DETAILS;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
DROP CONSTRAINT PK_DRUG_FORMULARY_DETAILS;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
DROP COLUMN DRUG_FORMULARY_DETAILS_ID;

CREATE SEQUENCE DRUG_FORMULARY_DETAILS_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
ADD DRUG_FORMULARY_DETAILS_ID NUMBER DEFAULT DRUG_FORMULARY_DETAILS_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
ADD CONSTRAINT PK_DRUG_FORMULARY_DETAILS PRIMARY KEY (DRUG_FORMULARY_DETAILS_ID)