--liquibase formatted sql

--changeset Drug Formulary Service:0024

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
DROP CONSTRAINT FK_DFPA_FORMULARY_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
DROP CONSTRAINT UK_DF_POLICY_ASSOCIATION;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
DROP CONSTRAINT PK_DF_POLICY_ASSOCIATION;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
DROP COLUMN DRUG_FORMULARY_ASSOCIATION_ID;

CREATE SEQUENCE DRUG_FORMULARY_POLICY_ASSOCIATION_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
ADD DRUG_FORMULARY_ASSOCIATION_ID NUMBER DEFAULT DRUG_FORMULARY_POLICY_ASSOCIATION_SEQ.nextval not null;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
ADD CONSTRAINT PK_DF_POLICY_ASSOCIATION PRIMARY KEY (DRUG_FORMULARY_ASSOCIATION_ID)