--liquibase formatted sql

--changeset Drug Formulary Service:0025

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_METADATA
DROP CONSTRAINT PK_DRUG_FORMULARY_METADATA;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_METADATA
DROP COLUMN FORMULARY_ID;

CREATE SEQUENCE DRUG_FORMULARY_METADATA_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_METADATA
ADD FORMULARY_ID NUMBER DEFAULT DRUG_FORMULARY_METADATA_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_METADATA
ADD CONSTRAINT PK_DRUG_FORMULARY_METADATA PRIMARY KEY (FORMULARY_ID);