--liquibase formatted sql

--changeset Drug Formulary Service:0026

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
ADD CONSTRAINT FK_DFD_FORMULARY_ID FOREIGN KEY (FORMULARY_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_FORMULARY_METADATA (FORMULARY_ID);

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
ADD CONSTRAINT UK_DRUG_FORMULARY_DETAILS UNIQUE (FORMULARY_ID,WASEEL_DRUG_ID,REGISTRATION_NUMBER);