--liquibase formatted sql

--changeset Drug Formulary Service:0027

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
ADD CONSTRAINT FK_DFPA_FORMULARY_ID FOREIGN KEY (FORMULARY_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_FORMULARY_METADATA (FORMULARY_ID);

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_POLICY_ASSOCIATION
ADD CONSTRAINT UK_DF_POLICY_ASSOCIATION
UNIQUE (FORMULARY_ID,POLICY_INFORMATION_ID,POLICY_CLASS_ID,MEMBER_POLICY_ASSOCIATION_ID);