--liquibase formatted sql

--changeset Drug Formulary Service:0029

ALTER TABLE PBM_BUSINESS_RULES.MEMBER_POLICY_ASSOCIATION ADD (IS_ENABLED CHAR(1) DEFAULT ('1'));
ALTER TABLE PBM_BUSINESS_RULES.MEMBER_POLICY_ASSOCIATION MODIFY (IS_ENABLED CHAR(1) NOT NULL  ENABLE NOVALIDATE);