--liquibase formatted sql

--changeset Drug Formulary Service:0030

ALTER TABLE PBM_BUSINESS_RULES.POLICY_CLASSES ADD (IS_ENABLED CHAR(1) DEFAULT ('1'));
ALTER TABLE PBM_BUSINESS_RULES.POLICY_CLASSES MODIFY (IS_ENABLED CHAR(1) NOT NULL  ENABLE NOVALIDATE);