--liquibase formatted sql

--changeset Drug Formulary Service:0032

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
DROP CONSTRAINT UK_DRUG_FORMULARY_DETAILS;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_FORMULARY_DETAILS
ADD CONSTRAINT UK_DRUG_FORMULARY_DETAILS UNIQUE (FORMULARY_ID,REGISTRATION_NUMBER);