apiVersion: apps/v1
kind: Deployment
metadata:
  name: idf-validation-service-qa-deployment
  namespace: pbm-qa
  labels:
    app: idf-validation-service-qa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idf-validation-service-qa-deployment
  template:
    metadata:
      labels:
        app: idf-validation-service-qa-deployment
    spec:
      containers:
        - name: idf-validation-service-qa-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-qa/idf-validation-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /idf-validation-service/actuator/health/liveness
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 20
      imagePullSecrets:
        - name: waseel-docker-registry-cred
