--liquibase formatted sql

--changeset DSS Admin Service:0001

CREATE SEQUENCE "MDSS"."AUDIT_LOG_SEQ"
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;
  
CREATE TABLE "MDSS"."AUDIT_LOG" (
    "AUDIT_LOG_ID"  NUMBER DEFAULT audit_log_seq.NEXTVAL NOT NULL,
    "USER_NAME"     VARCHAR2(50) NOT NULL,
    "ENTITY_ID"     NUMBER NOT NULL,
    "ENTITY_NAME"   VARCHAR2(250) NOT NULL,
    "ACTION"        VARCHAR2(15) NOT NULL,
    "DATE"          DATE NOT NULL,
    "ACCOUNT_ID"    VARCHAR2(10) NOT NULL,
    "ENTITIY_DATA"  CLOB DEFAULT NULL,
    CONSTRAINT pk_audit_log_id PRIMARY KEY ( "AUDIT_LOG_ID" )
);