--liquibase formatted sql

--changeset DSS Admin Service:0002

CREATE SEQUENCE "MDSS"."LOV_SEQ"
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;
  
CREATE TABLE "MDSS"."LOV" (
    "LOV_ID"  NUMBER DEFAULT LOV_SEQ.NEXTVAL NOT NULL,
    "KEY"     VARCHAR2(64) NOT NULL,
    "VALUE"     VARCHAR2(300) NOT NULL,
    "LABEL_EN"   VARCHAR2(300) NOT NULL,
    "LABEL_AR"   VARCHAR2(300) NOT NULL,
    CONSTRAINT PK_LOV_ID PRIMARY KEY ( "LOV_ID" )
);