--liquibase formatted sql

--changeset DSS Admin Service:0004

INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Vaginal gel', 'Vaginal gel', 'Vaginal gel');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cream', 'Cream', 'Cream');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for peritoneal dialysis', 'Solution for peritoneal dialysis', 'Solution for peritoneal dialysis');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Caplet', 'Caplet', 'Caplet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Pressurised inhalation, solution', 'Pressurised inhalation, solution', 'Pressurised inhalation, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye drops, solution', 'Eye drops, solution', 'Eye drops, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Transdermal patch', 'Transdermal patch', 'Transdermal patch');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral liquid', 'Oral liquid', 'Oral liquid');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Effervescent granules', 'Effervescent granules', 'Effervescent granules');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gastro-resistant capsule, hard', 'Gastro-resistant capsule, hard', 'Gastro-resistant capsule, hard');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Lotion', 'Lotion', 'Lotion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Extended-release capsule', 'Extended-release capsule', 'Extended-release capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Orodispersible tablet', 'Orodispersible tablet', 'Orodispersible tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gastro-resistant capsule', 'Gastro-resistant capsule', 'Gastro-resistant capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate for peritoneal dialysis solution', 'Concentrate for peritoneal dialysis solution', 'Concentrate for peritoneal dialysis solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral powder', 'Oral powder', 'Oral powder');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Film-coated tablet', 'Film-coated tablet', 'Film-coated tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Injection', 'Injection', 'Injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye drops', 'Eye drops', 'Eye drops');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Suspension for injection', 'Suspension for injection', 'Suspension for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gel', 'Gel', 'Gel');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Lyophilisate for solution for injection', 'Lyophilisate for solution for injection', 'Lyophilisate for solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cutaneous suspension', 'Cutaneous suspension', 'Cutaneous suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate and diluent for solution for infusion', 'Concentrate and diluent for solution for infusion', 'Concentrate and diluent for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for solution for injection/infusion', 'Powder and solvent for solution for injection/infusion', 'Powder and solvent for solution for injection/infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Vaginal capsule', 'Vaginal capsule', 'Vaginal capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for concentrate for solution for infusion', 'Powder for concentrate for solution for infusion', 'Powder for concentrate for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral gel', 'Oral gel', 'Oral gel');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Vaginal tablet', 'Vaginal tablet', 'Vaginal tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for suspension for injection in pre-filled syringe', 'Powder and solvent for suspension for injection in pre-filled syringe', 'Powder and solvent for suspension for injection in pre-filled syringe');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Implant in pre-filled syringe', 'Implant in pre-filled syringe', 'Implant in pre-filled syringe');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Sterile, lyophilized, white powder', 'Sterile, lyophilized, white powder', 'Sterile, lyophilized, white powder');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cutaneous patch', 'Cutaneous patch', 'Cutaneous patch');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gel for injection', 'Gel for injection', 'Gel for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'powder for solution for injection\nfusion', 'powder for solution for injection\nfusion', 'powder for solution for injection\nfusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Syrup', 'Syrup', 'Syrup');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Vaginal delivery system', 'Vaginal delivery system', 'Vaginal delivery system');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Aerosol', 'Aerosol', 'Aerosol');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Inhalation powder', 'Inhalation powder', 'Inhalation powder');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Prolonged-release granules', 'Prolonged-release granules', 'Prolonged-release granules');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for haemodialysis', 'Solution for haemodialysis', 'Solution for haemodialysis');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye drops, suspension', 'Eye drops, suspension', 'Eye drops, suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Modified-release capsule', 'Modified-release capsule', 'Modified-release capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for oral suspension', 'Powder for oral suspension', 'Powder for oral suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ear/eye drops, solution', 'Ear/eye drops, solution', 'Ear/eye drops, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Intravenous infusion', 'Intravenous infusion', 'Intravenous infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Granules for oral suspension', 'Granules for oral suspension', 'Granules for oral suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal drops', 'Nasal drops', 'Nasal drops');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Vaginal capsule, soft', 'Vaginal capsule, soft', 'Vaginal capsule, soft');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Infusion', 'Infusion', 'Infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Effervescent powder', 'Effervescent powder', 'Effervescent powder');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Inhalation powder, pre-dispensed', 'Inhalation powder, pre-dispensed', 'Inhalation powder, pre-dispensed');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate and solvent for solution for infusion', 'Concentrate and solvent for solution for infusion', 'Concentrate and solvent for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Granules for suspension', 'Granules for suspension', 'Granules for suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection', 'Solution for injection', 'Solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate for solution for infusion', 'Concentrate for solution for infusion', 'Concentrate for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for injection', 'Powder for injection', 'Powder for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral drops, solution', 'Oral drops, solution', 'Oral drops, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral drops', 'Oral drops', 'Oral drops');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral lyophilisate', 'Oral lyophilisate', 'Oral lyophilisate');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'powder for solution for injection', 'powder for solution for injection', 'powder for solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Effervescent tablet', 'Effervescent tablet', 'Effervescent tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Mouthwash', 'Mouthwash', 'Mouthwash');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Suspension for injection in pre-filled syringe', 'Suspension for injection in pre-filled syringe', 'Suspension for injection in pre-filled syringe');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ophthalmic solution', 'Ophthalmic solution', 'Ophthalmic solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gastro-resistant coated tablet', 'Gastro-resistant coated tablet', 'Gastro-resistant coated tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for solution for injection', 'Powder and solvent for solution for injection', 'Powder and solvent for solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Intrauterine delivery system', 'Intrauterine delivery system', 'Intrauterine delivery system');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Prolonged-release capsule, hard', 'Prolonged-release capsule, hard', 'Prolonged-release capsule, hard');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ear drops, solution', 'Ear drops, solution', 'Ear drops, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ear drops', 'Ear drops', 'Ear drops');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Rectal ointment', 'Rectal ointment', 'Rectal ointment');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Soluble tablet', 'Soluble tablet', 'Soluble tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Implant', 'Implant', 'Implant');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Rectal suspension', 'Rectal suspension', 'Rectal suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for suspension for injection', 'Powder for suspension for injection', 'Powder for suspension for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection/infusion in pre-filled syringe', 'Solution for injection/infusion in pre-filled syringe', 'Solution for injection/infusion in pre-filled syringe');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Medicated chewing-gum', 'Medicated chewing-gum', 'Medicated chewing-gum');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for bladder irrigation', 'Powder for bladder irrigation', 'Powder for bladder irrigation');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ointment', 'Ointment', 'Ointment');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection/infusion', 'Solution for injection/infusion', 'Solution for injection/infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Shampoo', 'Shampoo', 'Shampoo');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for suspension', 'Powder for suspension', 'Powder for suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Extended-release tablet', 'Extended-release tablet', 'Extended-release tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nebuliser solution', 'Nebuliser solution', 'Nebuliser solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Spray', 'Spray', 'Spray');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Sealant matrix', 'Sealant matrix', 'Sealant matrix');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for oral solution', 'Powder for oral solution', 'Powder for oral solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for suspension for injection', 'Powder and solvent for suspension for injection', 'Powder and solvent for suspension for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection in cartridge', 'Solution for injection in cartridge', 'Solution for injection in cartridge');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Capsule, soft', 'Capsule, soft', 'Capsule, soft');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for solution for injection/infusion', 'Powder for solution for injection/infusion', 'Powder for solution for injection/infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Scalp solution', 'Scalp solution', 'Scalp solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Drops', 'Drops', 'Drops');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye/nose drops', 'Eye/nose drops', 'Eye/nose drops');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal ointment', 'Nasal ointment', 'Nasal ointment');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Tablet, orally disintegrating', 'Tablet, orally disintegrating', 'Tablet, orally disintegrating');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Modified-release capsule, hard', 'Modified-release capsule, hard', 'Modified-release capsule, hard');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Intravitreal implant in applicator', 'Intravitreal implant in applicator', 'Intravitreal implant in applicator');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solvent for parenteral use', 'Solvent for parenteral use', 'Solvent for parenteral use');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Dispersion for infusion', 'Dispersion for infusion', 'Dispersion for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate and solvent for solution for injection', 'Concentrate and solvent for solution for injection', 'Concentrate and solvent for solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Sustained-release tablet', 'Sustained-release tablet', 'Sustained-release tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Suspension', 'Suspension', 'Suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Tablet', 'Tablet', 'Tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection in pre-filled syringe', 'Solution for injection in pre-filled syringe', 'Solution for injection in pre-filled syringe');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral suspension', 'Oral suspension', 'Oral suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Prolonged-release tablet', 'Prolonged-release tablet', 'Prolonged-release tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder', 'Powder', 'Powder');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Inhalation vapour, liquid', 'Inhalation vapour, liquid', 'Inhalation vapour, liquid');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gastro-resistant tablet', 'Gastro-resistant tablet', 'Gastro-resistant tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Sublingual tablet', 'Sublingual tablet', 'Sublingual tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cutaneous liquid', 'Cutaneous liquid', 'Cutaneous liquid');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Granules for oral solution', 'Granules for oral solution', 'Granules for oral solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'modified-release tablet', 'modified-release tablet', 'modified-release tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for haemodialysis/haemofiltration', 'Solution for haemodialysis/haemofiltration', 'Solution for haemodialysis/haemofiltration');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'inhalation solution', 'inhalation solution', 'inhalation solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Chewable/dispersible tablet', 'Chewable/dispersible tablet', 'Chewable/dispersible tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for sealant', 'Powder and solvent for sealant', 'Powder and solvent for sealant');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'eye gel', 'eye gel', 'eye gel');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Chewable tablet', 'Chewable tablet', 'Chewable tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Capsule', 'Capsule', 'Capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Suppository', 'Suppository', 'Suppository');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Emulsion for injection/infusion', 'Emulsion for injection/infusion', 'Emulsion for injection/infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for solution for infusion', 'Powder for solution for infusion', 'Powder for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for infusion', 'Solution for infusion', 'Solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nebuliser suspension', 'Nebuliser suspension', 'Nebuliser suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal spray, solution', 'Nasal spray, solution', 'Nasal spray, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cutaneous powder', 'Cutaneous powder', 'Cutaneous powder');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Coated tablet', 'Coated tablet', 'Coated tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Emulsion', 'Emulsion', 'Emulsion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye ointment', 'Eye ointment', 'Eye ointment');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for oral/rectal suspension', 'Powder for oral/rectal suspension', 'Powder for oral/rectal suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Dispersible tablet', 'Dispersible tablet', 'Dispersible tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for prolonged-release suspension for injection', 'Powder and solvent for prolonged-release suspension for injection', 'Powder and solvent for prolonged-release suspension for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Inhalation powder, hard capsule', 'Inhalation powder, hard capsule', 'Inhalation powder, hard capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Pressurised inhalation', 'Pressurised inhalation', 'Pressurised inhalation');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Prolonged-release capsule', 'Prolonged-release capsule', 'Prolonged-release capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ophthalmic strip', 'Ophthalmic strip', 'Ophthalmic strip');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Pessary', 'Pessary', 'Pessary');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Granules in sachet', 'Granules in sachet', 'Granules in sachet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye drops, emulsion', 'Eye drops, emulsion', 'Eye drops, emulsion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Lyophilisate for solution for infusion', 'Lyophilisate for solution for infusion', 'Lyophilisate for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Capsule, hard', 'Capsule, hard', 'Capsule, hard');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution', 'Solution', 'Solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Enteric-coated tablet', 'Enteric-coated tablet', 'Enteric-coated tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cutaneous solution', 'Cutaneous solution', 'Cutaneous solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Enema', 'Enema', 'Enema');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Granules', 'Granules', 'Granules');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Medicated plaster', 'Medicated plaster', 'Medicated plaster');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection in pre-filled pen', 'Solution for injection in pre-filled pen', 'Solution for injection in pre-filled pen');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal drops, solution', 'Nasal drops, solution', 'Nasal drops, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Modified-release film-coated tablet', 'Modified-release film-coated tablet', 'Modified-release film-coated tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal spray, suspension', 'Nasal spray, suspension', 'Nasal spray, suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Emulsion for infusion', 'Emulsion for infusion', 'Emulsion for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Prolonged-release film-coated tablet', 'Prolonged-release film-coated tablet', 'Prolonged-release film-coated tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Lozenge', 'Lozenge', 'Lozenge');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for injection/concentrate for solution for infusion', 'Solution for injection/concentrate for solution for infusion', 'Solution for injection/concentrate for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for oral solution in sachet', 'Powder for oral solution in sachet', 'Powder for oral solution in sachet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for infusion', 'Powder for infusion', 'Powder for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for concentrate for solution for haemodialysis', 'Powder for concentrate for solution for haemodialysis', 'Powder for concentrate for solution for haemodialysis');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Irrigation solution', 'Irrigation solution', 'Irrigation solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate for dispersion for injection', 'Concentrate for dispersion for injection', 'Concentrate for dispersion for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Vaginal cream', 'Vaginal cream', 'Vaginal cream');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal spray', 'Nasal spray', 'Nasal spray');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'concentrate for solution for injection', 'concentrate for solution for injection', 'concentrate for solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Concentrate for solution for haemodialysis', 'Concentrate for solution for haemodialysis', 'Concentrate for solution for haemodialysis');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder for concentrate for dispersion for infusion', 'Powder for concentrate for dispersion for infusion', 'Powder for concentrate for dispersion for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Oral solution', 'Oral solution', 'Oral solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solvent for solution for infusion', 'Powder and solvent for solution for infusion', 'Powder and solvent for solution for infusion');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Nasal drops, suspension', 'Nasal drops, suspension', 'Nasal drops, suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Pressurised inhalation, suspension', 'Pressurised inhalation, suspension', 'Pressurised inhalation, suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and suspension for suspension for injection', 'Powder and suspension for suspension for injection', 'Powder and suspension for suspension for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Scored tablet', 'Scored tablet', 'Scored tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Ear/eye/nose drops, solution', 'Ear/eye/nose drops, solution', 'Ear/eye/nose drops, solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Delayed-release tablet', 'Delayed-release tablet', 'Delayed-release tablet');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Powder and solution for solution for injection', 'Powder and solution for solution for injection', 'Powder and solution for solution for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Endotracheopulmonary instillation, suspension', 'Endotracheopulmonary instillation, suspension', 'Endotracheopulmonary instillation, suspension');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Prolonged-release suspension for injection', 'Prolonged-release suspension for injection', 'Prolonged-release suspension for injection');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Eye drops, solution in single-dose container', 'Eye drops, solution in single-dose container', 'Eye drops, solution in single-dose container');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Solution for infusion and oral solution', 'Solution for infusion and oral solution', 'Solution for infusion and oral solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Gastroenteral solution', 'Gastroenteral solution', 'Gastroenteral solution');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Delayed-release capsule', 'Delayed-release capsule', 'Delayed-release capsule');
INSERT INTO MDSS.LOV(KEY, VALUE, LABEL_EN, LABEL_AR) VALUES ('dosageForm', 'Cutaneous foam', 'Cutaneous foam', 'Cutaneous foam');