generic-base-url=https://url.waseel.com
e-prescirption-base-url=https://ep.waseel.com


spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://iam.waseel.com/realms/waseel-prod/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=${URL_SHORTENER_CLIENT_ID}
spring.security.oauth2.resourceserver.opaquetoken.client-secret=${URL_SHORTENER_CLIENT_SECRET}


spring.redis.host=redis-master.default
spring.redis.port=6379
spring.redis.username=${REDIS_USERNAME}
spring.redis.password=${REDIS_PASSWORD}
