generic-base-url=https://stg-url.waseel.com
e-prescirption-base-url=https://stg-ep.waseel.com


spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://qa-iam.waseel.com/realms/waseel-stg/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=${URL_SHORTENER_CLIENT_ID}
spring.security.oauth2.resourceserver.opaquetoken.client-secret=${URL_SHORTENER_CLIENT_SECRET}

spring.redis.username=${REDIS_USERNAME}
spring.redis.password=${REDIS_PASSWORD}
spring.redis.host=redis-master.redis.svc.cluster.local
spring.redis.port=6379