server.port=8898

generic-base-url=http://localhost:${server.port}
e-prescirption-base-url=http://localhost:${server.port}


spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=https://qa-iam.waseel.com/realms/waseel-qa/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id=url-shortener-service
spring.security.oauth2.resourceserver.opaquetoken.client-secret=jbgkZ5fXqmxIeeO0t64HNV5GldJnad7P