service_name=waseelurlshortener
service_version=1.0
application_packages=com.waseel.waseelurlshortener
server_urls=http://apm.elastic:8200
secret_token=apm-t0ken@123
enable_log_correlation=true
transaction_sample_rate=1
environment=@elasticEnvironment@