server.max-http-header-size=24576
spring.profiles.active=@activatedSpringProperties@
server.servlet.context-path=/pbm-authentication-service

spring.jackson.time-zone=Asia/Riyadh
spring.jackson.locale=en-SA

management.metrics.web.client.max-uri-tags: 400
management.metrics.web.server.max-uri-tags: 400