apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: pbm-stg
  labels:
    app: email-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: email-service
