apiVersion: v1
kind: Service
metadata:
  name: waseel-url-shortener
  namespace: pbm-qa
  labels:
    app: waseel-url-shortener
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: waseel-url-shortener
