#Logging Configuration
#-----------------------------------
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

#-----------------------------------
#DataBase Configuration
#-----------------------------------
spring.datasource.url=jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.username=PBM_BUSINESS_RULES
spring.datasource.password=fs#8o2dsJ3Q$kZ
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=300000
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#------------------------------
#Liquibase configuration
#------------------------------
spring.liquibase.enabled=false
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=PBM_BUSINESS_RULES

server.port:8093

client.tawuniya.url:https://mock.waseel.com/rest/Business+Rules+APIs/1.2/

#Header Parameters
sender.code =101
receiver.code = 102
transaction.id=1
timestamp = YYYY-MM-DDThh:mm:ss<TZDSuffix> 
direction = REQUEST
apikey = abc
