#Logging Configuration
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

#-------------------------------------------------

#MongoDB
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM_test:ENt4356PestM@tst-mongo-upgrade-tbd-1.devdbsn.wslvcn.oraclevcn.com:27017,test-mongo-upgrade-tbd.devdbsn.wslvcn.oraclevcn.com:27017/test?authSource=PBM&replicaSet=tst-mongo-01&maxPoolSize=400&maxIdleTimeMS=60000&readPreference=primary&appname=MongoDB%20Compass&ssl=false


#---------------------------------
#Liquibase configuration
#-----------------------------------
spring.liquibase.enabled=false
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=MDSS

#DataBase Configuration
spring.datasource.url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.username=MDSS
spring.datasource.password=Dev#$#MSpro$#3234
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true
spring.datasource.hikari.connectionTimeout=3600000
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.minimumIdle=1
spring.datasource.hikari.maximumPoolSize=1


server.port:8082
