<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.0</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.waseel</groupId>
	<artifactId>pbm-gateway-service</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>pbm-gateway-service</name>
	<description>Gateway for pbm services</description>
	<properties>
		<java.version>11</java.version>
		<spring-cloud.version>2021.0.2</spring-cloud.version>
	</properties>
	<profiles>
		<profile>
			<id>local</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<property>
					<name>local</name>
				</property>
			</activation>
			<properties>
				<activatedSpringProperties>local</activatedSpringProperties>
				<maven.test.skip>true</maven.test.skip>
				<pbm-gatewayUrl>http://localhost:8080</pbm-gatewayUrl>
				<dss-serviceUrl>http://localhost:8081</dss-serviceUrl>
				<idf-serviceUrl>http://localhost:8082</idf-serviceUrl>
				<fdb-serviceUrl>http://localhost:8083</fdb-serviceUrl>
				<rts-serviceUrl>http://localhost:8084</rts-serviceUrl>
				<payer-customization-serviceUrl>http://localhost:8085</payer-customization-serviceUrl>
				<pbm-admin-service-serviceUrl>http://localhost:8086</pbm-admin-service-serviceUrl>
				<oauthUrl>http://localhost:8086</oauthUrl>
				<prescription-service-serviceUrl>http://localhost:8090</prescription-service-serviceUrl>
				<pbm-notification-service-serviceUrl>http://localhost:8096</pbm-notification-service-serviceUrl>
				<dss-admin-service-serviceUrl>http://localhost:8098</dss-admin-service-serviceUrl>
			</properties>
		</profile>
		<profile>
			<id>qa</id>
			<activation>
				<property>
					<name>qa</name>
				</property>
			</activation>
			<properties>
				<activatedSpringProperties>qa</activatedSpringProperties>
				<maven.test.skip>true</maven.test.skip>
				<pbm-gatewayUrl>https://qa-pbm-admin.waseel.com/api</pbm-gatewayUrl>
				<dss-serviceUrl>http://pqa-portal.waseel.com:8081</dss-serviceUrl>
				<idf-serviceUrl>http://pqa-portal.waseel.com:8082</idf-serviceUrl>
				<fdb-serviceUrl>http://pqa-portal.waseel.com:8083</fdb-serviceUrl>
				<rts-serviceUrl>http://pqa-portal.waseel.com:8084</rts-serviceUrl>
				<payer-customization-serviceUrl>http://payer-customization-service-qa-service:8080</payer-customization-serviceUrl>
				<pbm-admin-service-serviceUrl>http://admin-service-qa-service:8080</pbm-admin-service-serviceUrl>
				<oauthUrl>http://pbm-authentication-server:8080</oauthUrl>
				<prescription-service-serviceUrl>http://prescription-service-qa-service:8080</prescription-service-serviceUrl>
				<pbm-notification-service-serviceUrl>http://pbm-notification-service:8080</pbm-notification-service-serviceUrl>
				<dss-admin-service-serviceUrl>http://dss-admin-service:8080</dss-admin-service-serviceUrl>
			</properties>
		</profile>
		<profile>
			<id>stg</id>
			<activation>
				<property>
					<name>stg</name>
				</property>
			</activation>
			<properties>
				<activatedSpringProperties>stg</activatedSpringProperties>
				<elasticEnvironment>STAGING</elasticEnvironment>
				<maven.test.skip>true</maven.test.skip>
				<pbm-gatewayUrl>https://stg-pbm-admin.waseel.com/api</pbm-gatewayUrl>
				<dss-serviceUrl>http://pqa-portal.waseel.com:8081</dss-serviceUrl>
				<idf-serviceUrl>http://pqa-portal.waseel.com:8082</idf-serviceUrl>
				<fdb-serviceUrl>http://pqa-portal.waseel.com:8083</fdb-serviceUrl>
				<rts-serviceUrl>http://pqa-portal.waseel.com:8084</rts-serviceUrl>
				<payer-customization-serviceUrl>http://payer-customization-service-stg-service:8080</payer-customization-serviceUrl>
				<pbm-admin-service-serviceUrl>http://admin-service-stg-service:8080</pbm-admin-service-serviceUrl>
				<oauthUrl>http://pbm-authentication-server:8080</oauthUrl>
				<prescription-service-serviceUrl>http://prescription-service-stg-service:8080</prescription-service-serviceUrl>
				<pbm-notification-service-serviceUrl>http://pbm-notification-service:8080</pbm-notification-service-serviceUrl>
				<dss-admin-service-serviceUrl>http://dss-admin-service:8080</dss-admin-service-serviceUrl>
			</properties>
		</profile>
		<profile>
			<id>prod</id>
			<activation>
				<property>
					<name>prod</name>
				</property>
			</activation>
			<properties>
				<activatedSpringProperties>prod</activatedSpringProperties>
				<elasticEnvironment>PROD</elasticEnvironment>
				<maven.test.skip>true</maven.test.skip>
				<pbm-gatewayUrl>https://rx.waseel.com/api</pbm-gatewayUrl>
				<dss-serviceUrl>http://pqa-portal.waseel.com:8081</dss-serviceUrl>
				<idf-serviceUrl>http://pqa-portal.waseel.com:8082</idf-serviceUrl>
				<fdb-serviceUrl>http://pqa-portal.waseel.com:8083</fdb-serviceUrl>
				<rts-serviceUrl>http://pqa-portal.waseel.com:8084</rts-serviceUrl>
				<payer-customization-serviceUrl>http://payer-customization-service-prod-service:8080</payer-customization-serviceUrl>
				<pbm-admin-service-serviceUrl>http://admin-service-prod-service:8080</pbm-admin-service-serviceUrl>
				<oauthUrl>http://pbm-authentication-server:8080</oauthUrl>
				<prescription-service-serviceUrl>http://prescription-service-prod-deployment:8080</prescription-service-serviceUrl>
				<pbm-notification-service-serviceUrl>http://pbm-notification-service:8080</pbm-notification-service-serviceUrl>
				<dss-admin-service-serviceUrl>http://dss-admin-service:8080</dss-admin-service-serviceUrl>
			</properties>
		</profile>
	</profiles>
	<dependencies>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-gateway</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-resource-server</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-oauth2-client</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-jose</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webflux-core</artifactId>
			<version>1.6.10</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webflux-ui</artifactId>
			<version>1.6.10</version>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
			<version>7.2</version>
		</dependency>
		<dependency>
			<groupId>co.elastic.apm</groupId>
			<artifactId>apm-agent-attach</artifactId>
			<version>1.31.0</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<releases>
				<enabled>false</enabled>
			</releases>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
</project>
