apiVersion: apps/v1
kind: Deployment
metadata:
  name: dss-admin-service
  namespace: pbm-stg
  labels:
    app: dss-admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dss-admin-service
  template:
    metadata:
      labels:
        app: dss-admin-service
    spec:
      containers:
        - name: dss-admin-service-stg-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm/stg/dss-admin-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: MDSS_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MDSS_USERNAME
          - name: MDSS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: MDSS_PASSWORD
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
