spring.h2.console.enabled = true
spring.h2.console.path = /h2

spring.datasource.hira.jdbc-url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS PBM_ADMIN
spring.datasource.medk_fdb.jdbc-url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS PBM_ADMIN
spring.datasource.hira.username=sa
spring.datasource.hira.password=sa
spring.datasource.medk_fdb.username=sa
spring.datasource.medk_fdb.password=sa

spring.datasource.businessrules.jdbc-url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS PBM_BUSINESS_RULES
spring.datasource.businessrules.username=testPbmAdmin
spring.datasource.businessrules.password=testPbmAdmin

spring.datasource.mdss.jdbc-url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS MDSS
spring.datasource.mdss.username=testPbmAdmin
spring.datasource.mdss.password=testPbmAdmin
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.enabled=false
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

#---------------------------------
#Actuators  configuration
#-----------------------------------
management.security.enabled = false
management.endpoints.web.exposure.include=*
info.app.name=Admin-Service
info.app.java.version=11
info.app.type=Spring Boot-Microservice


pbmPayerApisServiceClient.url:http://pbm-payer-apis-service.pbm-qa:8080/pbm-payer-apis-service
dssAdminSerivceClient.url:http://dss-admin-service.pbm-qa:8080