spring.datasource.mdss.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.mdss.username=${MDSS_USERNAME}
spring.datasource.mdss.password=${MDSS_PASSWORD}
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=1
spring.datasource.mdss.maximumPoolSize=1

spring.datasource.medk-fdb.jdbc-url=jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.medk-fdb.username=${MEDK_FDB_USERNAME}
spring.datasource.medk-fdb.password=${MEDK_FDB_PASSWORD}
spring.datasource.medk-fdb.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.medk-fdb.connectionTimeout=3600000
spring.datasource.medk-fdb.idleTimeout=600000
spring.datasource.medk-fdb.minimumIdle=5
spring.datasource.medk-fdb.maximumPoolSize=10

spring.datasource.hira.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.hira.username=${HIRA_USERNAME}
spring.datasource.hira.password=${HIRA_PASSWORD}
spring.datasource.hira.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hira.connectionTimeout=3600000
spring.datasource.hira.idleTimeout=600000
spring.datasource.hira.minimumIdle=1
spring.datasource.hira.maximumPoolSize=1

spring.datasource.businessrules.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.businessrules.username=${PBM_BUSINESS_RULES_USERNAME}
spring.datasource.businessrules.password=${PBM_BUSINESS_RULES_PASSWORD}
spring.datasource.businessrules.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.businessrules.connectionTimeout=3600000
spring.datasource.businessrules.idleTimeout=600000
spring.datasource.businessrules.minimumIdle=1
spring.datasource.businessrules.maximumPoolSize=1

spring.datasource.prescriptionservice.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.prescriptionservice.username=${PRESCRIPTION_SERVICE_USERNAME}
spring.datasource.prescriptionservice.password=${PRESCRIPTION_SERVICE_PASSWORD}
spring.datasource.prescriptionservice.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.prescriptionservice.connectionTimeout=3600000
spring.datasource.prescriptionservice.idleTimeout=600000
spring.datasource.prescriptionservice.minimumIdle=1
spring.datasource.prescriptionservice.maximumPoolSize=1

spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect

#---------------------------------
#Liquibase configuration
#-----------------------------------
spring.liquibase.enabled=true
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=MDSS

#---------------------------------
#Actuators  configuration
#-----------------------------------
management.security.enabled = false
management.endpoints.web.exposure.include=*
info.app.name=Admin-Service
info.app.java.version=11
info.app.type=Spring Boot-Microservice


pbmPayerApisServiceClient.url:http://pbm-payer-apis-service.pbm-stg:8080/pbm-payer-apis-service
dssAdminSerivceClient.url:http://dss-admin-service.pbm-stg:8080

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
