apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility-service-qa-deployment
  namespace: pbm-qa
  labels:
    app: eligibility-service-qa-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eligibility-service-qa-deployment
  template:
    metadata:
      labels:
        app: eligibility-service-qa-deployment
    spec:
      containers:
        - name: eligibility-service-qa-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-qa/eligibility-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
