#Logging Configuration
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
spring.jpa.database=default
#-------------------------------------------------

#DataBase Configuration

spring.datasource.medk-fdb.jdbc-url=jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.medk-fdb.username=${MEDK_FDB_USERNAME}
spring.datasource.medk-fdb.password=${MEDK_FDB_PASSWORD}
spring.datasource.medk-fdb.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.medk-fdb.connectionTimeout=3600000
spring.datasource.medk-fdb.idleTimeout=600000
spring.datasource.medk-fdb.minimumIdle=5
spring.datasource.medk-fdb.maximumPoolSize=10

spring.datasource.mdss.jdbc-url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
spring.datasource.mdss.username=${MDSS_USERNAME}
spring.datasource.mdss.password=${MDSS_PASSWORD}
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=5
spring.datasource.mdss.maximumPoolSize=5

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect


#Liquibase configuration

spring.liquibase.enabled=true
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=MDSS

# MongoDB
#-----------------
spring.data.mongodb.database=PBM_STG
spring.data.mongodb.uri=mongodb://PBM_test:ENt4356PestM@tst-mongo-upgrade-tbd-1.devdbsn.wslvcn.oraclevcn.com:27017,test-mongo-upgrade-tbd.devdbsn.wslvcn.oraclevcn.com:27017/test?authSource=PBM&replicaSet=tst-mongo-01&maxPoolSize=400&maxIdleTimeMS=60000&readPreference=primary&appname=MongoDB%20Compass&ssl=false

spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true

#Singlton values Configuration 

medk-framwork.url = jdbc:oracle:thin:@adbstage_low?TNS_ADMIN=/opt/wallet/
medk-framwork.username=${MEDK_FRAMWORK_USERNAME}
medk-framwork.password=${MEDK_FRAMWORK_PASSWORD}
medk-framwork.driver=oracle.jdbc.driver.OracleDriver
medk-framwork.UseJNDI= false
medk-framwork.poolPreparedStatements = true
medk-framwork.maxOpenPreparedStatements = 200
medk-framwork.initialPoolSize = 5
medk-framwork.maxPoolSize=10
medk-framwork.maxIdlePoolSize=10
medk-framwork.minIdlePoolSize=5
