# Waseel Sms configuration
clients.unifonic.url:https://el.cloud.unifonic.com/rest/SMS/messages
clients.waseel-sms.url:https://smsgw.waseel.com/services/send.php

#----------------------
#DataBase Configuration
#----------------------
spring.h2.console.enabled = true
spring.h2.console.path = /h2
spring.datasource.url = jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS PBM_SCHEDULER
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


spring.security.oauth2.resourceserver.opaquetoken.introspection-uri: https://qa-iam.waseel.com/realms/waseel-stg/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id: SMS_SERVICE_CLIENT_ID
spring.security.oauth2.resourceserver.opaquetoken.client-secret: SMS_SERVICE_CLIENT_SECRET