# Waseel Sms configuration
clients.unifonic.url:https://el.cloud.unifonic.com/rest/SMS/messages
clients.waseel-sms.url:https://smsgw.waseel.com/services/send.php


#----------------------
#DataBase Configuration
#----------------------
spring.datasource.url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/wallet/
spring.datasource.username = ${HIRA_USERNAME}
spring.datasource.password = ${HIRA_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.connection-timeout=3600000
spring.datasource.idleTimeout=600000
spring.datasource.minimumIdle=1
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.default_schema=HIRA
spring.jpa.show-sql=true


spring.security.oauth2.resourceserver.opaquetoken.introspection-uri: https://iam.waseel.com/realms/waseel-prod/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id: ${SMS_SERVICE_CLIENT_ID}
spring.security.oauth2.resourceserver.opaquetoken.client-secret: ${SMS_SERVICE_CLIENT_SECRET}
#--------
# MongoDB
#--------
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM:Toyxe3dsDcHy025@mongo-db.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-02.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-03.prddbsn.wslvcn.oraclevcn.com:27017/PBM?authSource=PBM&replicaSet=prd-monog-replica&ssl=false&readPreference=primary&maxIdleTimeMS=60000&maxPoolSize=400
