#Logging Configuration
#-----------------------------------
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

#-----------------------------------
#DataBase Configuration
#-----------------------------------
spring.datasource.prescriptionservice.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=/wallet/
spring.datasource.prescriptionservice.username=prescription_service
spring.datasource.prescriptionservice.password=Dev#S92p$v3
spring.datasource.prescriptionservice.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.prescriptionservice.connectionTimeout=3600000
spring.datasource.prescriptionservice.idleTimeout=600000
spring.datasource.prescriptionservice.minimumIdle=1
spring.datasource.prescriptionservice.maximumPoolSize=1

spring.datasource.businessrules.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=/wallet/
spring.datasource.businessrules.username=PBM_business_rules
spring.datasource.businessrules.password=fs#8o2dsJ3Q$kZ
spring.datasource.businessrules.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.businessrules.connectionTimeout=3600000
spring.datasource.businessrules.idleTimeout=600000
spring.datasource.businessrules.minimumIdle=1
spring.datasource.businessrules.maximumPoolSize=1

spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#------------------------------
#Liquibase configuration
#------------------------------
spring.priscriptionservice.liquibase.enabled=true
logging.level.liquibase = INFO
spring.priscriptionservice.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.priscriptionservice.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.priscriptionservice.liquibase.database-change-log-table=DATABASECHANGELOG
spring.priscriptionservice.default-schema=prescription_service


spring.businessrules.liquibase.enabled=true
spring.businessrules.liquibase.change-log=classpath:/database/db.changelog-businessrules.yaml
spring.businessrules.default-schema=PBM_business_rules
spring.businessrules.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.businessrules.liquibase.database-change-log-table=DATABASECHANGELOG

#------------------------------
#Client configuration
#------------------------------
#client.tawuniya.url:https://mock.waseel.com/rest/Tawuniya+Apis/1.2
client.tawuniya.url:https://webapisdev.tawuniya.com.sa:5556/gateway/tawnEprescription
clients.tawuniya.apiKey:apiKey
clients.tawuniya.senderCode:101
clients.tawuniya.receiverCode:102
clients.tawuniya.direction:REQUEST

client.prescription.url:http://prescription-service-qa-service.pbm-qa:8080
client.EmailServiceClient.url:http://email-service.pbm-qa:8080/api

#----------------------------------------
#Waseel Sms service client configuration
#----------------------------------------
waseelSmsService.url=http://waseel-sms-service.pbm-qa:8080

#-----------------------------------
#Unifonic request details
#-----------------------------------
unifonic.appSid= ${UNIFONIC_APP_SID}
unifonic.senderId= ${UNIFONIC_SENDER_ID}
unifonic.appName= ${UNIFONIC_APP_NAME}

#--------------------------
#SSO token details details
#--------------------------
sso.url = ${SSO_URL}
sso.auth.username:${SSO_USERNAME}
sso.auth.password:${SSO_PASSWORD}
sso.content.type:${SSO_REQUEST_BODY_CONTENT_TYPE}
sso.body.key:${SSO_REQUEST_BODY_KEY}
sso.body.value:${SSO_REQUEST_BODY_VALUE}
