# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy on QA with ADB

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Start validate phase with maven to install 3rd party jars
      run: mvn validate
    - name: Build with Maven
      run: mvn package --file pom.xml install -DskipTests -Dpackaging=jar -Dmaven.javadoc.skip=true -Dmaven.site.skip=true -Dmaven.source.skip=true -Djacoco.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dpmd.skip=true -Dfabric8.skip=true -e -B -Pociqaadb

    - name: Docker Login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login me-jeddah-1.ocir.io -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Docker Build
      run: docker build . -t me-jeddah-1.ocir.io/ax7dvcawpc84/qa/eligibility:latest -t me-jeddah-1.ocir.io/ax7dvcawpc84/qa/eligibility:${{ github.sha }}

    - name: Docker Push
      run: docker push --all-tags me-jeddah-1.ocir.io/ax7dvcawpc84/qa/eligibility
    
    - name: Deploy to K8S
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.ECLAIMS_KUBE_CONFIG_QA }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: set image --record deployment/eligibility eligibility=me-jeddah-1.ocir.io/ax7dvcawpc84/qa/eligibility:${{ github.sha }} -n qa
      
    - name: Verify Deployment
      uses: waseel-asp/kubectl@v1.17.9
      env:
        KUBE_CONFIG: ${{ secrets.ECLAIMS_KUBE_CONFIG_QA }}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        args: '"rollout status deployment/eligibility -n qa"'
