apiVersion: apps/v1
kind: Deployment
metadata:
  name: eligibility-service-stg-deployment
  namespace: pbm-stg
  labels:
    app: eligibility-service-stg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eligibility-service-stg-deployment
  template:
    metadata:
      labels:
        app: eligibility-service-stg-deployment
    spec:
      containers:
        - name: eligibility-service-stg-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-stg/eligibility-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          - name: PBM_BUSINESS_RULES_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PBM_BUSINESS_RULES_USERNAME
          - name: PBM_BUSINESS_RULES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secrets
                key: PBM_BUSINESS_RULES_PASSWORD
          - name: PORTAL_USERNAME
            valueFrom:
              secretKeyRef:
                name: portal-credintails
                key: PORTAL_USERNAME
          - name: PORTAL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: portal-credintails
                key: PORTAL_PASSWORD
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
