--liquibase formatted sql

--changeset Prescription:0033

CREATE TABLE MEMBER_POLICY_USAGE 
(
  MEMBER_POLICY_USAGE_ID NUMBER NOT NULL 
, PAYER_ID VARCHAR2(20) NOT NULL 
, PROVIDER_ID VARCHAR2(20) NOT NULL 
, MEMBER_ID VARCHAR2(50) NOT NULL 
, ID_NUMBER NUMBER NOT NULL 
, POLICY_NUMBER VARCHAR2(50) NOT NULL 
, POLICY_CLASS VARCHAR2(50) NOT NULL 
, POLICY_BENEFIT VARCHAR2(30) NOT NULL 
, BENEFIT_LIMIT_VALUE NUMBER NOT NULL 
, BENEFIT_LIMIT_CURRENCY VARCHAR2(30) NOT NULL 
, BENEFIT_LOCKED_AMOUNT_VALUE NUMBER NOT NULL 
, BENEFIT_LOCKED_AMOUNT_CURRENCY VARCHAR2(30) NOT NULL 
, BENEFIT_REMAINNING_LIMIT_VALUE NUMBER NOT NULL 
, BENEFIT_REMAINNING_LIMIT_CURRENCY VARCHAR2(30) NOT NULL 
, EPRESCRIPTION_REFERENCE_NUMBER VARCHAR2(100) NOT NULL 
, EPRESCRIPTION_STATUS VARCHAR2(50) NOT NULL 
, CONSTRAINT MEMBER_POLICY_USAGE_PK PRIMARY KEY(MEMBER_POLICY_USAGE_ID)
);

CREATE SEQUENCE "PRESCRIPTION_SERVICE".PS_MEMBER_POLICY_USAGE_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;