--liquibase formatted sql

--changeset Prescription:0035

CREATE TABLE "PRESCRIPTION_SERVICE".PRESCRIPTION_REJECTION 
(
  PRESCRIPTION_REJECTION_ID NUMBER NOT NULL 
, DENIAL_CODE VARCHAR2(30) NOT NULL 
, REJECTION_REASON VARCHAR2(2500) NOT NULL 
, REQUEST_ID VARCHAR2(100) NOT NULL 
, ELIGIBILITY_REFERENCE_NUMBER VARCHAR2(40) NOT NULL 
, CONSTRAINT PK_PRESCRIPTION_REJECTION_ID PRIMARY KEY(PRESCRIPTION_REJECTION_ID)
);

CREATE SEQUENCE "PRESCRIPTION_SERVICE".PS_PRESCRIPTION_REJECTION_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;