--liquibase formatted sql

--changeset Prescription:0039

CREATE TABLE PRESCRIPTION_SERVICE.PRESCRIPTION_APPROVAL_ASSC
(
	PRESCRIPTION_APPROVAL_ASSC_ID NUMBER NOT NULL,
   	APPROVAL_REFERENCE_NUMBER  VARCHAR2(200)  NOT NULL,
    CREATED_DATE DATE NOT NULL,
    EPRESCRIPTION_REFERENCE_NUMBER VARCHAR2(100) NOT NULL,
    REQUEST_TYPE  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_PAPRASSC_PAPRASSCID PRIMARY KEY (PRESCRIPTION_APPROVAL_ASSC_ID)
);

CREATE SEQUENCE PRESCRIPTION_SERVICE.SEQ_PRESCRIPTION_APPROVAL_ASSC
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;