--liquibase formatted sql

--changeset Prescription:0040

ALTER TABLE MEMBER_POLICY_USAGE DROP COLUMN BENEFIT_LOCKED_AMOUNT_VALUE;

ALTER TABLE MEMBER_POLICY_USAGE DROP COLUMN BENEFIT_LOCKED_AMOUNT_CURRENCY;

ALTER TABLE MEMBER_POLICY_USAGE  MODIFY (POLICY_BENEFIT NULL );

ALTER TABLE MEMBER_POLICY_USAGE RENAME COLUMN BENEFIT_REMAINNING_LIMIT_VALUE TO BENEFIT_REMAINING_LIMIT_VALUE;

ALTER TABLE MEMBER_POLICY_USAGE RENAME COLUMN BENEFIT_REMAINNING_LIMIT_CURRENCY TO BENEFIT_REMAINING_LIMIT_CURRENCY;
