--liquibase formatted sql

--changeset Prescription:0041

ALTER TABLE PRESCRIPTION_REJECTION ADD (SHOW_UNDER_BUSINESS_VALIDATION CHAR(1) DEFAULT '1' NULL);
ALTER TABLE PRESCRIPTION_REJECTION MODIFY (SHOW_UNDER_BUSINESS_VALIDATION CHAR(1) NOT NULL  ENABLE NOVALIDATE);
