--liquibase formatted sql

--changeset Prescription:0045

ALTER TABLE PRESCRIPTION_SERVICE.PRESCRIPTION_REJECTION ADD (IS_MODIFIED_BY_PAYER CHAR(1) DEFAULT ('0'));
ALTER TABLE PRESCRIPTION_SERVICE.PRESCRIPTION_REJECTION MODIFY (IS_MODIFIED_BY_PAYER CHAR(1) NOT NULL  ENABLE NOVALIDATE);