--liquibase formatted sql

--changeset Prescription:0049

CREATE SEQUENCE "PRESCRIPTION_SERVICE".PAYER_ID_MAPPING_SEQ
MINVALUE 1
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE TABLE "PRESCRIPTION_SERVICE".PAYER_ID_MAPPING
(
    ID NUMBER DEFAULT "PRESCRIPTION_SERVICE".PAYER_ID_MAPPING_SEQ.NEXTVAL NOT NULL,
    TRANSACTION_TYPE VARCHAR2(30) NOT NULL,
    PAYER_ID VARCHAR2(30) NOT NULL,
    MAPPED_PAYER_ID VARCHAR2(30) NOT NULL,
    CONSTRAINT PK_PAYER_ID_MAPPING PRIMARY KEY (ID)
);
