--liquibase formatted sql

--changeset Prescription:0051

ALTER TABLE PAYER_ID_MAPPING ADD (IS_ENABLED CHAR(1) DEFAULT ('1') NOT NULL);

ALTER TABLE PAYER_ID_MAPPING RENAME COLUMN ID TO MAPPING_ID;

ALTER TABLE PAYER_ID_MAPPING ADD CONSTRAINT UK_PAYER_ID_MAPPING UNIQUE (TRANSACTION_TYPE, PAYER_ID) ENABLE;