--liquibase formatted sql

--changeset Prescription:0053

CREATE SEQUENCE "PRESCRIPTION_SERVICE".SEQ_PRESCRIPTION_APPROVAL_DRUG
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;

CREATE TABLE "PRESCRIPTION_SERVICE".PRESCRIPTION_APPROVAL_DRUG
(
  PRESCRIPTION_APPROVAL_DRUG_ID NUMBER DEFAULT "PRESCRIPTION_SERVICE".SEQ_PRESCRIPTION_APPROVAL_DRUG.NEXTVAL NOT NULL,
  EPRESCRIPTION_REFERENCE_NUMBER VARCHAR2(100) NOT NULL,
  SCIENTIFIC_CODE  VARCHAR2(200)  NOT NULL,
  SUGGESTED_DRUG_CODE  VARCHAR2(200)  NOT NULL,
  STATUS VARCHAR2(100) NOT NULL,  
  LATEST_UPDATE_DATE TIMESTAMP(6) NOT NULL,
  
  CONSTRAINT PK_PRESCRIPTION_APPROVAL_DRUG PRIMARY KEY (PRESCRIPTION_APPROVAL_DRUG_ID)
);
