--liquibase formatted sql

--changeset Prescription:0055

CREATE SEQUENCE "PRESCRIPTION_SERVICE".SEQ_OVERRIDDEN_MEDICATION
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;

CREATE TABLE "PRESCRIPTION_SERVICE"."OVERRIDDEN_MEDICATION" (
  "OVERRIDDEN_MEDICATION_ID" NUMBER DEFAULT "PRESCRIPTION_SERVICE"."SEQ_OVERRIDDEN_MEDICATION".NEXTVAL NOT NULL,
  "EPRESCRIPTION_REFERENCE_NUMBER" VARCHAR2(100) NOT NULL,
  "PROVIDER_ID" VARCHAR2(20) NOT NULL,
  "PROVIDER_NAME" VARCHAR2(100) NOT NULL,
  "PAYER_ID" VARCHAR2(20) NOT NULL,
  "DRUG_CODE" VARCHAR2(50) NOT NULL,
  "DRUG_NAME" VARCHAR2(100),
  "DENIAL_CODE" VARCHAR2(30) NOT NULL,
  "REJECTION_REASON" VARCHAR2(2500) NOT NULL,
  "OVERRIDING_REASON" VARCHAR2(2500),
  "OVERRIDDEN_DATE" TIMESTAMP(6) NOT NULL,
  "OVERRIDDEN_BY" VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_OVERRIDDEN_MEDICATION PRIMARY KEY ("OVERRIDDEN_MEDICATION_ID")
);