--liquibase formatted sql

--changeset Prescription:0056

CREATE SEQUENCE "PRESCRIPTION_SERVICE".SEQ_ELIGIBLE_DSS_POLICY
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;

CREATE TABLE "PRESCRIPTION_SERVICE"."ELIGIBLE_DSS_POLICY" (
  "ELIGIBLE_DSS_POLICY_ID" NUMBER DEFAULT "PRESCRIPTION_SERVICE"."SEQ_ELIGIBLE_DSS_POLICY".NEXTVAL NOT NULL,
  "POLICY_NUMBER" VARCHAR2(50) NOT NULL,
  "POLICY_HOLDER_NAME" VARCHAR2(100) NOT NULL,
  "POLICY_CLASS" VARCHAR2(50) NOT NULL,
  "IS_ENABLED" VARCHAR2(20) NOT NULL,
  "UPDATED_BY" VARCHAR2(100) NOT NULL,
  "LAST_UPDATED_DATE" TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_ELIGIBLE_DSS_POLICY PRIMARY KEY ("ELIGIBLE_DSS_POLICY_ID")
);