--liquibase formatted sql

--changeset Prescription:0057

ALTER TABLE "PRESCRIPTION_SERVICE"."OVERRIDDEN_MEDICATION" 
  ADD(  "SCIENTIFIC_CODE" VARCHAR2(100),"SCIENTIFIC_NAME" VARCHAR2(100));
  
ALTER TABLE "PRESCRIPTION_SERVICE"."OVERRIDDEN_MEDICATION" modify (DRUG_CODE null);