spring.datasource.mdss.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.mdss.username=MDSS
spring.datasource.mdss.password=Dev#$#MSpro$#3234
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=1
spring.datasource.mdss.maximumPoolSize=1
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect


spring.datasource.hira.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.hira.username=hira
spring.datasource.hira.password=ADBPortal_HI2021
spring.datasource.hira.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hira.connectionTimeout=3600000
spring.datasource.hira.idleTimeout=600000
spring.datasource.hira.minimumIdle=1
spring.datasource.hira.maximumPoolSize=1
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect

spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true
logging.level.com.zaxxer.hikari.HikariConfig=TRACE

#-----------------
# MongoDB
#-----------------
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM_test:ENt4356PestM@tst-mongo-upgrade-tbd-1.devdbsn.wslvcn.oraclevcn.com:27017,test-mongo-upgrade-tbd.devdbsn.wslvcn.oraclevcn.com:27017/test?authSource=PBM&replicaSet=tst-mongo-01&maxPoolSize=400&maxIdleTimeMS=60000&readPreference=primary&appname=MongoDB%20Compass&ssl=false

server.port:8084

#---------------------------------
#Actuators  configuration
#-----------------------------------
management.security.enabled = false
management.endpoints.web.exposure.include=*
info.app.name=RTS-Service
info.app.java.version=11
info.app.type=Spring Boot-Microservice
