--liquibase formatted sql

--changeset Policy Consumption Service:0001

CREATE TABLE PBM_BUSINESS_RULES.PRESCRIPTION_METADATA 
(
  ID NUMBER NOT NULL 
, REQUEST_ID VARCHAR2(100) NOT NULL 
, PATIENT_SHARE NUMBER NOT NULL 
, PAYER_SHARE NUMBER NOT NULL 
, REMAINING_LIMIT NUMBER NOT NULL 
, BENEFIT_LIMIT_VALUE NUMBER NOT NULL 
, BENEFIT_LIMIT_CURR VARCHAR2(30) NOT NULL 
, BENEFIT_LOCKED_AMOUNT_VALUE NUMBER NOT NULL 
, BENEFIT_LOCKED_AMOUNT_CURR VARCHAR2(30) NOT NULL 
, POLICY_NUMBER NUMBER NOT NULL 
, MEMBER_BENEFIT_ASSOCIATION_ID NUMBER NOT NULL, 
CONSTRAINT PK_PRESCRIPTION_METADATA PRIMARY KEY (ID),
CONSTRAINT UK_REQUEST_ID UNIQUE (REQUEST_ID),
CONSTRAINT FK_MEMBER_BENEFIT_ASSOCIATION_ID FOREIGN KEY (MEMBER_BENEFIT_ASSOCIATION_ID) REFERENCES PBM_BUSINESS_RULES.MEMBER_BENEFIT_ASSOICATION (MEMBER_BENEFIT_ASSOICATION_ID)
);