--liquibase formatted sql

--changeset Policy Consumption Service:0008

CREATE TABLE PBM_BUSINESS_RULES.GENERIC_IRREPLICABLE_BRAND 
(
  GENERIC_IRREPLICABLE_BRAND_ID NUMBER NOT NULL,
  DRUGCODE VARCHAR2(50) NOT NULL,
  TRADE_NAME  VARCHAR2(256) NOT NULL, 
  PAYERID  NUMBER NOT NULL, 
  IS_DELETED  char(1) DEFAULT ('0'),
  DELETED_BY   VARCHAR2(50) NOT NULL, 
  LAST_UPDATE_DATE DATE,
CONSTRAINT PK_GENERIC PRIMARY KEY (GENERIC_IRREPLICABLE_BRAND_ID),
CONSTRAINT UK_GENERIC UNIQUE (DRUGCODE, PAYERID)
);