--liquibase formatted sql

--changeset Policy Consumption Service:0008

ALTER TABLE PRESCRIPTION_METADATA DROP COLUMN BENEFIT_LOCKED_AMOUNT_VALUE;

ALTER TABLE PRESCRIPTION_METADATA DROP COLUMN BENEFIT_LOCKED_AMOUNT_CURR;