--liquibase formatted sql

--changeset Policy Consumption Service:0009

CREATE TABLE PBM_BUSINESS_RULES.REPLICABLE_BRAND 
(
  REPLICABLE_BRAND_ID NUMBER NOT NULL,
  DRUGCODE VARCHAR2(50) NOT NULL,
  TRADE_NAME VARCHAR2(256) NOT NULL, 
  PAYERID NUMBER NOT NULL, 
  IS_DELETED char(1) DEFAULT ('0'),
  DELETED_BY VARCHAR2(50) NOT NULL, 
  LAST_UPDATE_DATE DATE,
CONSTRAINT PK_REPLACBLE PRIMARY KEY (REPLICABLE_BRAND_ID),
CONSTRAINT UK_REPLACBLE UNIQUE (DRUGCODE, PAYERID)
);