apiVersion: apps/v1
kind: Deployment
metadata:
  name: payer-customization-service-stg-deployment
  namespace: pbm-stg
  labels:
    app: payer-customization-service-stg-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payer-customization-service-stg-deployment
  template:
    metadata:
      labels:
        app: payer-customization-service-stg-deployment
    spec:
      containers:
        - name: payer-customization-service-stg-container
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-stg/payer-customization-service:latest
          env:
          - name: TZ
            value: Asia/Riyadh
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: waseel-docker-registry-cred
