--liquibase formatted sql

--changeset Fdb:6



CREATE TABLE "MDSS"."FDB_NOT_EXIST_DIAGNOSIS"
(
  ICD_CODE VARCHAR2(10) NOT NULL,
  REQUEST_ID VARCHAR2(100) NOT NULL,
  CONSTRAINT PK_NOT_EXIST_DIAGNOSIS PRIMARY KEY(ICD_CODE,REQUEST_ID)
);

