apiVersion: v1
kind: Service
metadata:
  name: rts-service-stg-service
  namespace: pbm-stg
  labels:
    app: rts-service-stg-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: rts-service-stg-deployment
