#spring.datasource.url= jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/opt/wallet
#spring.datasource.username=-----------
#spring.datasource.password=-----------
#spring.datasource.hikari.connectionTimeout=3600000
#spring.datasource.hikari.idleTimeout=600000
#spring.datasource.hikari.minimumIdle=20
#spring.datasource.hikari.maximumPoolSize=100

# Key store to hold the certificate/private key that is being published.
#server.ssl.key-store=classpath:keystore2021.jks
# Trust store that holds SSL certificates.
#server.ssl.trust-store=classpath:trustStore.jks
# Password used to access the trust store.
#server.ssl.trust-store-password=changeit
# Type of the trust store.
#server.ssl.trust-store-type=JKS
# Whether client authentication is wanted ("want") or needed ("need").
#server.ssl.client-auth=want