--liquibase formatted sql

--changeset Eligibility Service:0002

ALTER TABLE "PBM_BUSINESS_RULES".TRANSACTION_LOG ADD (TRANSACTION_STATUS VARCHAR2(100) NULL);
ALTER TABLE "PBM_BUSINESS_RULES".TRANSACTION_LOG MODIFY (TRANSACTION_STATUS VARCHAR2(100) NOT NULL  ENABLE NOVALIDATE);