apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbm-admin-ui
  namespace: pbm-stg
  labels:
    app: pbm-admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbm-admin-ui
  template:
    metadata:
      labels:
        app: pbm-admin-ui
    spec:
      containers:
        - name: pbm-admin-ui
          image: me-jeddah-1.ocir.io/ax7dvcawpc84/pbm-stg/pbm-admin-ui:latest
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: ocir-login-credentials