spring.datasource.url = jdbc:oracle:thin:@adbtest_tpurgent?TNS_ADMIN=/wallet
#spring.datasource.url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/walletV2
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect


spring.liquibase.enabled=false
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=CLAIM
spring.datasource.tomcat.initial-size=1
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=5
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.tomcat.max-idle=1
spring.datasource.tomcat.min-idle=1
spring.datasource.hikari.maxLifeTime : 1200000

spring.rabbitmq.host = rabbitmq-qa-headless
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest
spring.rabbitmq.listener.simple.prefetch=1

spring.jpa.show-sql=true

portal.url = https://devzero.waseel.com/WaseelSwitch/Uhud/Service?wsdl
settings-service.url=http://settings:8080

