spring.profiles.active=@activatedSpringProperties@

spring.jackson.time-zone=Asia/Riyadh
spring.jackson.locale=en-SA
#health check
management.endpoints.web.exposure.include=health,info,beans,env
management.endpoint.health.show-details=always

server.max-http-header-size=40KB