#spring.rabbitmq.host = devone.waseel.com
#spring.rabbitmq.port = 5672
#spring.rabbitmq.username = guest
#spring.rabbitmq.password = guest
#spring.rabbitmq.listener.simple.prefetch=1

spring.datasource.url = jdbc:oracle:thin:@adbtest_tpurgent?TNS_ADMIN=${HOMEPATH}/wallet
spring.datasource.username = claims
spring.datasource.password = kduStB04
spring.datasource.tomcat.initial-size=1
spring.datasource.tomcat.max-wait=20000
spring.datasource.tomcat.max-active=1
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.tomcat.max-idle=1
spring.datasource.tomcat.min-idle=1


#spring.datasource.url = jdbc:oracle:thin:@wsldev_medium?TNS_ADMIN=${user.home}/wallet
#spring.datasource.username = claims
#spring.datasource.password = fSDJNOFW#213

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=true

spring.liquibase.enabled=false
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=CLAIMS

portal.url = https://devzero.waseel.com/WaseelSwitch/Uhud/Service?wsdl
settings-service.url: http://localhost:8111