spring.rabbitmq.host = rabbitmq-prod-headless
spring.rabbitmq.port = 5672
spring.rabbitmq.username = rabbitmq
spring.rabbitmq.password = rabbitmq@123
spring.rabbitmq.listener.simple.prefetch=1

spring.datasource.url = jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/wallet
spring.datasource.username = ${DB_USERNAME}
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.maxLifeTime : 1200000
spring.datasource.hikari.idle-timeout: 90000
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.hikari.maximum-pool-size=5

portal.url = https://portal.waseel.com/WaseelSwitch/Uhud/Service?wsdl
settings-service.url:http://settings:8080

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.server.MessageTracing.sent=DEBUG
logging.level.org.springframework.ws.client.MessageTracing.received=TRACE
logging.level.org.springframework.ws.server.MessageTracing.received=TRACE