service_name=Eligibility
service_version= 1.0
application_packages=com.waseel.eligibility
server_urls=http://prod-apm:8200
#secret_token=7vxl8ndqx2rvktschdnfzwcj
#verify_server_cert=false
enable_log_correlation=true