apiVersion: v1
kind: Service
metadata:
  name: payer-customization-service-qa-service
  namespace: pbm-qa
  labels:
    app: payer-customization-service-qa-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
  selector:
    app: payer-customization-service-qa-deployment