#Logging Configuration
#-----------------------------------
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG
logging.level.org.hibernate.SQL=DEBUG
#---------------------------------
#DataBase Configuration
#-----------------------------------
spring.datasource.url=jdbc:oracle:thin:@waseeladb_tpurgent?TNS_ADMIN=/wallet/
spring.datasource.username=${PBM_BUSINESS_RULES_USERNAME}
spring.datasource.password=${PBM_BUSINESS_RULES_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.Oracle12cDialect
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.connection-timeout=300000
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#------------------------------
#Liquibase configuration
#------------------------------
spring.liquibase.enabled=true
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=PBM_business_rules
#--------------------------
#MongoDB
#--------------------------
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM:Toyxe3dsDcHy025@mongo-db.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-02.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-03.prddbsn.wslvcn.oraclevcn.com:27017/PBM?authSource=PBM&replicaSet=prd-monog-replica&ssl=false&readPreference=primary&maxIdleTimeMS=60000&maxPoolSize=400
