--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0003

CREATE TABLE PBM_BUSINESS_RULES.SPECIALITY
(
	SPECIALITY_ID NUMBER NOT NULL,
	SPECIALITY_NAME  VARCHAR2(100) NOT NULL,
	LAST_UPDATE_DATE  DATE DEFAULT SYSDATE NOT NULL,
	IS_DELETED  CHAR(1) DEFAULT ('0') NOT NULL,
	CONSTRAINT PK_SPECIALITY_SPECIALITY_ID PRIMARY KEY (SPECIALITY_ID),
	CONSTRAINT UK_SPECIALITY UNIQUE (SPECIALITY_NAME)
);
