--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0004

CREATE TABLE PBM_BUSINESS_RULES.DEPARTMENT
(
	DEPARTMENT_ID NUMBER NOT NULL,
	DEPARTMENT_NAME VARCHAR2(100) NOT NULL,
	LAST_UPDATE_DATE DATE DEFAULT SYSDATE NOT NULL ,
	IS_DELETED  CHAR(1) DEFAULT ('0') NOT NULL,
	CONSTRAINT PK_DEPARTMENT_DEPARTMENT_ID PRIMARY KEY (DEPARTMENT_ID),
	CONSTRAINT UK_DEPARTMENT UNIQUE (DEPARTMENT_NAME)
);
