--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0008

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
ADD PAYER_ID NUMBER NULL;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
MODIFY PAYER_ID NUMBER NOT NULL  ENABLE NOVALIDATE;
