--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0009

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
ADD CONSTRAINT UK_DEM_EXCLUSION_ID_PAYER_ID UNIQUE (EXCLUSION_ID,PAYER_ID);