--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0011

CREATE TABLE PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE
(
	MODULE_ID NUMBER NOT NULL,
    MODULE_NAME VARCHAR2(300) NOT NULL,
    CONSTRAINT PK_BRM_MODULE_ID PRIMARY KEY (MODULE_ID)
);