--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0012

CREATE TABLE PBM_BUSINESS_RULES.MODULE_CONFIGURATION
(
	PAYER_ID NUMBER NOT NULL,
    PROVIDER_ID NUMBER NOT NULL,
    MODULE_ID NUMBER NOT NULL,
    IS_ENABLED CHAR(1) DEFAULT ('1') NOT NULL,
    CONSTRAINT PK_MC_PAYID_PROID_MODID PRIMARY KEY (PAYER_ID,PROVIDER_ID,MODULE_ID),
    CONSTRAINT FK_MC_MODULE_ID
        FOREIGN KEY (MODULE_ID) REFERENCES PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE (MODULE_ID)
);