--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0013

INSERT ALL
  INTO PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE (MODULE_ID, MODULE_NAME) VALUES  (1, 'Exclusion Validation')
  INTO PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE (MODULE_ID, MODULE_NAME) VALUES  (2, 'Specialty Exclusion')
  INTO PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE (MODULE_ID, MODULE_NAME) VALUES  (3, 'Providers Exclusion')
  INTO PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE (MODULE_ID, MODULE_NAME) VALUES  (4, 'Networks Exclusion')
  INTO PBM_BUSINESS_RULES.BUSINESS_RULE_MODULE (MODULE_ID, MODULE_NAME) VALUES  (5, 'High Cost Drugs Exclusion')
SELECT 1 FROM DUAL;
COMMIT;