--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0020

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
ADD PAYER_ID NUMBER NULL;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
MODIFY PAYER_ID NUMBER NOT NULL  ENABLE NOVALIDATE;
