--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0021

ALTER TABLE PROVIDER_EXCLUSION_ASSC DROP CONSTRAINT UK_PROVIDER_EXCLUSION_ASSC;
ALTER TABLE PROVIDER_EXCLUSION_ASSC ADD CONSTRAINT UK_PEA_PROID_PID UNIQUE (PROVIDER_ID, PAYER_ID);
