--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0023

ALTER TABLE PBM_BUSINESS_RULES.DEPT_SPEC_PHYSC_ASSC
DROP CONSTRAINT  PK_DSPA_DSPASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.DEPT_SPEC_PHYSC_ASSC
ADD CONSTRAINT PK_DSPA_DSPASSC_ID PRIMARY KEY (DEPT_SPEC_PHYSC_ASSC_ID);