--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0024

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
DROP CONSTRAINT UK_NETWORK_EXC;

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
DROP CONSTRAINT PK_NETWORKID_ASSC_EXC;

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
DROP CONSTRAINT FK_NETWORK_ID_EXC;

CREATE SEQUENCE NETWORK_EXCLUSION_ASSC_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;
    
ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
ADD NETWORK_EXCLUSION_ASSC_ID_TEMP NUMBER;

UPDATE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
SET NETWORK_EXCLUSION_ASSC_ID_TEMP = NETWORK_EXCLUSION_ASSC_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
DROP COLUMN NETWORK_EXCLUSION_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
RENAME COLUMN NETWORK_EXCLUSION_ASSC_ID_TEMP TO NETWORK_EXCLUSION_ASSC_ID;    
    
ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
MODIFY NETWORK_EXCLUSION_ASSC_ID NUMBER DEFAULT NETWORK_EXCLUSION_ASSC_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
ADD CONSTRAINT PK_NETWORKID_ASSC_EXC PRIMARY KEY (NETWORK_EXCLUSION_ASSC_ID)    