--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0025

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
DROP CONSTRAINT FK_NETWORK_ID;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
DROP CONSTRAINT PK_NETWORKID_ASSC;

CREATE SEQUENCE PROVIDER_NETWORK_ASSC_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;
        
ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
ADD PROVIDER_NETWORK_ASSC_ID_TEMP NUMBER;

UPDATE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
SET PROVIDER_NETWORK_ASSC_ID_TEMP = PROVIDER_NETWORK_ASSC_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
DROP COLUMN PROVIDER_NETWORK_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
RENAME COLUMN PROVIDER_NETWORK_ASSC_ID_TEMP TO PROVIDER_NETWORK_ASSC_ID; 

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
MODIFY PROVIDER_NETWORK_ASSC_ID NUMBER DEFAULT PROVIDER_NETWORK_ASSC_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
ADD CONSTRAINT PK_NETWORKID_ASSC PRIMARY KEY (PROVIDER_NETWORK_ASSC_ID)    