--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0026

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK
DROP CONSTRAINT PK_NETWORKID;

CREATE SEQUENCE PROVIDER_NETWORK_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK
ADD NETWORK_ID_TEMP NUMBER;

UPDATE PBM_BUSINESS_RULES.PROVIDER_NETWORK
SET NETWORK_ID_TEMP = PROVIDER_NETWORK_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK
DROP COLUMN NETWORK_ID;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK
RENAME COLUMN NETWORK_ID_TEMP TO NETWORK_ID; 
    
ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK
MODIFY NETWORK_ID NUMBER DEFAULT PROVIDER_NETWORK_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK
ADD CONSTRAINT PK_NETWORKID PRIMARY KEY (NETWORK_ID)    