--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0027

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
ADD CONSTRAINT FK_NETWORK_ID_EXC FOREIGN KEY (NETWORK_ID)
REFERENCES PBM_BUSINESS_RULES.PROVIDER_NETWORK (NETWORK_ID);

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
ADD CONSTRAINT UK_NETWORK_EXC UNIQUE (NETWORK_ID,EXCLUSION_ID);