--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0028

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_NETWORK_ASSC
ADD CONSTRAINT FK_PRO_ASSC_NETWORK_ID FOREIGN KEY (NETWORK_ID)
REFERENCES PBM_BUSINESS_RULES.PROVIDER_NETWORK (NETWORK_ID);
