--liquibase formatted sql

--changeset PbmAdminService:0029


ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
DROP CONSTRAINT FK_DED_EXCLUSION_ID;

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
DROP CONSTRAINT FK_SEASSC_EXCLUSION_ID;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
DROP CONSTRAINT FK_PEA_EXCLUSION_ID;

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
DROP CONSTRAINT FK_EXCLUSION_ID_EXC;

ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
DROP CONSTRAINT FK_HCEA_EXCLUSION_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
DROP CONSTRAINT UK_DEM_EXCLUSION_ID_PAYER_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
DROP CONSTRAINT PK_DEM_EXCLUSION_ID;

CREATE SEQUENCE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
ADD EXCLUSION_ID_TEMP NUMBER;

UPDATE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
SET EXCLUSION_ID_TEMP = DRUG_EXCLUSION_METADATA_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
DROP COLUMN EXCLUSION_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
RENAME COLUMN EXCLUSION_ID_TEMP TO EXCLUSION_ID; 
    
ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
MODIFY EXCLUSION_ID NUMBER DEFAULT DRUG_EXCLUSION_METADATA_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
ADD CONSTRAINT PK_DEM_EXCLUSION_ID PRIMARY KEY (EXCLUSION_ID) 
