--liquibase formatted sql

--changeset PbmAdminService:0030

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA
ADD CONSTRAINT UK_DEM_EXCLUSION_ID_PAYER_ID UNIQUE (EXCLUSION_ID, PAYER_ID);

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
ADD CONSTRAINT FK_DED_EXCLUSION_ID FOREIGN KEY (EXCLUSION_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA (EXCLUSION_ID);

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
ADD CONSTRAINT FK_SEASSC_EXCLUSION_ID FOREIGN KEY (EXCLUSION_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA (EXCLUSION_ID);

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
ADD CONSTRAINT FK_PEA_EXCLUSION_ID FOREIGN KEY (EXCLUSION_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA (EXCLUSION_ID);

ALTER TABLE PBM_BUSINESS_RULES.NETWORK_EXCLUSION_ASSC
ADD CONSTRAINT FK_EXCLUSION_ID_EXC FOREIGN KEY (EXCLUSION_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA (EXCLUSION_ID);

ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
ADD CONSTRAINT FK_HCEA_EXCLUSION_ID FOREIGN KEY (EXCLUSION_ID)
REFERENCES PBM_BUSINESS_RULES.DRUG_EXCLUSION_METADATA (EXCLUSION_ID);
