--liquibase formatted sql

--changeset PbmAdminService:0032


ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
DROP CONSTRAINT PK_HCEA_HCEASS_ID;

ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
DROP CONSTRAINT UK_HCEA_EXCLUSION_ID_PAYER_ID;


CREATE SEQUENCE PBM_BUSINESS_RULES.HIGH_COST_EXC_ASSC_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
ADD HIGH_COST_EXCLUSION_ASSC_ID_T NUMBER;

UPDATE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
SET HIGH_COST_EXCLUSION_ASSC_ID_T = HIGH_COST_EXC_ASSC_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
DROP COLUMN HIGH_COST_EXCLUSION_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
RENAME COLUMN HIGH_COST_EXCLUSION_ASSC_ID_T TO HIGH_COST_EXCLUSION_ASSC_ID; 
    
ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
MODIFY HIGH_COST_EXCLUSION_ASSC_ID NUMBER DEFAULT HIGH_COST_EXC_ASSC_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.HIGH_COST_EXCLUSION_ASSC
ADD CONSTRAINT PK_HCEA_HCEASS_ID PRIMARY KEY (HIGH_COST_EXCLUSION_ASSC_ID) 
