--liquibase formatted sql

--changeset PbmAdminService:0032


ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
DROP CONSTRAINT PK_DED_DRUG_EXCLUSION_DETAILS_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
DROP CONSTRAINT UK_DED_EID_WDID_RN;


CREATE SEQUENCE PBM_BUSINESS_RULES.DRUG_EXC_DETAILS_SEQ
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
ADD DRUG_EXCLUSION_DETAILS_ID_T NUMBER;

UPDATE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
SET DRUG_EXCLUSION_DETAILS_ID_T = DRUG_EXC_DETAILS_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
DROP COLUMN DRUG_EXCLUSION_DETAILS_ID;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
RENAME COLUMN DRUG_EXCLUSION_DETAILS_ID_T TO DRUG_EXCLUSION_DETAILS_ID; 
    
ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
MODIFY DRUG_EXCLUSION_DETAILS_ID NUMBER DEFAULT DRUG_EXC_DETAILS_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
ADD CONSTRAINT PK_DED_DRUG_EXCLUSION_DETAILS_ID PRIMARY KEY (DRUG_EXCLUSION_DETAILS_ID) 
