--liquibase formatted sql

--changeset PbmAdminService:0035

ALTER TABLE PBM_BUSINESS_RULES.DRUG_EXCLUSION_DETAILS
ADD CONSTRAINT UK_DED_EID_WDID_RN UNIQUE (EXCLUSION_ID, WASEEL_DRUG_ID, REGISTRATION_NUMBER);
