--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0036

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
DROP CONSTRAINT PROVIDER_EXCLUSION_ASSC_PK;

CREATE SEQUENCE PROVIDER_EXCLUSION_ASSC_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
ADD PROVIDER_EXCLUSION_ASSC_ID_TEMP NUMBER;

UPDATE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
SET PROVIDER_EXCLUSION_ASSC_ID_TEMP = PROVIDER_EXCLUSION_ASSC_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
DROP COLUMN PROVIDER_EXCLUSION_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
RENAME COLUMN PROVIDER_EXCLUSION_ASSC_ID_TEMP TO PROVIDER_EXCLUSION_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
MODIFY PROVIDER_EXCLUSION_ASSC_ID NUMBER DEFAULT PROVIDER_EXCLUSION_ASSC_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.PROVIDER_EXCLUSION_ASSC
ADD CONSTRAINT PK_PROVIDER_EXC_ASSC PRIMARY KEY (PROVIDER_EXCLUSION_ASSC_ID)