--liquibase formatted sql

--changeset PbmAdminService:0037

-- Create the sequence
CREATE SEQUENCE PBM_BUSINESS_RULES.EXC_ASS_SEQ 
MINVALUE 1
MAXVALUE 999999999999999999999999999
START WITH 1
INCREMENT BY 1
CACHE 20;

-- Create the table
CREATE TABLE PBM_BUSINESS_RULES.EXCLUSION_ASSC_TYPE_LIST (
    EXC_LIST_ID NUMBER DEFAULT EXC_ASS_SEQ.nextval NOT NULL,
    EXCLUSION_ID NUMBER NOT NULL,
    NETWORK_ID NUMBER,
    PROVIDER_ID NUMBER,
    SPECIALITY_ID NUMBER,
    PAYER_ID NUMBER NOT NULL,
    EXCLUSION_TYPE VARCHAR(255) NOT NULL,
    EXCLUSION_ASSC_ID NUMBER NOT NULL,
    EXCLUSION_TYPE_NAME VARCHAR(255),
    CONSTRAINT PK_EXCLUSION_LIST_ASSC PRIMARY KEY (EXC_LIST_ID),
    CONSTRAINT UQ_EXCLUSION_PAYER_PROVIDER UNIQUE (EXCLUSION_ID, PAYER_ID, PROVIDER_ID),
    CONSTRAINT UQ_EXCLUSION_PAYER_SPECIALITY UNIQUE (EXCLUSION_ID, PAYER_ID, SPECIALITY_ID),
    CONSTRAINT UQ_EXCLUSION_PAYER_NETWORK UNIQUE (EXCLUSION_ID, PAYER_ID, NETWORK_ID)
);