--liquibase formatted sql

--changeset PbmAdminService:0038

ALTER TABLE PBM_BUSINESS_RULES.EXCLUSION_ASSC_TYPE_LIST 
DROP CONSTRAINT UQ_EXCLUSION_PAYER_PROVIDER
DROP CONSTRAINT UQ_EXCLUSION_PAYER_SPECIALITY 
DROP CONSTRAINT UQ_EXCLUSION_PAYER_NETWORK;
