--liquibase formatted sql

--changeset Drug Exclusion Validation Service:0041

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
DROP CONSTRAINT PK_SEASSC_SEASS_ID;

CREATE SEQUENCE SPECIALITY_EXCLUSION_ASSC_SEQ
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1
    NOCYCLE
    NOCACHE;

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
ADD SPECIALITY_EXCLUSION_ASSC_ID_TEMP NUMBER;

UPDATE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
SET SPECIALITY_EXCLUSION_ASSC_ID_TEMP = SPECIALITY_EXCLUSION_ASSC_SEQ.nextval;

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
DROP COLUMN SPECIALITY_EXCLUSION_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
RENAME COLUMN SPECIALITY_EXCLUSION_ASSC_ID_TEMP TO SPECIALITY_EXCLUSION_ASSC_ID;

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
MODIFY SPECIALITY_EXCLUSION_ASSC_ID NUMBER DEFAULT SPECIALITY_EXCLUSION_ASSC_SEQ.nextval NOT NULL;

ALTER TABLE PBM_BUSINESS_RULES.SPECIALITY_EXCLUSION_ASSC
ADD CONSTRAINT PK_SEASSC_SEASS_ID PRIMARY KEY (SPECIALITY_EXCLUSION_ASSC_ID)