spring.mail.sender=meetv@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Meet
spring.mail.password=nczfxi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.resourceserver.opaquetoken.introspection-uri: https:/test.test/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id: email-service
spring.security.oauth2.resourceserver.opaquetoken.client-secret: asdfsdfgghsFSDGGfghdfsg56fg46