#Logging Configuration
#-----------------------------------
logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG
logging.level.httpclient.wire=DEBUG

#Email configuration
spring.mail.sender=${MAIL_SENDER}
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri: https://iam.waseel.com/realms/waseel-prod/protocol/openid-connect/token/introspect
spring.security.oauth2.resourceserver.opaquetoken.client-id: ${EMAIL_SERVICE_CLIENT_ID}
spring.security.oauth2.resourceserver.opaquetoken.client-secret: ${EMAIL_SERVICE_CLIENT_SECRET}

#-----------------
# MongoDB
#-----------------
spring.data.mongodb.database=waseelswitch
spring.data.mongodb.uri=mongodb://waseelswitch:waseelPBM123@mongo-db.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-02.prddbsn.wslvcn.oraclevcn.com:27017,portal-mongo-db-03.prddbsn.wslvcn.oraclevcn.com:27017/waseelswitch?replicaSet=prd-monog-replica&ssl=false&maxIdleTimeMS=60000&maxPoolSize=400


