spring.profiles.active=@activatedSpringProperties@
spring.jackson.time-zone=Asia/Riyadh
spring.jackson.locale=en-SA

#=======================
#SWAGGER CONFIGURATION
#=======================
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.path=/emails/swagger-ui.html
springdoc.api-docs.path=/emails/v3/api-docs
sprindoc.swagger-ui.config-url=/emails/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/emails/v3/api-docs

server.servlet.context-path=/api
