spring.datasource.mdss.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.mdss.username=MDSS
spring.datasource.mdss.password=Dev#$#MSpro$#3234
spring.datasource.mdss.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.mdss.connectionTimeout=3600000
spring.datasource.mdss.idleTimeout=600000
spring.datasource.mdss.minimumIdle=1
spring.datasource.mdss.maximumPoolSize=1

spring.datasource.hira.jdbc-url = jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.hira.username=hira
spring.datasource.hira.password=ADBPortal_HI2021
spring.datasource.hira.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.hira.connectionTimeout=3600000
spring.datasource.hira.idleTimeout=600000
spring.datasource.hira.minimumIdle=1
spring.datasource.hira.maximumPoolSize=1

spring.datasource.medk-fdb.jdbc-url=jdbc:oracle:thin:@adbtest_low?TNS_ADMIN=${user.home}/wallet
spring.datasource.medk-fdb.username=MEDK_FDB
spring.datasource.medk-fdb.password=Xev$#aaFrs$321X
spring.datasource.medk-fdb.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.medk-fdb.connectionTimeout=3600000
spring.datasource.medk-fdb.idleTimeout=600000
spring.datasource.medk-fdb.minimumIdle=1
spring.datasource.medk-fdb.maximumPoolSize=1
#-----------------
# MongoDB
#-----------------
spring.data.mongodb.database=PBM
spring.data.mongodb.uri=mongodb://PBM_test:ENt4356PestM@tst-mongo-upgrade-tbd-1.devdbsn.wslvcn.oraclevcn.com:27017,test-mongo-upgrade-tbd.devdbsn.wslvcn.oraclevcn.com:27017/test?authSource=PBM&replicaSet=tst-mongo-01&maxPoolSize=400&maxIdleTimeMS=60000&readPreference=primary&appname=MongoDB%20Compass&ssl=false


logging.level.org.hibernate.SQL=DEBUG
spring.jpa.show-sql=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.globally_quoted_identifiers = true

#---------------------------------
#Authenication Configuration
#-----------------------------------
#security.oauth2.client.clientId: dssPBMService
#security.oauth2.client.clientSecret: dss!#45149832164
#security.oauth2.client.accessTokenUri = http://localhost:8080/pbm-authentication-service/check_token
#security.oauth2.resource.tokenInfoUri = http://localhost:8080/pbm-authentication-service/check_token
#security.oauth2.resource.userInfoUri= http://localhost:8080/pbm-authentication-service/users/current

#security.oauth2.client.accessTokenUri= http://pbm-authentication-service/pbm-authentication-service-qa-service:8080/check_token
#security.oauth2.resource.tokenInfoUri= http://pbm-authentication-service/pbm-authentication-service-qa-service:8080/check_token
#security.oauth2.resource.userInfoUri= http://pbm-authentication-service/pbm-authentication-service-qa-service:8080/users/current
#security.oauth2.client.grant-type: token
#security.oauth2.client.scope: server
#server.error.include-exception= true

server.port:8081

#---------------------------------
#Liquibase configuration
#-----------------------------------
spring.liquibase.enabled=false
logging.level.liquibase = INFO
spring.liquibase.change-log=classpath:/database/db.changelog-master.yaml
spring.liquibase.database-change-log-lock-table=DATABASECHANGELOGLOCK
spring.liquibase.database-change-log-table=DATABASECHANGELOG
spring.liquibase.default-schema=MDSS


idfvalidationservice.url:http://localhost:8082/idf-validation-service/validate
fdbvalidationservice.url:http://localhost:8083/fdb-validation-service/validate
rtsvalidationservice.url:http://localhost:8084/rts-service/validate
payercustomizationservice.url:http://localhost:8085/payer-customization-service/validate


#---------------------------------
#Actuators  configuration
#-----------------------------------
management.security.enabled = false
management.endpoints.web.exposure.include=*
info.app.name=Dss-Service
info.app.java.version=11
info.app.type=Spring Boot-Microservice

