--liquibase formatted sql

--changeset PbmAdminService:0013

CREATE SEQUENCE MDSS.CUSTOMIZATION_UPLOAD_AUDIT_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  NOCYCLE
  NOCACHE;

CREATE TABLE MDSS.CUSTOMIZATION_UPLOAD_AUDIT
(
	CUSTOMIZATION_UPLOAD_AUDIT_ID NUMBER DEFAULT CUSTOMIZATION_UPLOAD_AUDIT_SEQ.nextval NOT NULL,
    USER_ID  VARCHAR2(200) NOT NULL,
	ENTITY_ID  VARCHAR2(200) NOT NULL,
	ENTITY_NAME VARCHAR2(200) NOT NULL,
	ACTION VARCHAR2(200) NOT NULL,
	LAST_UPDATED_DATE DATE NOT NULL,
	CHANGE CLOB NULL,
	ACCOUNT_ID VARCHAR2(20) NOT NULL,
	CONSTRAINT PK_CUST_UPLOAD_AUDIT_ID PRIMARY KEY (CUSTOMIZATION_UPLOAD_AUDIT_ID)
);

